// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:10:29
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.http.*;
import java.math.BigDecimal;
import java.util.*;

import com.carddemo.controllers.TransactionAddController;
import com.carddemo.controllers.TransactionAddController.TransactionAddRequest;
import com.carddemo.controllers.TransactionAddController.ApiResponse;
import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;

class TransactionAddControllerTest {

    private TransactionAddController controller;

    @BeforeEach
    void setUp() {
        controller = new TransactionAddController();
        controller.initializeData();
    }

    @Test
    void testInitializeDataCreatesCardXrefRecords() {
        assertNotNull(controller);
    }

    @Test
    void testAddTransactionWithValidRequest() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "80000001001";
        request.cardNumber = "4111111111111111";
        request.transactionType = "PU";
        request.categoryCode = 5001;
        request.source = "ONLINE";
        request.description = "Test Transaction";
        request.amount = new BigDecimal("50.00");
        request.merchantId = 123456789L;
        request.merchantName = "Test Merchant";
        request.merchantCity = "Boston";
        request.merchantZip = "02101";

        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testAddTransactionWithNullRequest() {
        TransactionAddRequest request = new TransactionAddRequest();
        
        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testAddTransactionWithEmptyAccountId() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "";
        request.cardNumber = "4111111111111111";
        request.transactionType = "PU";
        request.amount = new BigDecimal("100.00");

        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testAddTransactionWithInvalidCardNumber() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "80000001001";
        request.cardNumber = "9999999999999999";
        request.transactionType = "PU";
        request.amount = new BigDecimal("100.00");

        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testAddTransactionWithNegativeAmount() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "80000001001";
        request.cardNumber = "4111111111111111";
        request.transactionType = "PU";
        request.amount = new BigDecimal("-50.00");

        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testAddTransactionWithZeroAmount() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "80000001001";
        request.cardNumber = "4111111111111111";
        request.transactionType = "PU";
        request.amount = BigDecimal.ZERO;

        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testAddTransactionWithDifferentTransactionTypes() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "80000002002";
        request.cardNumber = "4222222222222222";
        request.transactionType = "SA";
        request.categoryCode = 5002;
        request.source = "POS";
        request.description = "Sale Transaction";
        request.amount = new BigDecimal("200.00");
        request.merchantId = 987654321L;
        request.merchantName = "Sale Merchant";
        request.merchantCity = "Chicago";
        request.merchantZip = "60601";

        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testAddTransactionWithLargeAmount() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "80000001001";
        request.cardNumber = "4111111111111111";
        request.transactionType = "PU";
        request.amount = new BigDecimal("999999.99");

        ResponseEntity<ApiResponse> response = controller.addTransaction(request);
        
        assertNotNull(response);
    }

    @Test
    void testTransactionAddRequestFieldInitialization() {
        TransactionAddRequest request = new TransactionAddRequest();
        
        assertNull(request.accountId);
        assertNull(request.cardNumber);
        assertNull(request.transactionType);
        assertNull(request.amount);
    }

    @Test
    void testTransactionAddRequestFieldAssignment() {
        TransactionAddRequest request = new TransactionAddRequest();
        request.accountId = "12345678901";
        request.cardNumber = "4111111111111111";
        request.transactionType = "CR";
        request.categoryCode = 1001;
        request.source = "WEB";
        request.description = "Credit Transaction";
        request.amount = new BigDecimal("500.00");
        request.merchantId = 555555555L;
        request.merchantName = "Credit Store";
        request.merchantCity = "Miami";
        request.merchantZip = "33101";

        assertEquals("12345678901", request.accountId);
        assertEquals("4111111111111111", request.cardNumber);
        assertEquals("CR", request.transactionType);
        assertEquals(1001, request.categoryCode);
        assertEquals("WEB", request.source);
        assertEquals("Credit Transaction", request.description);
        assertEquals(new BigDecimal("500.00"), request.amount);
        assertEquals(555555555L, request.merchantId);
        assertEquals("Credit Store", request.merchantName);
        assertEquals("Miami", request.merchantCity);
        assertEquals("33101", request.merchantZip);
    }
}