// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:08:22
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import org.springframework.http.ResponseEntity;
import com.carddemo.controllers.TransactionListController;
import com.carddemo.controllers.TransactionListController.ApiResponse;
import com.carddemo.controllers.TransactionListController.TransactionListResponse;
import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

public class TransactionListControllerTest {

    private TransactionListController controller;

    @BeforeEach
    void setUp() {
        controller = new TransactionListController();
        controller.initSampleData();
    }

    @Test
    void testListTransactionsDefaultPage() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(1, null);
        
        assertNotNull(response);
        assertEquals(200, response.getStatusCode().value());
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        assertTrue(apiResponse.success);
        assertNull(apiResponse.errorMessage);
        assertNotNull(apiResponse.data);
        assertNotNull(apiResponse.commArea);
    }

    @Test
    void testListTransactionsReturnsTransactionData() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(1, null);
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        
        Map<String, Object> data = apiResponse.data;
        assertNotNull(data);
        assertTrue(data.containsKey("transactions"));
        assertTrue(data.containsKey("pageNum"));
        assertTrue(data.containsKey("hasNextPage"));
    }

    @Test
    void testListTransactionsWithStartTranId() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(1, "0000000000000005");
        
        assertNotNull(response);
        assertEquals(200, response.getStatusCode().value());
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        assertTrue(apiResponse.success);
    }

    @Test
    void testListTransactionsPage2() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(2, null);
        
        assertNotNull(response);
        assertEquals(200, response.getStatusCode().value());
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        assertTrue(apiResponse.success);
    }

    @Test
    void testListTransactionsContainsHeaderInfo() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(1, null);
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        
        Map<String, Object> data = apiResponse.data;
        assertNotNull(data);
        assertTrue(data.containsKey("firstTranId") || data.containsKey("lastTranId"));
    }

    @Test
    void testListTransactionsCommAreaPopulated() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(1, null);
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        assertNotNull(apiResponse.commArea);
        
        CardDemoCommArea commArea = apiResponse.commArea;
        assertEquals("CT00", commArea.cdemoFromTranid);
        assertEquals("COTRN00C", commArea.cdemoFromProgram);
    }

    @Test
    void testListTransactionsWithHighPageNumber() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(10, null);
        
        assertNotNull(response);
        assertEquals(200, response.getStatusCode().value());
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        assertTrue(apiResponse.success);
    }

    @Test
    void testInitSampleDataCreatesTransactions() {
        TransactionListController freshController = new TransactionListController();
        freshController.initSampleData();
        
        ResponseEntity<ApiResponse> response = freshController.listTransactions(1, null);
        
        assertNotNull(response);
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        assertTrue(apiResponse.success);
    }

    @Test
    void testListTransactionsWithNullStartTranId() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(1, null);
        
        assertNotNull(response);
        assertEquals(200, response.getStatusCode().value());
        assertTrue(response.getBody().success);
    }

    @Test
    void testListTransactionsWithEmptyStartTranId() {
        ResponseEntity<ApiResponse> response = controller.listTransactions(1, "");
        
        assertNotNull(response);
        assertEquals(200, response.getStatusCode().value());
    }
}