// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:09:01
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;

@RestController
@RequestMapping("/api/transactions")
public class TransactionViewController {

    private static final String WS_PGMNAME = "COTRN01C";
    private static final String WS_TRANID = "CT01";
    private static final String WS_TRANSACT_FILE = "TRANSACT";
    
    private static final String CCDA_MSG_INVALID_KEY = "Invalid key pressed. Please try again.";
    private static final String CCDA_TITLE01 = "AWS CardDemo Application";
    private static final String CCDA_TITLE02 = "View Transaction";

    private static Map<String, TransactionRecord> transactFile = new HashMap<>();

    @PostConstruct
    public void initializeSampleData() {
        TransactionRecord tran1 = new TransactionRecord();
        tran1.tranId = "0000000000000001";
        tran1.tranTypeCd = "PU";
        tran1.tranCatCd = 5001;
        tran1.tranSource = "ONLINE";
        tran1.tranDesc = "Online Purchase - Electronics";
        tran1.tranAmt = new BigDecimal("125.99");
        tran1.tranMerchantId = 123456789L;
        tran1.tranMerchantName = "Best Electronics";
        tran1.tranMerchantCity = "New York";
        tran1.tranMerchantZip = "10001";
        tran1.tranCardNum = "4111111111111111";
        tran1.tranOrigTs = "2024-01-15 10:30:00";
        tran1.tranProcTs = "2024-01-15 10:30:05";
        transactFile.put(tran1.tranId, tran1);

        TransactionRecord tran2 = new TransactionRecord();
        tran2.tranId = "0000000000000002";
        tran2.tranTypeCd = "SA";
        tran2.tranCatCd = 5411;
        tran2.tranSource = "POS";
        tran2.tranDesc = "Grocery Store Purchase";
        tran2.tranAmt = new BigDecimal("87.50");
        tran2.tranMerchantId = 987654321L;
        tran2.tranMerchantName = "Fresh Foods Market";
        tran2.tranMerchantCity = "Chicago";
        tran2.tranMerchantZip = "60601";
        tran2.tranCardNum = "4222222222222222";
        tran2.tranOrigTs = "2024-01-16 14:22:00";
        tran2.tranProcTs = "2024-01-16 14:22:03";
        transactFile.put(tran2.tranId, tran2);

        TransactionRecord tran3 = new TransactionRecord();
        tran3.tranId = "0000000000000003";
        tran3.tranTypeCd = "CR";
        tran3.tranCatCd = 5812;
        tran3.tranSource = "MOBILE";
        tran3.tranDesc = "Restaurant Payment";
        tran3.tranAmt = new BigDecimal("45.00");
        tran3.tranMerchantId = 555666777L;
        tran3.tranMerchantName = "Downtown Grill";
        tran3.tranMerchantCity = "Los Angeles";
        tran3.tranMerchantZip = "90001";
        tran3.tranCardNum = "4333333333333333";
        tran3.tranOrigTs = "2024-01-17 19:45:00";
        tran3.tranProcTs = "2024-01-17 19:45:02";
        transactFile.put(tran3.tranId, tran3);
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }

    public static class TransactionViewRequest {
        public String tranId;
        public String action;
        public CardDemoCommArea commArea;
    }

    public static class TransactionViewResponse {
        public String tranId;
        public String cardNum;
        public String tranTypeCd;
        public int tranCatCd;
        public String tranSource;
        public String tranAmt;
        public String tranDesc;
        public String tranOrigTs;
        public String tranProcTs;
        public String merchantId;
        public String merchantName;
        public String merchantCity;
        public String merchantZip;
        public String title01;
        public String title02;
        public String trnName;
        public String pgmName;
        public String curDate;
        public String curTime;
    }

    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse> viewTransaction(@PathVariable("id") String tranId) {
        if (tranId == null || tranId.trim().isEmpty()) {
            ApiResponse response = new ApiResponse(false, "Tran ID can NOT be empty...", null);
            return ResponseEntity.badRequest().body(response);
        }

        String paddedTranId = padTranId(tranId.trim());
        TransactionRecord tranRecord = readTransactFile(paddedTranId);

        if (tranRecord == null) {
            ApiResponse response = new ApiResponse(false, "Transaction ID NOT found...", null);
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(response);
        }

        TransactionViewResponse viewResponse = buildTransactionViewResponse(tranRecord);
        ApiResponse response = new ApiResponse(true, null, viewResponse);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/view")
    public ResponseEntity<ApiResponse> processTransactionView(@RequestBody TransactionViewRequest request) {
        CardDemoCommArea commArea = request.commArea;
        
        if (commArea == null) {
            commArea = new CardDemoCommArea();
            commArea.cdemoFromTranid = WS_TRANID;
            commArea.cdemoFromProgram = WS_PGMNAME;
        }

        String action = request.action;
        
        if ("back".equalsIgnoreCase(action) || "PF3".equalsIgnoreCase(action)) {
            return handleReturnToPrevScreen(commArea);
        }
        
        if ("clear".equalsIgnoreCase(action) || "PF4".equalsIgnoreCase(action)) {
            return handleClearScreen(commArea);
        }
        
        if ("list".equalsIgnoreCase(action) || "PF5".equalsIgnoreCase(action)) {
            ApiResponse response = new ApiResponse(true, null, null);
            response.redirect = "COTRN00C";
            response.commArea = commArea;
            commArea.cdemoToProgram = "COTRN00C";
            commArea.cdemoFromTranid = WS_TRANID;
            commArea.cdemoFromProgram = WS_PGMNAME;
            return ResponseEntity.ok(response);
        }

        return processEnterKey(request.tranId, commArea);
    }

    private ResponseEntity<ApiResponse> processEnterKey(String tranId, CardDemoCommArea commArea) {
        if (tranId == null || tranId.trim().isEmpty()) {
            ApiResponse response = new ApiResponse(false, "Tran ID can NOT be empty...", null);
            response.commArea = commArea;
            return ResponseEntity.badRequest().body(response);
        }

        String paddedTranId = padTranId(tranId.trim());
        TransactionRecord tranRecord = readTransactFile(paddedTranId);

        if (tranRecord == null) {
            ApiResponse response = new ApiResponse(false, "Transaction ID NOT found...", null);
            response.commArea = commArea;
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(response);
        }

        TransactionViewResponse viewResponse = buildTransactionViewResponse(tranRecord);
        ApiResponse response = new ApiResponse(true, null, viewResponse);
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private ResponseEntity<ApiResponse> handleReturnToPrevScreen(CardDemoCommArea commArea) {
        String toProgram = commArea.cdemoFromProgram;
        if (toProgram == null || toProgram.trim().isEmpty()) {
            toProgram = "COMEN01C";
        }
        
        commArea.cdemoToProgram = toProgram;
        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;
        commArea.cdemoPgmContext = 0;
        
        ApiResponse response = new ApiResponse(true, null, null);
        response.redirect = toProgram;
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private ResponseEntity<ApiResponse> handleClearScreen(CardDemoCommArea commArea) {
        TransactionViewResponse emptyResponse = new TransactionViewResponse();
        populateHeaderInfo(emptyResponse);
        emptyResponse.tranId = "";
        emptyResponse.cardNum = "";
        emptyResponse.tranTypeCd = "";
        emptyResponse.tranCatCd = 0;
        emptyResponse.tranSource = "";
        emptyResponse.tranAmt = "";
        emptyResponse.tranDesc = "";
        emptyResponse.tranOrigTs = "";
        emptyResponse.tranProcTs = "";
        emptyResponse.merchantId = "";
        emptyResponse.merchantName = "";
        emptyResponse.merchantCity = "";
        emptyResponse.merchantZip = "";
        
        ApiResponse response = new ApiResponse(true, null, emptyResponse);
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private TransactionRecord readTransactFile(String tranId) {
        return transactFile.get(tranId);
    }

    private TransactionViewResponse buildTransactionViewResponse(TransactionRecord tranRecord) {
        TransactionViewResponse viewResponse = new TransactionViewResponse();
        
        viewResponse.tranId = tranRecord.tranId;
        viewResponse.cardNum = tranRecord.tranCardNum;
        viewResponse.tranTypeCd = tranRecord.tranTypeCd;
        viewResponse.tranCatCd = tranRecord.tranCatCd;
        viewResponse.tranSource = tranRecord.tranSource;
        viewResponse.tranAmt = formatTranAmount(tranRecord.tranAmt);
        viewResponse.tranDesc = tranRecord.tranDesc;
        viewResponse.tranOrigTs = tranRecord.tranOrigTs;
        viewResponse.tranProcTs = tranRecord.tranProcTs;
        viewResponse.merchantId = String.valueOf(tranRecord.tranMerchantId);
        viewResponse.merchantName = tranRecord.tranMerchantName;
        viewResponse.merchantCity = tranRecord.tranMerchantCity;
        viewResponse.merchantZip = tranRecord.tranMerchantZip;
        
        populateHeaderInfo(viewResponse);
        
        return viewResponse;
    }

    private void populateHeaderInfo(TransactionViewResponse response) {
        LocalDateTime now = LocalDateTime.now();
        
        response.title01 = CCDA_TITLE01;
        response.title02 = CCDA_TITLE02;
        response.trnName = WS_TRANID;
        response.pgmName = WS_PGMNAME;
        response.curDate = now.format(DateTimeFormatter.ofPattern("MM/dd/yy"));
        response.curTime = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
    }

    private String formatTranAmount(BigDecimal amount) {
        if (amount == null) {
            return "+00000000.00";
        }
        String sign = amount.compareTo(BigDecimal.ZERO) >= 0 ? "+" : "";
        return String.format("%s%011.2f", sign, amount.abs());
    }

    private String padTranId(String tranId) {
        if (tranId == null) {
            return null;
        }
        if (tranId.length() >= 16) {
            return tranId.substring(0, 16);
        }
        return String.format("%016d", Long.parseLong(tranId));
    }
}