// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:08:10
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;
import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;

@RestController
@RequestMapping("/api/transactions")
public class TransactionListController {

    private static final String WS_PGMNAME = "COTRN00C";
    private static final String WS_TRANID = "CT00";
    private static final int PAGE_SIZE = 10;

    private static Map<String, TransactionRecord> transactFile = new LinkedHashMap<>();

    @PostConstruct
    public void initSampleData() {
        for (int i = 1; i <= 35; i++) {
            TransactionRecord tran = new TransactionRecord();
            tran.tranId = String.format("%016d", i);
            tran.tranTypeCd = (i % 2 == 0) ? "PU" : "SA";
            tran.tranCatCd = 5000 + (i % 10);
            tran.tranSource = "ONLINE";
            tran.tranDesc = "Transaction " + i;
            tran.tranAmt = new BigDecimal("100.00").add(new BigDecimal(i));
            tran.tranMerchantId = 100000000L + i;
            tran.tranMerchantName = "Merchant " + i;
            tran.tranMerchantCity = "City " + i;
            tran.tranMerchantZip = "1000" + (i % 10);
            tran.tranCardNum = "411111111111" + String.format("%04d", i);
            tran.tranOrigTs = "2024-01-" + String.format("%02d", (i % 28) + 1) + " 10:30:00";
            tran.tranProcTs = "2024-01-" + String.format("%02d", (i % 28) + 1) + " 10:31:00";
            transactFile.put(tran.tranId, tran);
        }
    }

    @GetMapping
    public ResponseEntity<ApiResponse> listTransactions(
            @RequestParam(value = "page", defaultValue = "1") int page,
            @RequestParam(value = "startTranId", required = false) String startTranId) {

        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;

        TransactionListResponse response = processPageForward(startTranId, page);
        
        Map<String, Object> data = new HashMap<>();
        data.put("transactions", response.transactions);
        data.put("pageNum", response.pageNum);
        data.put("hasNextPage", response.hasNextPage);
        data.put("firstTranId", response.firstTranId);
        data.put("lastTranId", response.lastTranId);
        data.putAll(populateHeaderInfo());

        ApiResponse apiResponse = new ApiResponse(true, null, data);
        apiResponse.commArea = commArea;

        return ResponseEntity.ok(apiResponse);
    }

    @GetMapping("/page/forward")
    public ResponseEntity<ApiResponse> pageForward(
            @RequestParam(value = "lastTranId", required = false) String lastTranId,
            @RequestParam(value = "currentPage", defaultValue = "0") int currentPage) {

        if (lastTranId == null || lastTranId.trim().isEmpty()) {
            lastTranId = null;
        }

        TransactionListResponse response = processPageForward(lastTranId, currentPage);

        if (response.transactions.isEmpty() && currentPage > 0) {
            ApiResponse apiResponse = new ApiResponse(false, "You are already at the bottom of the page...", null);
            return ResponseEntity.ok(apiResponse);
        }

        Map<String, Object> data = new HashMap<>();
        data.put("transactions", response.transactions);
        data.put("pageNum", response.pageNum);
        data.put("hasNextPage", response.hasNextPage);
        data.put("firstTranId", response.firstTranId);
        data.put("lastTranId", response.lastTranId);
        data.putAll(populateHeaderInfo());

        ApiResponse apiResponse = new ApiResponse(true, null, data);
        return ResponseEntity.ok(apiResponse);
    }

    @GetMapping("/page/backward")
    public ResponseEntity<ApiResponse> pageBackward(
            @RequestParam(value = "firstTranId", required = false) String firstTranId,
            @RequestParam(value = "currentPage", defaultValue = "1") int currentPage) {

        if (currentPage <= 1) {
            ApiResponse apiResponse = new ApiResponse(false, "You are already at the top of the page...", null);
            return ResponseEntity.ok(apiResponse);
        }

        TransactionListResponse response = processPageBackward(firstTranId, currentPage);

        Map<String, Object> data = new HashMap<>();
        data.put("transactions", response.transactions);
        data.put("pageNum", response.pageNum);
        data.put("hasNextPage", response.hasNextPage);
        data.put("firstTranId", response.firstTranId);
        data.put("lastTranId", response.lastTranId);
        data.putAll(populateHeaderInfo());

        ApiResponse apiResponse = new ApiResponse(true, null, data);
        return ResponseEntity.ok(apiResponse);
    }

    @PostMapping("/select")
    public ResponseEntity<ApiResponse> selectTransaction(@RequestBody TransactionSelectRequest request) {

        if (request.selection == null || request.selection.trim().isEmpty()) {
            ApiResponse apiResponse = new ApiResponse(false, "No selection made", null);
            return ResponseEntity.badRequest().body(apiResponse);
        }

        String selFlag = request.selection.toUpperCase();
        if (!selFlag.equals("S")) {
            ApiResponse apiResponse = new ApiResponse(false, "Invalid selection. Valid value is S", null);
            return ResponseEntity.badRequest().body(apiResponse);
        }

        if (request.tranId == null || request.tranId.trim().isEmpty()) {
            ApiResponse apiResponse = new ApiResponse(false, "No transaction ID selected", null);
            return ResponseEntity.badRequest().body(apiResponse);
        }

        CardDemoCommArea commArea = request.commArea != null ? request.commArea : new CardDemoCommArea();
        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;
        commArea.cdemoToProgram = "COTRN01C";
        commArea.cdemoPgmContext = 0;

        ApiResponse apiResponse = new ApiResponse(true, null, null);
        apiResponse.redirect = "/api/transactions/" + request.tranId;
        apiResponse.commArea = commArea;

        return ResponseEntity.ok(apiResponse);
    }

    @PostMapping("/search")
    public ResponseEntity<ApiResponse> searchTransactions(@RequestBody TransactionSearchRequest request) {

        if (request.tranIdInput != null && !request.tranIdInput.trim().isEmpty()) {
            String tranIdInput = request.tranIdInput.trim();
            
            try {
                Long.parseLong(tranIdInput);
            } catch (NumberFormatException e) {
                ApiResponse apiResponse = new ApiResponse(false, "Tran ID must be Numeric ...", null);
                return ResponseEntity.badRequest().body(apiResponse);
            }

            String paddedTranId = String.format("%016d", Long.parseLong(tranIdInput));
            TransactionListResponse response = processPageForward(paddedTranId, 0);

            Map<String, Object> data = new HashMap<>();
            data.put("transactions", response.transactions);
            data.put("pageNum", response.pageNum);
            data.put("hasNextPage", response.hasNextPage);
            data.put("firstTranId", response.firstTranId);
            data.put("lastTranId", response.lastTranId);
            data.putAll(populateHeaderInfo());

            ApiResponse apiResponse = new ApiResponse(true, null, data);
            return ResponseEntity.ok(apiResponse);
        }

        return listTransactions(1, null);
    }

    private TransactionListResponse processPageForward(String startTranId, int currentPage) {
        TransactionListResponse response = new TransactionListResponse();
        response.transactions = new ArrayList<>();
        response.pageNum = currentPage;

        List<TransactionRecord> allTransactions = new ArrayList<>(transactFile.values());
        
        allTransactions.sort((a, b) -> a.tranId.compareTo(b.tranId));

        int startIndex = 0;
        if (startTranId != null && !startTranId.trim().isEmpty()) {
            for (int i = 0; i < allTransactions.size(); i++) {
                if (allTransactions.get(i).tranId.compareTo(startTranId) > 0) {
                    startIndex = i;
                    break;
                }
                if (allTransactions.get(i).tranId.equals(startTranId)) {
                    startIndex = i + 1;
                    break;
                }
            }
        }

        int count = 0;
        for (int i = startIndex; i < allTransactions.size() && count < PAGE_SIZE; i++) {
            TransactionRecord tran = allTransactions.get(i);
            TransactionListItem item = convertToListItem(tran);
            response.transactions.add(item);

            if (count == 0) {
                response.firstTranId = tran.tranId;
            }
            response.lastTranId = tran.tranId;
            count++;
        }

        if (!response.transactions.isEmpty()) {
            response.pageNum = currentPage + 1;
        }

        int nextIndex = startIndex + count;
        response.hasNextPage = nextIndex < allTransactions.size();

        return response;
    }

    private TransactionListResponse processPageBackward(String firstTranId, int currentPage) {
        TransactionListResponse response = new TransactionListResponse();
        response.transactions = new ArrayList<>();

        List<TransactionRecord> allTransactions = new ArrayList<>(transactFile.values());
        allTransactions.sort((a, b) -> a.tranId.compareTo(b.tranId));

        int endIndex = allTransactions.size() - 1;
        if (firstTranId != null && !firstTranId.trim().isEmpty()) {
            for (int i = allTransactions.size() - 1; i >= 0; i--) {
                if (allTransactions.get(i).tranId.compareTo(firstTranId) < 0) {
                    endIndex = i;
                    break;
                }
            }
        }

        int startIndex = Math.max(0, endIndex - PAGE_SIZE + 1);
        
        for (int i = startIndex; i <= endIndex && i < allTransactions.size(); i++) {
            TransactionRecord tran = allTransactions.get(i);
            TransactionListItem item = convertToListItem(tran);
            response.transactions.add(item);
        }

        if (!response.transactions.isEmpty()) {
            response.firstTranId = response.transactions.get(0).tranId;
            response.lastTranId = response.transactions.get(response.transactions.size() - 1).tranId;
        }

        response.pageNum = currentPage - 1;
        if (response.pageNum < 1) {
            response.pageNum = 1;
        }

        response.hasNextPage = true;

        return response;
    }

    private TransactionListItem convertToListItem(TransactionRecord tran) {
        TransactionListItem item = new TransactionListItem();
        item.tranId = tran.tranId;
        item.tranDate = formatTranDate(tran.tranOrigTs);
        item.tranDesc = tran.tranDesc;
        item.tranAmt = tran.tranAmt != null ? tran.tranAmt.toString() : "0.00";
        return item;
    }

    private String formatTranDate(String origTs) {
        if (origTs == null || origTs.length() < 10) {
            return "00/00/00";
        }
        try {
            String year = origTs.substring(2, 4);
            String month = origTs.substring(5, 7);
            String day = origTs.substring(8, 10);
            return month + "/" + day + "/" + year;
        } catch (Exception e) {
            return "00/00/00";
        }
    }

    private Map<String, Object> populateHeaderInfo() {
        Map<String, Object> headerInfo = new HashMap<>();
        
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MM/dd/yy");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

        headerInfo.put("title01", "CardDemo Application");
        headerInfo.put("title02", "Transaction List");
        headerInfo.put("tranName", WS_TRANID);
        headerInfo.put("programName", WS_PGMNAME);
        headerInfo.put("currentDate", now.format(dateFormatter));
        headerInfo.put("currentTime", now.format(timeFormatter));

        return headerInfo;
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }

    public static class TransactionListResponse {
        public List<TransactionListItem> transactions;
        public int pageNum;
        public boolean hasNextPage;
        public String firstTranId;
        public String lastTranId;
    }

    public static class TransactionListItem {
        public String tranId;
        public String tranDate;
        public String tranDesc;
        public String tranAmt;
    }

    public static class TransactionSelectRequest {
        public String selection;
        public String tranId;
        public CardDemoCommArea commArea;
    }

    public static class TransactionSearchRequest {
        public String tranIdInput;
        public CardDemoCommArea commArea;
    }
}