package com.carddemo.controllers;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:07:29
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;
import com.carddemo.controllers.AuthController;
import com.carddemo.controllers.AuthController.LoginRequest;
import com.carddemo.controllers.AuthController.ApiResponse;
import com.carddemo.controllers.AuthController.SignonScreenData;
import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.UserSecurityData;

import static org.junit.jupiter.api.Assertions.*;

class AuthControllerTest {

    private AuthController controller;

    @BeforeEach
    void setUp() {
        controller = new AuthController();
        controller.initializeData();
    }

    @Test
    void testGetLoginScreen_ReturnsSuccessResponse() {
        ResponseEntity<ApiResponse> response = controller.getLoginScreen();
        
        assertNotNull(response);
        assertEquals(HttpStatus.OK, response.getStatusCode());
        
        ApiResponse apiResponse = response.getBody();
        assertNotNull(apiResponse);
        assertTrue(apiResponse.success);
    }

    @Test
    void testApiResponse_ConstructorSetsFields() {
        ApiResponse response = new ApiResponse(true, "Test message", "testData");
        
        assertTrue(response.success);
        assertEquals("Test message", response.message);
        assertEquals("testData", response.data);
    }

    @Test
    void testApiResponse_FieldsCanBeSet() {
        ApiResponse response = new ApiResponse(false, "Initial", null);
        response.redirect = "/redirect/path";
        response.commArea = new CardDemoCommArea();
        
        assertEquals("/redirect/path", response.redirect);
        assertNotNull(response.commArea);
    }

    @Test
    void testLoginRequest_FieldsInitialization() {
        LoginRequest request = new LoginRequest();
        
        assertNull(request.userId);
        assertNull(request.password);
        assertNull(request.action);
        assertNull(request.commArea);
    }

    @Test
    void testLoginRequest_FieldsAssignment() {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001";
        request.password = "ADMIN123";
        request.action = "LOGIN";
        request.commArea = new CardDemoCommArea();
        
        assertEquals("ADMIN001", request.userId);
        assertEquals("ADMIN123", request.password);
        assertEquals("LOGIN", request.action);
        assertNotNull(request.commArea);
    }

    @Test
    void testSignonScreenData_DefaultValues() {
        SignonScreenData screenData = new SignonScreenData();
        
        assertEquals("CARDDEMO", screenData.applId);
        assertEquals("SYS1", screenData.sysId);
        assertNull(screenData.title01);
        assertNull(screenData.title02);
        assertNull(screenData.errorMessage);
    }

    @Test
    void testSignonScreenData_FieldsAssignment() {
        SignonScreenData screenData = new SignonScreenData();
        screenData.title01 = "CardDemo System";
        screenData.title02 = "Sign On";
        screenData.tranName = "CC00";
        screenData.pgmName = "COSGN00C";
        screenData.curDate = "2024-01-15";
        screenData.curTime = "10:30:00";
        screenData.errorMessage = "";
        
        assertEquals("CardDemo System", screenData.title01);
        assertEquals("Sign On", screenData.title02);
        assertEquals("CC00", screenData.tranName);
        assertEquals("COSGN00C", screenData.pgmName);
        assertEquals("2024-01-15", screenData.curDate);
        assertEquals("10:30:00", screenData.curTime);
        assertEquals("", screenData.errorMessage);
    }

    @Test
    void testInitializeData_CreatesAdminUser() {
        AuthController newController = new AuthController();
        newController.initializeData();
        
        ResponseEntity<ApiResponse> response = newController.getLoginScreen();
        assertNotNull(response);
        assertTrue(response.getBody().success);
    }

    @Test
    void testCardDemoCommArea_Integration() {
        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoUserId = "ADMIN001";
        
        LoginRequest request = new LoginRequest();
        request.commArea = commArea;
        
        assertEquals("ADMIN001", request.commArea.cdemoUserId);
    }

    @Test
    void testUserSecurityData_FieldsAssignment() {
        UserSecurityData userData = new UserSecurityData();
        userData.secUsrId = "TEST001";
        userData.secUsrFname = "TEST";
        userData.secUsrLname = "USER";
        userData.secUsrPwd = "PASSWORD";
        userData.secUsrType = "U";
        
        assertEquals("TEST001", userData.secUsrId);
        assertEquals("TEST", userData.secUsrFname);
        assertEquals("USER", userData.secUsrLname);
        assertEquals("PASSWORD", userData.secUsrPwd);
        assertEquals("U", userData.secUsrType);
    }
}