package com.carddemo.controllers;
import com.carddemo.controllers.AuthController;
import com.carddemo.controllers.AuthController.LoginRequest;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:02:19
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.ObjectMapper;

@WebMvcTest(AuthController.class)
class AuthControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void getSignonScreen_shouldReturnOkWithScreenData() throws Exception {
        mockMvc.perform(get("/api/auth/screen"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.message").value("Signon screen ready"))
                .andExpect(jsonPath("$.data.userId").value(""))
                .andExpect(jsonPath("$.data.password").value(""))
                .andExpect(jsonPath("$.data.errorMessage").value(""));
    }

    @Test
    void login_withValidAdminCredentials_shouldReturnOk() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001";
        request.password = "ADMIN123";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());
    }

    @Test
    void login_withValidUserCredentials_shouldReturnOk() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "USER0001";
        request.password = "USER1234";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());
    }

    @Test
    void login_withEmptyUserId_shouldReturnBadRequest() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "";
        request.password = "password123";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.message").value("Please enter User ID ..."));
    }

    @Test
    void login_withNullUserId_shouldReturnBadRequest() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = null;
        request.password = "password123";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.message").value("Please enter User ID ..."));
    }

    @Test
    void login_withEmptyPassword_shouldReturnBadRequest() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001";
        request.password = "";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.message").value("Please enter Password ..."));
    }

    @Test
    void login_withNullPassword_shouldReturnBadRequest() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001";
        request.password = null;

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.message").value("Please enter Password ..."));
    }

    @Test
    void login_withWhitespaceUserId_shouldReturnBadRequest() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "   ";
        request.password = "password123";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.message").value("Please enter User ID ..."));
    }

    @Test
    void login_withWhitespacePassword_shouldReturnBadRequest() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001";
        request.password = "   ";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.message").value("Please enter Password ..."));
    }

    @Test
    void login_withLowercaseCredentials_shouldNormalizeAndReturnOk() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "admin001";
        request.password = "admin123";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());
    }

    @Test
    void login_withLongUserId_shouldTruncateAndProcess() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001EXTRACHARACTERS";
        request.password = "ADMIN123";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());
    }

    @Test
    void login_withLongPassword_shouldTruncateAndProcess() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001";
        request.password = "ADMIN123EXTRACHARACTERS";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());
    }

    @Test
    void logout_shouldReturnOk() throws Exception {
        mockMvc.perform(post("/api/auth/logout"))
                .andExpect(status().isOk());
    }

    @Test
    void login_withInvalidUserId_shouldReturnNotFound() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "INVALID1";
        request.password = "PASSWORD";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isNotFound());
    }

    @Test
    void login_withWrongPassword_shouldReturnUnauthorized() throws Exception {
        LoginRequest request = new LoginRequest();
        request.userId = "ADMIN001";
        request.password = "WRONGPWD";

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isUnauthorized());
    }
}