package com.carddemo.controllers;
import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.controllers.MenuController;
import com.carddemo.controllers.MenuController.MenuOption;
import com.carddemo.controllers.AuthController.ApiResponse;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:01:37
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import org.springframework.http.*;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

class MenuControllerTest {

    private MenuController menuController;

    @BeforeEach
    void setUp() {
        menuController = new MenuController();
        menuController.init();
    }

    @Test
    void getMenu_withValidSession_returnsSuccess() {
        String sessionData = "valid-session-data";
        
        ResponseEntity<MenuController.ApiResponse> response = menuController.getMenu(sessionData);
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertTrue(response.getBody().success);
    }

    @Test
    void getMenu_withNullSession_returnsUnauthorized() {
        ResponseEntity<MenuController.ApiResponse> response = menuController.getMenu(null);
        
        assertEquals(HttpStatus.UNAUTHORIZED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertFalse(response.getBody().success);
        assertEquals("Session required", response.getBody().message);
        assertEquals("COSGN00C", response.getBody().redirect);
    }

    @Test
    void getMenu_withEmptySession_returnsUnauthorized() {
        ResponseEntity<MenuController.ApiResponse> response = menuController.getMenu("");
        
        assertEquals(HttpStatus.UNAUTHORIZED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertFalse(response.getBody().success);
        assertEquals("Session required", response.getBody().message);
    }

    @Test
    void menuOption_constructorSetsFieldsCorrectly() {
        MenuController.MenuOption option = new MenuController.MenuOption(1, "View Account", "COACTVWC", "U");
        
        assertEquals(1, option.optionNum);
        assertEquals("View Account", option.optionName);
        assertEquals("COACTVWC", option.programName);
        assertEquals("U", option.userType);
    }

    @Test
    void menuRequest_fieldsCanBeAssignedAndRetrieved() {
        MenuController.MenuRequest request = new MenuController.MenuRequest();
        request.option = 5;
        request.action = "select";
        request.commArea = new CardDemoCommArea();
        
        assertEquals(5, request.option);
        assertEquals("select", request.action);
        assertNotNull(request.commArea);
    }

    @Test
    void menuResponse_fieldsCanBeAssignedAndRetrieved() {
        MenuController.MenuResponse response = new MenuController.MenuResponse();
        response.title01 = "Main Menu";
        response.title02 = "Subtitle";
        response.transactionName = "CM00";
        response.programName = "COMEN01C";
        response.currentDate = "2024-01-15";
        response.currentTime = "10:30:00";
        response.menuOptionTexts = Arrays.asList("Option 1", "Option 2");
        response.errorMessage = null;
        
        assertEquals("Main Menu", response.title01);
        assertEquals("Subtitle", response.title02);
        assertEquals("CM00", response.transactionName);
        assertEquals("COMEN01C", response.programName);
        assertEquals("2024-01-15", response.currentDate);
        assertEquals("10:30:00", response.currentTime);
        assertEquals(2, response.menuOptionTexts.size());
        assertNull(response.errorMessage);
    }

    @Test
    void apiResponse_constructorSetsFieldsCorrectly() {
        Object testData = new HashMap<String, String>();
        MenuController.ApiResponse response = new MenuController.ApiResponse(true, "Success", testData);
        
        assertTrue(response.success);
        assertEquals("Success", response.message);
        assertSame(testData, response.data);
    }

    @Test
    void apiResponse_fieldsCanBeModified() {
        MenuController.ApiResponse response = new MenuController.ApiResponse(false, null, null);
        response.redirect = "COSGN00C";
        response.commArea = new CardDemoCommArea();
        
        assertEquals("COSGN00C", response.redirect);
        assertNotNull(response.commArea);
    }

    @Test
    void init_populatesMenuOptionsWithSixItems() {
        MenuController controller = new MenuController();
        controller.init();
        
        ResponseEntity<MenuController.ApiResponse> response = controller.getMenu("valid-session");
        
        assertEquals(HttpStatus.OK, response.getStatusCode());
    }

    @Test
    void menuOption_defaultValuesBeforeConstruction() {
        MenuController.MenuOption option = new MenuController.MenuOption(0, "", "", "");
        
        assertEquals(0, option.optionNum);
        assertEquals("", option.optionName);
        assertEquals("", option.programName);
        assertEquals("", option.userType);
    }
}
