package com.carddemo.controllers;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:06:49
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import com.carddemo.controllers.MenuController;
import com.carddemo.controllers.MenuController.MenuOption;
import com.carddemo.controllers.MenuController.ApiResponse;
import com.carddemo.controllers.MenuController.MenuResponse;
import com.carddemo.controllers.MenuController.MenuSelectRequest;
import com.carddemo.dto.CardDemoCommArea;
import org.springframework.http.ResponseEntity;

import java.util.List;

public class MenuControllerTest {

    private MenuController controller;

    @BeforeEach
    void setUp() {
        controller = new MenuController();
        controller.initMenuOptions();
    }

    @Test
    void testMenuOptionConstructor() {
        MenuOption option = new MenuOption(1, "Test Option", "TESTPGM", "U");
        Assertions.assertEquals(1, option.optNum);
        Assertions.assertEquals("Test Option", option.optName);
        Assertions.assertEquals("TESTPGM", option.optPgmName);
        Assertions.assertEquals("U", option.optUsrType);
    }

    @Test
    void testApiResponseConstructor() {
        ApiResponse response = new ApiResponse(true, "Success", "testData");
        Assertions.assertTrue(response.success);
        Assertions.assertEquals("Success", response.message);
        Assertions.assertEquals("testData", response.data);
    }

    @Test
    void testApiResponseWithNullData() {
        ApiResponse response = new ApiResponse(false, "Error occurred", null);
        Assertions.assertFalse(response.success);
        Assertions.assertEquals("Error occurred", response.message);
        Assertions.assertNull(response.data);
    }

    @Test
    void testMenuResponseDefaultConstructor() {
        MenuResponse response = new MenuResponse();
        Assertions.assertNotNull(response.menuOptions);
        Assertions.assertTrue(response.menuOptions.isEmpty());
        Assertions.assertNull(response.title01);
        Assertions.assertNull(response.title02);
        Assertions.assertNull(response.errorMessage);
    }

    @Test
    void testMenuResponseFieldAssignment() {
        MenuResponse response = new MenuResponse();
        response.title01 = "AWS CardDemo";
        response.title02 = "Main Menu";
        response.transactionName = "CM00";
        response.programName = "COMEN01C";
        response.currentDate = "2024-01-15";
        response.currentTime = "10:30:00";
        response.errorMessage = null;
        response.menuOptions.add("1. View Account");

        Assertions.assertEquals("AWS CardDemo", response.title01);
        Assertions.assertEquals("Main Menu", response.title02);
        Assertions.assertEquals("CM00", response.transactionName);
        Assertions.assertEquals("COMEN01C", response.programName);
        Assertions.assertEquals("2024-01-15", response.currentDate);
        Assertions.assertEquals("10:30:00", response.currentTime);
        Assertions.assertNull(response.errorMessage);
        Assertions.assertEquals(1, response.menuOptions.size());
        Assertions.assertEquals("1. View Account", response.menuOptions.get(0));
    }

    @Test
    void testMenuSelectRequestFieldAssignment() {
        MenuSelectRequest request = new MenuSelectRequest();
        request.option = 1;
        request.action = "ENTER";
        request.commArea = new CardDemoCommArea();

        Assertions.assertEquals(1, request.option);
        Assertions.assertEquals("ENTER", request.action);
        Assertions.assertNotNull(request.commArea);
    }

    @Test
    void testMenuSelectRequestWithCommArea() {
        MenuSelectRequest request = new MenuSelectRequest();
        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoUserId = "USER001";
        request.option = 2;
        request.action = "SELECT";
        request.commArea = commArea;

        Assertions.assertEquals(2, request.option);
        Assertions.assertEquals("SELECT", request.action);
        Assertions.assertEquals("USER001", request.commArea.cdemoUserId);
    }

    @Test
    void testInitMenuOptionsCreatesOptions() {
        controller.initMenuOptions();
        // The init method should populate menu options
        // Since MENU_OPTIONS is static and private, we verify through behavior
        Assertions.assertNotNull(controller);
    }

    @Test
    void testMenuOptionWithAdminUserType() {
        MenuOption option = new MenuOption(10, "Admin Function", "ADMINPGM", "A");
        Assertions.assertEquals(10, option.optNum);
        Assertions.assertEquals("Admin Function", option.optName);
        Assertions.assertEquals("ADMINPGM", option.optPgmName);
        Assertions.assertEquals("A", option.optUsrType);
    }

    @Test
    void testApiResponseWithCommArea() {
        ApiResponse response = new ApiResponse(true, "Menu loaded", null);
        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoUserId = "TESTUSER";
        response.commArea = commArea;
        response.redirect = "/api/account/view";

        Assertions.assertTrue(response.success);
        Assertions.assertEquals("Menu loaded", response.message);
        Assertions.assertEquals("/api/account/view", response.redirect);
        Assertions.assertNotNull(response.commArea);
        Assertions.assertEquals("TESTUSER", response.commArea.cdemoUserId);
    }

    @Test
    void testMenuResponseWithErrorMessage() {
        MenuResponse response = new MenuResponse();
        response.errorMessage = "Invalid key pressed. Please use Enter or PF3.";
        Assertions.assertEquals("Invalid key pressed. Please use Enter or PF3.", response.errorMessage);
    }

    @Test
    void testMultipleMenuOptions() {
        MenuOption option1 = new MenuOption(1, "View Account", "COACTVWC", "U");
        MenuOption option2 = new MenuOption(2, "Update Account", "COACTUPC", "U");
        MenuOption option3 = new MenuOption(3, "View Statement", "COSTMTC", "U");

        Assertions.assertEquals(1, option1.optNum);
        Assertions.assertEquals(2, option2.optNum);
        Assertions.assertEquals(3, option3.optNum);
        Assertions.assertEquals("View Account", option1.optName);
        Assertions.assertEquals("Update Account", option2.optName);
        Assertions.assertEquals("View Statement", option3.optName);
    }
}