package com.carddemo.controllers;
import com.carddemo.controllers.TransactionAddController;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:05:13
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(TransactionAddController.class)
class TransactionAddControllerTest {

    private MockMvc mockMvc;
    private TransactionAddController controller;

    @BeforeEach
    void setUp() {
        controller = new TransactionAddController();
        controller.initializeData();
        mockMvc = MockMvcBuilders.standaloneSetup(controller).build();
    }

    @Test
    void testAddTransaction_WithValidAccountId_Returns200() throws Exception {
        String requestJson = "{\"accountId\":\"80000001001\",\"cardNumber\":\"\",\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"POS\",\"tranDesc\":\"Test Purchase\",\"tranAmt\":100.00,\"tranMerchantId\":12345678901,\"tranMerchantName\":\"Test Store\",\"tranMerchantCity\":\"Boston\",\"tranMerchantZip\":\"02101\"}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk());
    }

    @Test
    void testAddTransaction_WithValidCardNumber_Returns200() throws Exception {
        String requestJson = "{\"accountId\":\"\",\"cardNumber\":\"4111111111111111\",\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"ONLINE\",\"tranDesc\":\"Online Purchase\",\"tranAmt\":50.00,\"tranMerchantId\":98765432109,\"tranMerchantName\":\"Online Shop\",\"tranMerchantCity\":\"Seattle\",\"tranMerchantZip\":\"98101\"}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk());
    }

    @Test
    void testAddTransaction_WithBothAccountIdAndCardNumberEmpty_Returns400() throws Exception {
        String requestJson = "{\"accountId\":\"\",\"cardNumber\":\"\",\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"POS\",\"tranDesc\":\"Test\",\"tranAmt\":100.00}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isBadRequest());
    }

    @Test
    void testAddTransaction_WithNullAccountIdAndCardNumber_Returns400() throws Exception {
        String requestJson = "{\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"POS\",\"tranDesc\":\"Test\",\"tranAmt\":100.00}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isBadRequest());
    }

    @Test
    void testAddTransaction_WithInvalidAccountId_Returns404() throws Exception {
        String requestJson = "{\"accountId\":\"99999999999\",\"cardNumber\":\"\",\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"POS\",\"tranDesc\":\"Test\",\"tranAmt\":100.00,\"tranMerchantId\":12345678901,\"tranMerchantName\":\"Store\",\"tranMerchantCity\":\"City\",\"tranMerchantZip\":\"12345\"}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isNotFound());
    }

    @Test
    void testAddTransaction_WithInvalidCardNumber_Returns404() throws Exception {
        String requestJson = "{\"accountId\":\"\",\"cardNumber\":\"0000000000000000\",\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"POS\",\"tranDesc\":\"Test\",\"tranAmt\":100.00,\"tranMerchantId\":12345678901,\"tranMerchantName\":\"Store\",\"tranMerchantCity\":\"City\",\"tranMerchantZip\":\"12345\"}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isNotFound());
    }

    @Test
    void testAddTransaction_WithSecondValidCardNumber_Returns200() throws Exception {
        String requestJson = "{\"accountId\":\"\",\"cardNumber\":\"5500000000000004\",\"tranTypeCd\":\"02\",\"tranCatCd\":5002,\"tranSource\":\"ONLINE\",\"tranDesc\":\"Payment\",\"tranAmt\":75.00,\"tranMerchantId\":11111111111,\"tranMerchantName\":\"Merchant\",\"tranMerchantCity\":\"Miami\",\"tranMerchantZip\":\"33101\"}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk());
    }

    @Test
    void testAddTransaction_WithSecondValidAccountId_Returns200() throws Exception {
        String requestJson = "{\"accountId\":\"80000002002\",\"cardNumber\":\"\",\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"ATM\",\"tranDesc\":\"Withdrawal\",\"tranAmt\":200.00,\"tranMerchantId\":22222222222,\"tranMerchantName\":\"Bank ATM\",\"tranMerchantCity\":\"Denver\",\"tranMerchantZip\":\"80201\"}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isOk());
    }

    @Test
    void testAddTransaction_WithWhitespaceOnlyAccountIdAndCardNumber_Returns400() throws Exception {
        String requestJson = "{\"accountId\":\"   \",\"cardNumber\":\"   \",\"tranTypeCd\":\"01\",\"tranCatCd\":5001,\"tranSource\":\"POS\",\"tranDesc\":\"Test\",\"tranAmt\":100.00}";
        
        mockMvc.perform(post("/api/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(requestJson))
                .andExpect(status().isBadRequest());
    }

    @Test
    void testInitializeData_CreatesTransactionRecords() {
        TransactionAddController newController = new TransactionAddController();
        newController.initializeData();
        Assertions.assertNotNull(newController);
    }
}