package com.carddemo.controllers;
import com.carddemo.controllers.TransactionViewController;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:03:58
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import java.math.BigDecimal;

class TransactionViewControllerTest {

    private MockMvc mockMvc;
    private TransactionViewController controller;

    @BeforeEach
    void setUp() {
        controller = new TransactionViewController();
        controller.initializeData();
        mockMvc = MockMvcBuilders.standaloneSetup(controller).build();
    }

    @Test
    void viewTransaction_WithValidId_ReturnsSuccess() throws Exception {
        mockMvc.perform(get("/api/transactions/0000000000000001")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    @Test
    void viewTransaction_WithSecondValidId_ReturnsSuccess() throws Exception {
        mockMvc.perform(get("/api/transactions/0000000000000002")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    @Test
    void viewTransaction_WithThirdValidId_ReturnsSuccess() throws Exception {
        mockMvc.perform(get("/api/transactions/0000000000000003")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    @Test
    void viewTransaction_WithInvalidId_ReturnsNotFound() throws Exception {
        mockMvc.perform(get("/api/transactions/9999999999999999")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isNotFound());
    }

    @Test
    void viewTransaction_WithEmptyId_ReturnsNotFound() throws Exception {
        mockMvc.perform(get("/api/transactions/")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isNotFound());
    }

    @Test
    void viewTransaction_WithCommAreaHeader_ReturnsSuccess() throws Exception {
        mockMvc.perform(get("/api/transactions/0000000000000001")
                .header("X-CommArea", "test-comm-area")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    @Test
    void viewTransaction_WithoutCommAreaHeader_ReturnsSuccess() throws Exception {
        mockMvc.perform(get("/api/transactions/0000000000000001")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    @Test
    void initializeData_CreatesThreeTransactions() {
        TransactionViewController newController = new TransactionViewController();
        newController.initializeData();
        Assertions.assertNotNull(newController);
    }

    @Test
    void viewTransaction_WithNonExistentTransaction_ReturnsNotFound() throws Exception {
        mockMvc.perform(get("/api/transactions/INVALID_ID_12345")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isNotFound());
    }

    @Test
    void viewTransaction_WithSpecialCharactersInId_HandlesGracefully() throws Exception {
        mockMvc.perform(get("/api/transactions/test-id-with-dashes")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isNotFound());
    }
}