package com.carddemo.controllers;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:09:20
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.http.*;
import java.math.BigDecimal;

import com.carddemo.controllers.TransactionViewController;
import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;

class TransactionViewControllerTest {

    private TransactionViewController controller;

    @BeforeEach
    void setUp() {
        controller = new TransactionViewController();
        controller.initializeSampleData();
    }

    @Test
    void testControllerInstantiation() {
        assertNotNull(controller);
    }

    @Test
    void testInitializeSampleDataCreatesTransactions() {
        // The initializeSampleData method is called in setUp
        // This test verifies the controller initializes without error
        assertDoesNotThrow(() -> controller.initializeSampleData());
    }

    @Test
    void testTransactionRecordFieldAssignment() {
        TransactionRecord record = new TransactionRecord();
        record.tranId = "TEST123";
        record.tranTypeCd = "PU";
        record.tranCatCd = 5001;
        record.tranSource = "ONLINE";
        record.tranDesc = "Test Description";
        record.tranAmt = new BigDecimal("100.50");
        record.tranMerchantId = 123456L;
        record.tranMerchantName = "Test Merchant";
        record.tranMerchantCity = "Test City";
        record.tranMerchantZip = "12345";
        record.tranCardNum = "4111111111111111";
        record.tranOrigTs = "2024-01-15 10:30:00";
        record.tranProcTs = "2024-01-15 10:30:05";

        assertEquals("TEST123", record.tranId);
        assertEquals("PU", record.tranTypeCd);
        assertEquals(5001, record.tranCatCd);
        assertEquals("ONLINE", record.tranSource);
        assertEquals("Test Description", record.tranDesc);
        assertEquals(new BigDecimal("100.50"), record.tranAmt);
        assertEquals(123456L, record.tranMerchantId);
        assertEquals("Test Merchant", record.tranMerchantName);
        assertEquals("Test City", record.tranMerchantCity);
        assertEquals("12345", record.tranMerchantZip);
        assertEquals("4111111111111111", record.tranCardNum);
        assertEquals("2024-01-15 10:30:00", record.tranOrigTs);
        assertEquals("2024-01-15 10:30:05", record.tranProcTs);
    }

    @Test
    void testTransactionRecordDefaultValues() {
        TransactionRecord record = new TransactionRecord();
        assertNull(record.tranId);
        assertNull(record.tranTypeCd);
        assertNull(record.tranSource);
        assertNull(record.tranDesc);
        assertNull(record.tranAmt);
        assertNull(record.tranMerchantName);
        assertNull(record.tranMerchantCity);
        assertNull(record.tranMerchantZip);
        assertNull(record.tranCardNum);
    }

    @Test
    void testAccountRecordFieldAssignment() {
        AccountRecord account = new AccountRecord();
        account.acctId = 12345L;
        account.acctActiveStatus = "Y";
        account.acctCurrBal = new BigDecimal("1000.00");
        account.acctCreditLimit = new BigDecimal("5000.00");

        assertEquals(12345L, account.acctId);
        assertEquals("Y", account.acctActiveStatus);
        assertEquals(new BigDecimal("1000.00"), account.acctCurrBal);
        assertEquals(new BigDecimal("5000.00"), account.acctCreditLimit);
    }

    @Test
    void testCardXrefRecordFieldAssignment() {
        CardXrefRecord xref = new CardXrefRecord();
        xref.xrefCardNum = "4111111111111111";
        xref.xrefAcctId = 12345L;
        xref.xrefCustId = 67890L;

        assertEquals("4111111111111111", xref.xrefCardNum);
        assertEquals(12345L, xref.xrefAcctId);
        assertEquals(67890L, xref.xrefCustId);
    }

    @Test
    void testCustomerRecordFieldAssignment() {
        CustomerRecord customer = new CustomerRecord();
        customer.custId = 12345L;
        customer.custFirstName = "John";
        customer.custLastName = "Doe";

        assertEquals(12345L, customer.custId);
        assertEquals("John", customer.custFirstName);
        assertEquals("Doe", customer.custLastName);
    }

    @Test
    void testUserSecurityDataFieldAssignment() {
        UserSecurityData user = new UserSecurityData();
        user.secUserId = "admin";
        user.secUserPwd = "password123";
        user.secUserType = "A";

        assertEquals("admin", user.secUserId);
        assertEquals("password123", user.secUserPwd);
        assertEquals("A", user.secUserType);
    }

    @Test
    void testCardDemoCommAreaFieldAssignment() {
        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoUserId = "testuser";
        commArea.cdemoFromTranid = "CT01";
        commArea.cdemoToTranid = "CT02";

        assertEquals("testuser", commArea.cdemoUserId);
        assertEquals("CT01", commArea.cdemoFromTranid);
        assertEquals("CT02", commArea.cdemoToTranid);
    }

    @Test
    void testMultipleInitializationCalls() {
        // Should not throw on multiple calls
        assertDoesNotThrow(() -> {
            controller.initializeSampleData();
            controller.initializeSampleData();
            controller.initializeSampleData();
        });
    }

    @Test
    void testTransactionAmountPrecision() {
        TransactionRecord record = new TransactionRecord();
        record.tranAmt = new BigDecimal("125.99");
        
        assertEquals(new BigDecimal("125.99"), record.tranAmt);
        assertEquals(2, record.tranAmt.scale());
    }

    @Test
    void testTransactionIdFormat() {
        TransactionRecord record = new TransactionRecord();
        record.tranId = "0000000000000001";
        
        assertEquals(16, record.tranId.length());
        assertEquals("0000000000000001", record.tranId);
    }
}