package com.carddemo.controllers;
import com.carddemo.controllers.TransactionListController;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:03:14
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.junit.jupiter.api.Assertions.*;

@WebMvcTest(TransactionListController.class)
class TransactionListControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    void listTransactions_defaultPage_returnsOk() throws Exception {
        mockMvc.perform(get("/api/transactions"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true));
    }

    @Test
    void listTransactions_withPageParameter_returnsOk() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("page", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true));
    }

    @Test
    void listTransactions_withPage2_returnsOk() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("page", "2"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true));
    }

    @Test
    void listTransactions_withStartTranId_returnsOk() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("startTranId", "0000000000000010"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true));
    }

    @Test
    void listTransactions_withEmptyStartTranId_returnsOk() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("startTranId", ""))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true));
    }

    @Test
    void listTransactions_pageOutOfRange_returnsEmptyList() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("page", "100"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.message").value("No transactions found"));
    }

    @Test
    void listTransactions_withHighStartTranId_returnsEmptyOrPartial() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("startTranId", "9999999999999999"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true));
    }

    @Test
    void listTransactions_firstPage_hasPrevPageFalse() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("page", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.hasPrevPage").value(false));
    }

    @Test
    void listTransactions_secondPage_hasPrevPageTrue() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("page", "2"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.hasPrevPage").value(true));
    }

    @Test
    void listTransactions_returnsPageNum() throws Exception {
        mockMvc.perform(get("/api/transactions")
                .param("page", "3"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.pageNum").value(3));
    }
}