package com.carddemo.controllers;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;


// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:02:01
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;

@RestController
@RequestMapping("/api/auth")
public class AuthController {

    private static final String WS_PGMNAME = "COSGN00C";
    private static final String WS_TRANID = "CC00";
    
    private static Map<String, UserSecurityData> userSecurityFile = new HashMap<>();
    
    @PostConstruct
    public void initializeData() {
        UserSecurityData adminUser = new UserSecurityData();
        adminUser.secUsrId = "ADMIN001";
        adminUser.secUsrFname = "SYSTEM";
        adminUser.secUsrLname = "ADMIN";
        adminUser.secUsrPwd = "ADMIN123";
        adminUser.secUsrType = "A";
        userSecurityFile.put("ADMIN001", adminUser);
        
        UserSecurityData regularUser = new UserSecurityData();
        regularUser.secUsrId = "USER0001";
        regularUser.secUsrFname = "JOHN";
        regularUser.secUsrLname = "DOE";
        regularUser.secUsrPwd = "USER1234";
        regularUser.secUsrType = "U";
        userSecurityFile.put("USER0001", regularUser);
    }
    
    @GetMapping("/screen")
    public ResponseEntity<ApiResponse> getSignonScreen() {
        Map<String, Object> screenData = new HashMap<>();
        populateHeaderInfo(screenData);
        screenData.put("userId", "");
        screenData.put("password", "");
        screenData.put("errorMessage", "");
        
        CardDemoCommArea commArea = new CardDemoCommArea();
        
        ApiResponse response = new ApiResponse(true, "Signon screen ready", screenData);
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }
    
    @PostMapping("/login")
    public ResponseEntity<ApiResponse> login(@RequestBody LoginRequest request) {
        String wsMessage = "";
        boolean errFlgOn = false;
        
        if (request.userId == null || request.userId.trim().isEmpty()) {
            errFlgOn = true;
            wsMessage = "Please enter User ID ...";
            return buildErrorResponse(wsMessage, "userId");
        }
        
        if (request.password == null || request.password.trim().isEmpty()) {
            errFlgOn = true;
            wsMessage = "Please enter Password ...";
            return buildErrorResponse(wsMessage, "password");
        }
        
        String wsUserId = request.userId.toUpperCase().trim();
        String wsUserPwd = request.password.toUpperCase().trim();
        
        if (wsUserId.length() > 8) {
            wsUserId = wsUserId.substring(0, 8);
        }
        if (wsUserPwd.length() > 8) {
            wsUserPwd = wsUserPwd.substring(0, 8);
        }
        
        return readUserSecFile(wsUserId, wsUserPwd);
    }
    
    @PostMapping("/logout")
    public ResponseEntity<ApiResponse> logout() {
        MessageData msgData = new MessageData();
        String thankYouMessage = "Thank you for using CardDemo Application";
        
        Map<String, Object> data = new HashMap<>();
        data.put("message", thankYouMessage);
        
        ApiResponse response = new ApiResponse(true, thankYouMessage, data);
        return ResponseEntity.ok(response);
    }
    
    private ResponseEntity<ApiResponse> readUserSecFile(String wsUserId, String wsUserPwd) {
        UserSecurityData secUserData = userSecurityFile.get(wsUserId);
        
        if (secUserData == null) {
            return buildErrorResponse("User not found. Try again ...", "userId");
        }
        
        if (secUserData.secUsrPwd == null || !secUserData.secUsrPwd.equals(wsUserPwd)) {
            return buildErrorResponse("Wrong Password. Try again ...", "password");
        }
        
        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;
        commArea.cdemoUserId = wsUserId;
        commArea.cdemoUserType = secUserData.secUsrType;
        commArea.cdemoPgmContext = 0;
        
        Map<String, Object> data = new HashMap<>();
        data.put("userId", wsUserId);
        data.put("userType", secUserData.secUsrType);
        data.put("firstName", secUserData.secUsrFname);
        data.put("lastName", secUserData.secUsrLname);
        populateHeaderInfo(data);
        
        ApiResponse response = new ApiResponse(true, "Login successful", data);
        response.commArea = commArea;
        
        if ("A".equals(secUserData.secUsrType)) {
            response.redirect = "COADM01C";
        } else {
            response.redirect = "COMEN01C";
        }
        
        return ResponseEntity.ok(response);
    }
    
    private ResponseEntity<ApiResponse> buildErrorResponse(String message, String fieldInError) {
        Map<String, Object> screenData = new HashMap<>();
        populateHeaderInfo(screenData);
        screenData.put("errorMessage", message);
        screenData.put("fieldInError", fieldInError);
        
        ApiResponse response = new ApiResponse(false, message, screenData);
        return ResponseEntity.badRequest().body(response);
    }
    
    private void populateHeaderInfo(Map<String, Object> data) {
        LocalDateTime now = LocalDateTime.now();
        
        data.put("title01", "AWS CardDemo Application");
        data.put("title02", "Sign On");
        data.put("transactionName", WS_TRANID);
        data.put("programName", WS_PGMNAME);
        data.put("currentDate", now.format(DateTimeFormatter.ofPattern("MM/dd/yy")));
        data.put("currentTime", now.format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        data.put("applId", "CARDDEMO");
        data.put("sysId", "SYS1");
    }
    
    public static class LoginRequest {
        public String userId;
        public String password;
        public String action;
        public CardDemoCommArea commArea;
    }
    
    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;
        
        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }
}