package com.carddemo.controllers;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:07:16
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;

@RestController
@RequestMapping("/api/auth")
public class AuthController {

    private static final String WS_PGMNAME = "COSGN00C";
    private static final String WS_TRANID = "CC00";
    private static final String WS_USRSEC_FILE = "USRSEC";

    private static Map<String, UserSecurityData> userSecurityFile = new HashMap<>();

    @PostConstruct
    public void initializeData() {
        UserSecurityData admin = new UserSecurityData();
        admin.secUsrId = "ADMIN001";
        admin.secUsrFname = "SYSTEM";
        admin.secUsrLname = "ADMINISTRATOR";
        admin.secUsrPwd = "ADMIN123";
        admin.secUsrType = "A";
        userSecurityFile.put("ADMIN001", admin);

        UserSecurityData user1 = new UserSecurityData();
        user1.secUsrId = "USER0001";
        user1.secUsrFname = "JOHN";
        user1.secUsrLname = "DOE";
        user1.secUsrPwd = "USER1234";
        user1.secUsrType = "U";
        userSecurityFile.put("USER0001", user1);

        UserSecurityData user2 = new UserSecurityData();
        user2.secUsrId = "USER0002";
        user2.secUsrFname = "JANE";
        user2.secUsrLname = "SMITH";
        user2.secUsrPwd = "PASS5678";
        user2.secUsrType = "U";
        userSecurityFile.put("USER0002", user2);
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }

    public static class LoginRequest {
        public String userId;
        public String password;
        public String action;
        public CardDemoCommArea commArea;
    }

    public static class SignonScreenData {
        public String title01;
        public String title02;
        public String tranName;
        public String pgmName;
        public String curDate;
        public String curTime;
        public String applId;
        public String sysId;
        public String errorMessage;

        public SignonScreenData() {
            this.applId = "CARDDEMO";
            this.sysId = "SYS1";
        }
    }

    @GetMapping("/login")
    public ResponseEntity<ApiResponse> getLoginScreen() {
        SignonScreenData screenData = populateHeaderInfo();
        screenData.errorMessage = "";

        ApiResponse response = new ApiResponse(true, "Login screen initialized", screenData);
        response.commArea = new CardDemoCommArea();
        return ResponseEntity.ok(response);
    }

    @PostMapping("/login")
    public ResponseEntity<ApiResponse> processLogin(@RequestBody LoginRequest request) {
        String wsMessage = "";
        boolean errFlag = false;

        if (request.action != null && "PF3".equalsIgnoreCase(request.action)) {
            ApiResponse response = new ApiResponse(true, "Thank you for using CardDemo application...", null);
            return ResponseEntity.ok(response);
        }

        if (request.userId == null || request.userId.trim().isEmpty()) {
            errFlag = true;
            wsMessage = "Please enter User ID ...";
            return buildErrorResponse(wsMessage);
        }

        if (request.password == null || request.password.trim().isEmpty()) {
            errFlag = true;
            wsMessage = "Please enter Password ...";
            return buildErrorResponse(wsMessage);
        }

        String wsUserId = request.userId.toUpperCase().trim();
        String wsUserPwd = request.password.toUpperCase().trim();

        if (wsUserId.length() > 8) {
            wsUserId = wsUserId.substring(0, 8);
        }
        if (wsUserPwd.length() > 8) {
            wsUserPwd = wsUserPwd.substring(0, 8);
        }

        return readUserSecFile(wsUserId, wsUserPwd);
    }

    @PostMapping("/logout")
    public ResponseEntity<ApiResponse> logout() {
        ApiResponse response = new ApiResponse(true, "Thank you for using CardDemo application...", null);
        return ResponseEntity.ok(response);
    }

    private ResponseEntity<ApiResponse> readUserSecFile(String userId, String password) {
        UserSecurityData userData = userSecurityFile.get(userId);

        if (userData == null) {
            return buildErrorResponse("User not found. Try again ...");
        }

        if (!userData.secUsrPwd.equals(password)) {
            return buildErrorResponse("Wrong Password. Try again ...");
        }

        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;
        commArea.cdemoUserId = userId;
        commArea.cdemoUserType = userData.secUsrType;
        commArea.cdemoPgmContext = 0;

        ApiResponse response;
        if (CardDemoCommArea.CDEMO_USRTYP_ADMIN.equals(userData.secUsrType)) {
            response = new ApiResponse(true, "Login successful - Admin user", null);
            response.redirect = "COADM01C";
        } else {
            response = new ApiResponse(true, "Login successful - Regular user", null);
            response.redirect = "COMEN01C";
        }
        response.commArea = commArea;

        Map<String, Object> loginData = new HashMap<>();
        loginData.put("userId", userId);
        loginData.put("userType", userData.secUsrType);
        loginData.put("firstName", userData.secUsrFname);
        loginData.put("lastName", userData.secUsrLname);
        loginData.put("isAdmin", CardDemoCommArea.CDEMO_USRTYP_ADMIN.equals(userData.secUsrType));
        response.data = loginData;

        return ResponseEntity.ok(response);
    }

    private ResponseEntity<ApiResponse> buildErrorResponse(String message) {
        SignonScreenData screenData = populateHeaderInfo();
        screenData.errorMessage = message;

        ApiResponse response = new ApiResponse(false, message, screenData);
        response.commArea = new CardDemoCommArea();
        return ResponseEntity.badRequest().body(response);
    }

    private SignonScreenData populateHeaderInfo() {
        SignonScreenData screenData = new SignonScreenData();

        LocalDateTime now = LocalDateTime.now();

        screenData.title01 = "CardDemo Application";
        screenData.title02 = "Sign On Screen";
        screenData.tranName = WS_TRANID;
        screenData.pgmName = WS_PGMNAME;

        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MM/dd/yy");
        screenData.curDate = now.format(dateFormatter);

        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        screenData.curTime = now.format(timeFormatter);

        screenData.applId = "CARDDEMO";
        screenData.sysId = "SYS1";

        return screenData;
    }
}