package com.carddemo.controllers;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:06:33
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;

@RestController
@RequestMapping("/api/menu")
public class MenuController {

    private static final String WS_PGMNAME = "COMEN01C";
    private static final String WS_TRANID = "CM00";
    private static final String CCDA_MSG_INVALID_KEY = "Invalid key pressed. Please use Enter or PF3.";
    private static final String CCDA_TITLE01 = "AWS CardDemo";
    private static final String CCDA_TITLE02 = "Main Menu";

    private static final List<MenuOption> MENU_OPTIONS = new ArrayList<>();

    public static class MenuOption {
        public int optNum;
        public String optName;
        public String optPgmName;
        public String optUsrType;

        public MenuOption(int optNum, String optName, String optPgmName, String optUsrType) {
            this.optNum = optNum;
            this.optName = optName;
            this.optPgmName = optPgmName;
            this.optUsrType = optUsrType;
        }
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }

    public static class MenuResponse {
        public String title01;
        public String title02;
        public String transactionName;
        public String programName;
        public String currentDate;
        public String currentTime;
        public List<String> menuOptions;
        public String errorMessage;

        public MenuResponse() {
            this.menuOptions = new ArrayList<>();
        }
    }

    public static class MenuSelectRequest {
        public int option;
        public String action;
        public CardDemoCommArea commArea;
    }

    @PostConstruct
    public void initMenuOptions() {
        MENU_OPTIONS.clear();
        MENU_OPTIONS.add(new MenuOption(1, "View Account", "COACTVWC", "U"));
        MENU_OPTIONS.add(new MenuOption(2, "Update Account", "COACTUPC", "U"));
        MENU_OPTIONS.add(new MenuOption(3, "View Statement", "COSTMTC", "U"));
        MENU_OPTIONS.add(new MenuOption(4, "View Transaction", "COTRN01C", "U"));
        MENU_OPTIONS.add(new MenuOption(5, "Transaction List", "COTRN00C", "U"));
        MENU_OPTIONS.add(new MenuOption(6, "Credit/Debit Card", "COCRDLIC", "U"));
        MENU_OPTIONS.add(new MenuOption(7, "Bill Payment", "COBIL00C", "U"));
        MENU_OPTIONS.add(new MenuOption(8, "Account Report", "CORPT00C", "A"));
        MENU_OPTIONS.add(new MenuOption(9, "User Management", "COUSR00C", "A"));
        MENU_OPTIONS.add(new MenuOption(10, "Batch Processing", "COPAUS0C", "A"));
    }

    @GetMapping
    public ResponseEntity<ApiResponse> getMenu(@RequestHeader(value = "X-Session-Token", required = false) String sessionToken) {
        CardDemoCommArea commArea = new CardDemoCommArea();
        
        if (sessionToken == null || sessionToken.isEmpty()) {
            ApiResponse response = new ApiResponse(false, "No session found. Please sign in.", null);
            response.redirect = "/api/auth/login";
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
        }

        commArea.cdemoFromProgram = "COSGN00C";
        commArea.cdemoPgmContext = CardDemoCommArea.CDEMO_PGM_ENTER;

        MenuResponse menuResponse = buildMenuScreen(commArea, "");
        
        ApiResponse response = new ApiResponse(true, "Menu loaded successfully", menuResponse);
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    @PostMapping
    public ResponseEntity<ApiResponse> getMenuWithCommArea(@RequestBody(required = false) CardDemoCommArea commArea) {
        if (commArea == null) {
            commArea = new CardDemoCommArea();
            commArea.cdemoFromProgram = "COSGN00C";
            
            ApiResponse response = new ApiResponse(false, "No session data. Please sign in.", null);
            response.redirect = "/api/auth/login";
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
        }

        if (commArea.cdemoPgmContext != CardDemoCommArea.CDEMO_PGM_REENTER) {
            commArea.cdemoPgmContext = CardDemoCommArea.CDEMO_PGM_REENTER;
        }

        MenuResponse menuResponse = buildMenuScreen(commArea, "");
        
        ApiResponse response = new ApiResponse(true, "Menu loaded successfully", menuResponse);
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    @PostMapping("/select")
    public ResponseEntity<ApiResponse> selectMenuOption(@RequestBody MenuSelectRequest request) {
        if (request.commArea == null) {
            ApiResponse response = new ApiResponse(false, "No session data. Please sign in.", null);
            response.redirect = "/api/auth/login";
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
        }

        CardDemoCommArea commArea = request.commArea;
        String action = request.action != null ? request.action.toUpperCase() : "ENTER";

        if ("BACK".equals(action) || "PF3".equals(action)) {
            return returnToSignonScreen(commArea);
        }

        if (!"ENTER".equals(action)) {
            MenuResponse menuResponse = buildMenuScreen(commArea, CCDA_MSG_INVALID_KEY);
            ApiResponse response = new ApiResponse(false, CCDA_MSG_INVALID_KEY, menuResponse);
            response.commArea = commArea;
            return ResponseEntity.ok(response);
        }

        return processEnterKey(request.option, commArea);
    }

    private ResponseEntity<ApiResponse> processEnterKey(int option, CardDemoCommArea commArea) {
        int menuOptCount = MENU_OPTIONS.size();

        if (option <= 0 || option > menuOptCount) {
            String errorMsg = "Please enter a valid option number...";
            MenuResponse menuResponse = buildMenuScreen(commArea, errorMsg);
            ApiResponse response = new ApiResponse(false, errorMsg, menuResponse);
            response.commArea = commArea;
            return ResponseEntity.badRequest().body(response);
        }

        MenuOption selectedOption = MENU_OPTIONS.get(option - 1);

        if (commArea.isRegularUser() && "A".equals(selectedOption.optUsrType)) {
            String errorMsg = "No access - Admin Only option...";
            MenuResponse menuResponse = buildMenuScreen(commArea, errorMsg);
            ApiResponse response = new ApiResponse(false, errorMsg, menuResponse);
            response.commArea = commArea;
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body(response);
        }

        String pgmName = selectedOption.optPgmName;

        if ("COPAUS0C".equals(pgmName)) {
            boolean programInstalled = checkProgramInstalled(pgmName);
            if (!programInstalled) {
                String errorMsg = "This option " + selectedOption.optName.trim() + " is not installed...";
                MenuResponse menuResponse = buildMenuScreen(commArea, errorMsg);
                ApiResponse response = new ApiResponse(false, errorMsg, menuResponse);
                response.commArea = commArea;
                return ResponseEntity.ok(response);
            }
        }

        if (pgmName.startsWith("DUMMY")) {
            String infoMsg = "This option " + selectedOption.optName.trim() + " is coming soon...";
            MenuResponse menuResponse = buildMenuScreen(commArea, infoMsg);
            ApiResponse response = new ApiResponse(true, infoMsg, menuResponse);
            response.commArea = commArea;
            return ResponseEntity.ok(response);
        }

        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;
        commArea.cdemoPgmContext = 0;

        String redirectUrl = mapProgramToEndpoint(pgmName);
        
        ApiResponse response = new ApiResponse(true, "Redirecting to " + selectedOption.optName, null);
        response.redirect = redirectUrl;
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private ResponseEntity<ApiResponse> returnToSignonScreen(CardDemoCommArea commArea) {
        String toProgram = commArea.cdemoToProgram;
        if (toProgram == null || toProgram.trim().isEmpty()) {
            toProgram = "COSGN00C";
        }
        commArea.cdemoToProgram = toProgram;

        ApiResponse response = new ApiResponse(true, "Returning to sign-on screen", null);
        response.redirect = "/api/auth/login";
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private MenuResponse buildMenuScreen(CardDemoCommArea commArea, String errorMessage) {
        MenuResponse menuResponse = new MenuResponse();

        menuResponse.title01 = CCDA_TITLE01;
        menuResponse.title02 = CCDA_TITLE02;
        menuResponse.transactionName = WS_TRANID;
        menuResponse.programName = WS_PGMNAME;

        LocalDateTime now = LocalDateTime.now();
        menuResponse.currentDate = now.format(DateTimeFormatter.ofPattern("MM/dd/yy"));
        menuResponse.currentTime = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));

        for (MenuOption opt : MENU_OPTIONS) {
            if (commArea.isRegularUser() && "A".equals(opt.optUsrType)) {
                continue;
            }
            String menuText = String.format("%d. %s", opt.optNum, opt.optName);
            menuResponse.menuOptions.add(menuText);
        }

        menuResponse.errorMessage = errorMessage;

        return menuResponse;
    }

    private boolean checkProgramInstalled(String programName) {
        List<String> installedPrograms = Arrays.asList(
            "COACTVWC", "COACTUPC", "COSTMTC", "COTRN01C", "COTRN00C",
            "COCRDLIC", "COBIL00C", "CORPT00C", "COUSR00C"
        );
        return installedPrograms.contains(programName);
    }

    private String mapProgramToEndpoint(String programName) {
        switch (programName) {
            case "COACTVWC":
                return "/api/accounts/view";
            case "COACTUPC":
                return "/api/accounts/update";
            case "COSTMTC":
                return "/api/statements";
            case "COTRN01C":
                return "/api/transactions/view";
            case "COTRN00C":
                return "/api/transactions";
            case "COCRDLIC":
                return "/api/cards";
            case "COBIL00C":
                return "/api/bills";
            case "CORPT00C":
                return "/api/reports";
            case "COUSR00C":
                return "/api/users";
            case "COPAUS0C":
                return "/api/batch";
            default:
                return "/api/menu";
        }
    }
}