package com.carddemo.controllers;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;


// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:01:24
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;

@RestController
@RequestMapping("/api/menu")
public class MenuController {

    private static final String WS_PGMNAME = "COMEN01C";
    private static final String WS_TRANID = "CM00";

    private List<MenuOption> menuOptions;

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }

    public static class MenuOption {
        public int optionNum;
        public String optionName;
        public String programName;
        public String userType;

        public MenuOption(int optionNum, String optionName, String programName, String userType) {
            this.optionNum = optionNum;
            this.optionName = optionName;
            this.programName = programName;
            this.userType = userType;
        }
    }

    public static class MenuRequest {
        public Integer option;
        public CardDemoCommArea commArea;
        public String action;
    }

    public static class MenuResponse {
        public String title01;
        public String title02;
        public String transactionName;
        public String programName;
        public String currentDate;
        public String currentTime;
        public List<String> menuOptionTexts;
        public String errorMessage;
    }

    @PostConstruct
    public void init() {
        menuOptions = new ArrayList<>();
        menuOptions.add(new MenuOption(1, "View Account", "COACTVWC", "U"));
        menuOptions.add(new MenuOption(2, "View Statement", "COSTMTC", "U"));
        menuOptions.add(new MenuOption(3, "View Transaction", "COTRN00C", "U"));
        menuOptions.add(new MenuOption(4, "Bill Payment", "COBPAY0C", "U"));
        menuOptions.add(new MenuOption(5, "Update Account", "DUMMY001", "U"));
        menuOptions.add(new MenuOption(6, "Credit Card Signup", "CCSIGNUP", "U"));
    }

    @GetMapping
    public ResponseEntity<ApiResponse> getMenu(@RequestHeader(value = "X-Session-Data", required = false) String sessionData) {
        ApiResponse response = new ApiResponse(true, null, null);

        if (sessionData == null || sessionData.isEmpty()) {
            response.success = false;
            response.message = "Session required";
            response.redirect = "COSGN00C";
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
        }

        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoFromProgram = "COSGN00C";

        MenuResponse menuResponse = buildMenuResponse(commArea, null);
        response.data = menuResponse;
        response.commArea = commArea;

        return ResponseEntity.ok(response);
    }

    @PostMapping
    public ResponseEntity<ApiResponse> getMenuWithCommArea(@RequestBody(required = false) CardDemoCommArea commArea) {
        ApiResponse response = new ApiResponse(true, null, null);

        if (commArea == null) {
            commArea = new CardDemoCommArea();
            commArea.cdemoFromProgram = "COSGN00C";
        }

        MenuResponse menuResponse = buildMenuResponse(commArea, null);
        response.data = menuResponse;
        response.commArea = commArea;

        return ResponseEntity.ok(response);
    }

    @PostMapping("/select")
    public ResponseEntity<ApiResponse> selectMenuOption(@RequestBody MenuRequest request) {
        ApiResponse response = new ApiResponse(true, null, null);

        if (request.commArea == null) {
            response.success = false;
            response.message = "Session required";
            response.redirect = "COSGN00C";
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
        }

        CardDemoCommArea commArea = request.commArea;

        if ("back".equalsIgnoreCase(request.action)) {
            return returnToSignonScreen(commArea);
        }

        String errorMessage = processEnterKey(request.option, commArea, response);

        if (errorMessage != null) {
            MenuResponse menuResponse = buildMenuResponse(commArea, errorMessage);
            response.success = false;
            response.message = errorMessage;
            response.data = menuResponse;
            response.commArea = commArea;
            return ResponseEntity.badRequest().body(response);
        }

        if (response.redirect != null) {
            commArea.cdemoFromTranid = WS_TRANID;
            commArea.cdemoFromProgram = WS_PGMNAME;
            commArea.cdemoPgmContext = 0;
            response.commArea = commArea;
            return ResponseEntity.ok(response);
        }

        MenuResponse menuResponse = buildMenuResponse(commArea, null);
        response.data = menuResponse;
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private String processEnterKey(Integer option, CardDemoCommArea commArea, ApiResponse response) {
        if (option == null) {
            return "Please enter a valid option number...";
        }

        int wsOption = option;

        if (wsOption <= 0 || wsOption > menuOptions.size()) {
            return "Please enter a valid option number...";
        }

        MenuOption selectedOption = menuOptions.get(wsOption - 1);

        if (commArea.isRegularUser() && "A".equals(selectedOption.userType)) {
            return "No access - Admin Only option...";
        }

        String programName = selectedOption.programName;

        if ("COPAUS0C".equals(programName)) {
            boolean programExists = checkProgramExists(programName);
            if (programExists) {
                response.redirect = programName;
                return null;
            } else {
                return "This option " + selectedOption.optionName.trim() + " is not installed...";
            }
        }

        if (programName != null && programName.startsWith("DUMMY")) {
            return "This option " + selectedOption.optionName.trim() + " is coming soon ...";
        }

        response.redirect = programName;
        return null;
    }

    private boolean checkProgramExists(String programName) {
        List<String> installedPrograms = Arrays.asList(
            "COACTVWC", "COSTMTC", "COTRN00C", "COTRN01C", "COTRN02C",
            "COBPAY0C", "CCSIGNUP", "COSGN00C", "COMEN01C"
        );
        return installedPrograms.contains(programName);
    }

    private ResponseEntity<ApiResponse> returnToSignonScreen(CardDemoCommArea commArea) {
        ApiResponse response = new ApiResponse(true, "Returning to sign-on screen", null);

        String toProgram = commArea.cdemoToProgram;
        if (toProgram == null || toProgram.trim().isEmpty()) {
            toProgram = "COSGN00C";
        }

        response.redirect = toProgram;
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private MenuResponse buildMenuResponse(CardDemoCommArea commArea, String errorMessage) {
        MenuResponse menuResponse = new MenuResponse();

        TitleData titleData = new TitleData();
        menuResponse.title01 = titleData.ccdaTitle01;
        menuResponse.title02 = titleData.ccdaTitle02;
        menuResponse.transactionName = WS_TRANID;
        menuResponse.programName = WS_PGMNAME;

        LocalDateTime now = LocalDateTime.now();
        menuResponse.currentDate = now.format(DateTimeFormatter.ofPattern("MM/dd/yy"));
        menuResponse.currentTime = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));

        menuResponse.menuOptionTexts = buildMenuOptions(commArea);

        if (errorMessage != null) {
            menuResponse.errorMessage = errorMessage;
        }

        return menuResponse;
    }

    private List<String> buildMenuOptions(CardDemoCommArea commArea) {
        List<String> optionTexts = new ArrayList<>();

        for (MenuOption option : menuOptions) {
            String optionText = String.format("%d. %s", option.optionNum, option.optionName);
            optionTexts.add(optionText);
        }

        return optionTexts;
    }
}