package com.carddemo.controllers;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;


// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:04:55
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import jakarta.annotation.PostConstruct;

@RestController
@RequestMapping("/api/transactions")
public class TransactionAddController {

    private static final String WS_PGMNAME = "COTRN02C";
    private static final String WS_TRANID = "CT02";

    private static Map<String, TransactionRecord> transactFile = new HashMap<>();
    private static Map<String, CardXrefRecord> ccxrefFile = new HashMap<>();
    private static Map<Long, CardXrefRecord> cxacaixFile = new HashMap<>();

    @PostConstruct
    public void initializeData() {
        TransactionRecord tran1 = new TransactionRecord();
        tran1.tranId = "0000000000000001";
        tran1.tranTypeCd = "01";
        tran1.tranCatCd = 5001;
        tran1.tranSource = "POS";
        tran1.tranDesc = "Sample Purchase";
        tran1.tranAmt = new BigDecimal("125.50");
        tran1.tranMerchantId = 12345678901L;
        tran1.tranMerchantName = "ACME Store";
        tran1.tranMerchantCity = "New York";
        tran1.tranMerchantZip = "10001";
        tran1.tranCardNum = "4111111111111111";
        tran1.tranOrigTs = "2024-01-15";
        tran1.tranProcTs = "2024-01-16";
        transactFile.put(tran1.tranId, tran1);

        TransactionRecord tran2 = new TransactionRecord();
        tran2.tranId = "0000000000000002";
        tran2.tranTypeCd = "02";
        tran2.tranCatCd = 5002;
        tran2.tranSource = "ONLINE";
        tran2.tranDesc = "Online Payment";
        tran2.tranAmt = new BigDecimal("-50.00");
        tran2.tranMerchantId = 98765432109L;
        tran2.tranMerchantName = "Web Services";
        tran2.tranMerchantCity = "Chicago";
        tran2.tranMerchantZip = "60601";
        tran2.tranCardNum = "4111111111111111";
        tran2.tranOrigTs = "2024-01-20";
        tran2.tranProcTs = "2024-01-21";
        transactFile.put(tran2.tranId, tran2);

        CardXrefRecord xref1 = new CardXrefRecord();
        xref1.xrefCardNum = "4111111111111111";
        xref1.xrefCustId = 1000001L;
        xref1.xrefAcctId = 80000001001L;
        ccxrefFile.put(xref1.xrefCardNum, xref1);
        cxacaixFile.put(xref1.xrefAcctId, xref1);

        CardXrefRecord xref2 = new CardXrefRecord();
        xref2.xrefCardNum = "5500000000000004";
        xref2.xrefCustId = 1000002L;
        xref2.xrefAcctId = 80000002002L;
        ccxrefFile.put(xref2.xrefCardNum, xref2);
        cxacaixFile.put(xref2.xrefAcctId, xref2);
    }

    @PostMapping
    public ResponseEntity<ApiResponse> addTransaction(@RequestBody TransactionAddRequest request) {
        List<String> errors = new ArrayList<>();
        
        String accountId = request.accountId;
        String cardNumber = request.cardNumber;
        
        if ((accountId == null || accountId.trim().isEmpty()) && 
            (cardNumber == null || cardNumber.trim().isEmpty())) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Account or Card Number must be entered...", null));
        }
        
        CardXrefRecord xrefRecord = null;
        
        if (accountId != null && !accountId.trim().isEmpty()) {
            if (!isNumeric(accountId)) {
                return ResponseEntity.badRequest().body(
                    new ApiResponse(false, "Account ID must be Numeric...", null));
            }
            long acctIdNum = Long.parseLong(accountId.trim());
            xrefRecord = cxacaixFile.get(acctIdNum);
            if (xrefRecord == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ApiResponse(false, "Account ID NOT found...", null));
            }
            cardNumber = xrefRecord.xrefCardNum;
        } else if (cardNumber != null && !cardNumber.trim().isEmpty()) {
            if (!isNumeric(cardNumber)) {
                return ResponseEntity.badRequest().body(
                    new ApiResponse(false, "Card Number must be Numeric...", null));
            }
            xrefRecord = ccxrefFile.get(cardNumber.trim());
            if (xrefRecord == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ApiResponse(false, "Card Number NOT found...", null));
            }
            accountId = String.valueOf(xrefRecord.xrefAcctId);
        }
        
        if (request.typeCode == null || request.typeCode.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Type CD can NOT be empty...", null));
        }
        if (request.categoryCode == null || request.categoryCode.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Category CD can NOT be empty...", null));
        }
        if (request.source == null || request.source.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Source can NOT be empty...", null));
        }
        if (request.description == null || request.description.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Description can NOT be empty...", null));
        }
        if (request.amount == null || request.amount.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Amount can NOT be empty...", null));
        }
        if (request.origDate == null || request.origDate.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Orig Date can NOT be empty...", null));
        }
        if (request.procDate == null || request.procDate.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Proc Date can NOT be empty...", null));
        }
        if (request.merchantId == null || request.merchantId.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Merchant ID can NOT be empty...", null));
        }
        if (request.merchantName == null || request.merchantName.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Merchant Name can NOT be empty...", null));
        }
        if (request.merchantCity == null || request.merchantCity.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Merchant City can NOT be empty...", null));
        }
        if (request.merchantZip == null || request.merchantZip.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Merchant Zip can NOT be empty...", null));
        }
        
        if (!isNumeric(request.typeCode)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Type CD must be Numeric...", null));
        }
        if (!isNumeric(request.categoryCode)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Category CD must be Numeric...", null));
        }
        
        BigDecimal amountValue;
        try {
            amountValue = new BigDecimal(request.amount.trim());
        } catch (NumberFormatException e) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Amount should be in format -99999999.99", null));
        }
        
        if (!isValidDateFormat(request.origDate)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Orig Date should be in format YYYY-MM-DD", null));
        }
        if (!isValidDate(request.origDate)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Orig Date - Not a valid date...", null));
        }
        
        if (!isValidDateFormat(request.procDate)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Proc Date should be in format YYYY-MM-DD", null));
        }
        if (!isValidDate(request.procDate)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Proc Date - Not a valid date...", null));
        }
        
        if (!isNumeric(request.merchantId)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Merchant ID must be Numeric...", null));
        }
        
        if (request.confirm == null || request.confirm.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Confirm to add this transaction...", null));
        }
        
        String confirmValue = request.confirm.trim().toUpperCase();
        if (!confirmValue.equals("Y") && !confirmValue.equals("N")) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Invalid value. Valid values are (Y/N)...", null));
        }
        
        if (confirmValue.equals("N")) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Confirm to add this transaction...", null));
        }
        
        String newTranId = generateNextTranId();
        
        TransactionRecord newTran = new TransactionRecord();
        newTran.tranId = newTranId;
        newTran.tranTypeCd = request.typeCode.trim();
        newTran.tranCatCd = Integer.parseInt(request.categoryCode.trim());
        newTran.tranSource = request.source.trim();
        newTran.tranDesc = request.description.trim();
        newTran.tranAmt = amountValue;
        newTran.tranCardNum = cardNumber;
        newTran.tranMerchantId = Long.parseLong(request.merchantId.trim());
        newTran.tranMerchantName = request.merchantName.trim();
        newTran.tranMerchantCity = request.merchantCity.trim();
        newTran.tranMerchantZip = request.merchantZip.trim();
        newTran.tranOrigTs = request.origDate.trim();
        newTran.tranProcTs = request.procDate.trim();
        
        if (transactFile.containsKey(newTranId)) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(
                new ApiResponse(false, "Tran ID already exist...", null));
        }
        
        transactFile.put(newTranId, newTran);
        
        Map<String, Object> responseData = new HashMap<>();
        responseData.put("tranId", newTranId);
        responseData.put("transaction", newTran);
        responseData.put("currentDate", LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yy")));
        responseData.put("currentTime", LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        
        String successMessage = "Transaction added successfully. Your Tran ID is " + newTranId.trim() + ".";
        
        ApiResponse response = new ApiResponse(true, successMessage, responseData);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @PostMapping("/copy-last")
    public ResponseEntity<ApiResponse> copyLastTransaction(@RequestBody TransactionCopyRequest request) {
        String accountId = request.accountId;
        String cardNumber = request.cardNumber;
        
        if ((accountId == null || accountId.trim().isEmpty()) && 
            (cardNumber == null || cardNumber.trim().isEmpty())) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Account or Card Number must be entered...", null));
        }
        
        CardXrefRecord xrefRecord = null;
        
        if (accountId != null && !accountId.trim().isEmpty()) {
            if (!isNumeric(accountId)) {
                return ResponseEntity.badRequest().body(
                    new ApiResponse(false, "Account ID must be Numeric...", null));
            }
            long acctIdNum = Long.parseLong(accountId.trim());
            xrefRecord = cxacaixFile.get(acctIdNum);
            if (xrefRecord == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ApiResponse(false, "Account ID NOT found...", null));
            }
            cardNumber = xrefRecord.xrefCardNum;
        } else if (cardNumber != null && !cardNumber.trim().isEmpty()) {
            if (!isNumeric(cardNumber)) {
                return ResponseEntity.badRequest().body(
                    new ApiResponse(false, "Card Number must be Numeric...", null));
            }
            xrefRecord = ccxrefFile.get(cardNumber.trim());
            if (xrefRecord == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ApiResponse(false, "Card Number NOT found...", null));
            }
            accountId = String.valueOf(xrefRecord.xrefAcctId);
        }
        
        TransactionRecord lastTran = getLastTransaction();
        
        if (lastTran == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                new ApiResponse(false, "No previous transaction found...", null));
        }
        
        Map<String, Object> responseData = new HashMap<>();
        responseData.put("accountId", accountId);
        responseData.put("cardNumber", cardNumber);
        responseData.put("typeCode", lastTran.tranTypeCd);
        responseData.put("categoryCode", String.valueOf(lastTran.tranCatCd));
        responseData.put("source", lastTran.tranSource);
        responseData.put("description", lastTran.tranDesc);
        responseData.put("amount", lastTran.tranAmt.toString());
        responseData.put("origDate", lastTran.tranOrigTs);
        responseData.put("procDate", lastTran.tranProcTs);
        responseData.put("merchantId", String.valueOf(lastTran.tranMerchantId));
        responseData.put("merchantName", lastTran.tranMerchantName);
        responseData.put("merchantCity", lastTran.tranMerchantCity);
        responseData.put("merchantZip", lastTran.tranMerchantZip);
        responseData.put("currentDate", LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yy")));
        responseData.put("currentTime", LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        
        return ResponseEntity.ok(new ApiResponse(true, "Last transaction data copied", responseData));
    }

    @GetMapping("/add-form")
    public ResponseEntity<ApiResponse> getAddForm(@RequestParam(required = false) String cardNumber) {
        Map<String, Object> responseData = new HashMap<>();
        responseData.put("programName", WS_PGMNAME);
        responseData.put("transactionId", WS_TRANID);
        responseData.put("currentDate", LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yy")));
        responseData.put("currentTime", LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        
        if (cardNumber != null && !cardNumber.trim().isEmpty()) {
            CardXrefRecord xref = ccxrefFile.get(cardNumber.trim());
            if (xref != null) {
                responseData.put("cardNumber", cardNumber);
                responseData.put("accountId", String.valueOf(xref.xrefAcctId));
            }
        }
        
        return ResponseEntity.ok(new ApiResponse(true, "Add transaction form", responseData));
    }

    @PostMapping("/clear")
    public ResponseEntity<ApiResponse> clearForm(@RequestBody(required = false) CardDemoCommArea commArea) {
        Map<String, Object> responseData = new HashMap<>();
        responseData.put("programName", WS_PGMNAME);
        responseData.put("transactionId", WS_TRANID);
        responseData.put("currentDate", LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yy")));
        responseData.put("currentTime", LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        responseData.put("accountId", "");
        responseData.put("cardNumber", "");
        responseData.put("typeCode", "");
        responseData.put("categoryCode", "");
        responseData.put("source", "");
        responseData.put("description", "");
        responseData.put("amount", "");
        responseData.put("origDate", "");
        responseData.put("procDate", "");
        responseData.put("merchantId", "");
        responseData.put("merchantName", "");
        responseData.put("merchantCity", "");
        responseData.put("merchantZip", "");
        responseData.put("confirm", "");
        
        ApiResponse response = new ApiResponse(true, "Form cleared", responseData);
        if (commArea != null) {
            response.commArea = commArea;
        }
        return ResponseEntity.ok(response);
    }

    @PostMapping("/back")
    public ResponseEntity<ApiResponse> goBack(@RequestBody(required = false) CardDemoCommArea commArea) {
        String redirect = "COMEN01C";
        if (commArea != null && commArea.cdemoFromProgram != null && 
            !commArea.cdemoFromProgram.trim().isEmpty()) {
            redirect = commArea.cdemoFromProgram;
        }
        
        ApiResponse response = new ApiResponse(true, "Returning to previous screen", null);
        response.redirect = redirect;
        if (commArea != null) {
            commArea.cdemoFromTranid = WS_TRANID;
            commArea.cdemoFromProgram = WS_PGMNAME;
            commArea.cdemoPgmContext = 0;
            response.commArea = commArea;
        }
        return ResponseEntity.ok(response);
    }

    private String generateNextTranId() {
        long maxId = 0;
        for (String key : transactFile.keySet()) {
            try {
                long id = Long.parseLong(key.trim());
                if (id > maxId) {
                    maxId = id;
                }
            } catch (NumberFormatException e) {
                // Skip non-numeric keys
            }
        }
        return String.format("%016d", maxId + 1);
    }

    private TransactionRecord getLastTransaction() {
        TransactionRecord lastTran = null;
        String maxId = null;
        
        for (Map.Entry<String, TransactionRecord> entry : transactFile.entrySet()) {
            if (maxId == null || entry.getKey().compareTo(maxId) > 0) {
                maxId = entry.getKey();
                lastTran = entry.getValue();
            }
        }
        return lastTran;
    }

    private boolean isNumeric(String str) {
        if (str == null || str.trim().isEmpty()) {
            return false;
        }
        try {
            Long.parseLong(str.trim());
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private boolean isValidDateFormat(String date) {
        if (date == null || date.length() != 10) {
            return false;
        }
        String year = date.substring(0, 4);
        String dash1 = date.substring(4, 5);
        String month = date.substring(5, 7);
        String dash2 = date.substring(7, 8);
        String day = date.substring(8, 10);
        
        if (!dash1.equals("-") || !dash2.equals("-")) {
            return false;
        }
        if (!isNumeric(year) || !isNumeric(month) || !isNumeric(day)) {
            return false;
        }
        return true;
    }

    private boolean isValidDate(String date) {
        try {
            LocalDate.parse(date, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            return true;
        } catch (DateTimeParseException e) {
            return false;
        }
    }

    public static class TransactionAddRequest {
        public String accountId;
        public String cardNumber;
        public String typeCode;
        public String categoryCode;
        public String source;
        public String description;
        public String amount;
        public String origDate;
        public String procDate;
        public String merchantId;
        public String merchantName;
        public String merchantCity;
        public String merchantZip;
        public String confirm;
    }

    public static class TransactionCopyRequest {
        public String accountId;
        public String cardNumber;
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }
}