package com.carddemo.controllers;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:10:14
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;
import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;

@RestController
@RequestMapping("/api/transactions")
public class TransactionAddController {

    private static Map<String, TransactionRecord> transactFile = new HashMap<>();
    private static Map<String, CardXrefRecord> ccxrefFile = new HashMap<>();
    private static Map<Long, CardXrefRecord> cxacaixFile = new HashMap<>();

    @PostConstruct
    public void initializeData() {
        CardXrefRecord xref1 = new CardXrefRecord();
        xref1.xrefCardNum = "4111111111111111";
        xref1.xrefAcctId = 80000001001L;
        xref1.xrefCustId = 1000001L;
        ccxrefFile.put(xref1.xrefCardNum, xref1);
        cxacaixFile.put(xref1.xrefAcctId, xref1);

        CardXrefRecord xref2 = new CardXrefRecord();
        xref2.xrefCardNum = "4222222222222222";
        xref2.xrefAcctId = 80000002002L;
        xref2.xrefCustId = 1000002L;
        ccxrefFile.put(xref2.xrefCardNum, xref2);
        cxacaixFile.put(xref2.xrefAcctId, xref2);

        TransactionRecord tran1 = new TransactionRecord();
        tran1.tranId = "0000000000000001";
        tran1.tranTypeCd = "PU";
        tran1.tranCatCd = 5001;
        tran1.tranSource = "ONLINE";
        tran1.tranDesc = "Sample Purchase Transaction";
        tran1.tranAmt = new BigDecimal("125.50");
        tran1.tranCardNum = "4111111111111111";
        tran1.tranMerchantId = 123456789L;
        tran1.tranMerchantName = "Sample Merchant";
        tran1.tranMerchantCity = "New York";
        tran1.tranMerchantZip = "10001";
        tran1.tranOrigTs = "2024-01-15";
        tran1.tranProcTs = "2024-01-15";
        transactFile.put(tran1.tranId, tran1);

        TransactionRecord tran2 = new TransactionRecord();
        tran2.tranId = "0000000000000002";
        tran2.tranTypeCd = "SA";
        tran2.tranCatCd = 5002;
        tran2.tranSource = "POS";
        tran2.tranDesc = "Sample Sale Transaction";
        tran2.tranAmt = new BigDecimal("75.25");
        tran2.tranCardNum = "4222222222222222";
        tran2.tranMerchantId = 987654321L;
        tran2.tranMerchantName = "Another Store";
        tran2.tranMerchantCity = "Los Angeles";
        tran2.tranMerchantZip = "90001";
        tran2.tranOrigTs = "2024-01-16";
        tran2.tranProcTs = "2024-01-16";
        transactFile.put(tran2.tranId, tran2);
    }

    @PostMapping
    public ResponseEntity<ApiResponse> addTransaction(@RequestBody TransactionAddRequest request) {
        List<String> errors = new ArrayList<>();
        
        String accountId = request.accountId;
        String cardNumber = request.cardNumber;
        CardXrefRecord xrefRecord = null;

        if (accountId != null && !accountId.trim().isEmpty()) {
            try {
                long acctIdNum = Long.parseLong(accountId.trim());
                xrefRecord = cxacaixFile.get(acctIdNum);
                if (xrefRecord == null) {
                    return ResponseEntity.status(HttpStatus.NOT_FOUND)
                        .body(new ApiResponse(false, "Account ID NOT found...", null));
                }
                cardNumber = xrefRecord.xrefCardNum;
            } catch (NumberFormatException e) {
                return ResponseEntity.badRequest()
                    .body(new ApiResponse(false, "Account ID must be Numeric...", null));
            }
        } else if (cardNumber != null && !cardNumber.trim().isEmpty()) {
            if (!cardNumber.trim().matches("\\d+")) {
                return ResponseEntity.badRequest()
                    .body(new ApiResponse(false, "Card Number must be Numeric...", null));
            }
            xrefRecord = ccxrefFile.get(cardNumber.trim());
            if (xrefRecord == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ApiResponse(false, "Card Number NOT found...", null));
            }
            accountId = String.valueOf(xrefRecord.xrefAcctId);
        } else {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Account or Card Number must be entered...", null));
        }

        if (request.typeCode == null || request.typeCode.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Type CD can NOT be empty...", null));
        }

        if (request.categoryCode == null || request.categoryCode.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Category CD can NOT be empty...", null));
        }
        if (!request.categoryCode.trim().matches("\\d+")) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Category CD must be Numeric...", null));
        }

        if (request.source == null || request.source.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Source can NOT be empty...", null));
        }

        if (request.description == null || request.description.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Description can NOT be empty...", null));
        }

        if (request.amount == null || request.amount.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Amount can NOT be empty...", null));
        }
        BigDecimal amountValue;
        try {
            amountValue = new BigDecimal(request.amount.trim());
        } catch (NumberFormatException e) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Amount should be in format -99999999.99", null));
        }

        if (request.origDate == null || request.origDate.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Orig Date can NOT be empty...", null));
        }
        if (!isValidDateFormat(request.origDate.trim())) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Orig Date should be in format YYYY-MM-DD", null));
        }
        if (!isValidDate(request.origDate.trim())) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Orig Date - Not a valid date...", null));
        }

        if (request.procDate == null || request.procDate.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Proc Date can NOT be empty...", null));
        }
        if (!isValidDateFormat(request.procDate.trim())) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Proc Date should be in format YYYY-MM-DD", null));
        }
        if (!isValidDate(request.procDate.trim())) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Proc Date - Not a valid date...", null));
        }

        if (request.merchantId == null || request.merchantId.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Merchant ID can NOT be empty...", null));
        }
        if (!request.merchantId.trim().matches("\\d+")) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Merchant ID must be Numeric...", null));
        }

        if (request.merchantName == null || request.merchantName.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Merchant Name can NOT be empty...", null));
        }

        if (request.merchantCity == null || request.merchantCity.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Merchant City can NOT be empty...", null));
        }

        if (request.merchantZip == null || request.merchantZip.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Merchant Zip can NOT be empty...", null));
        }

        if (request.confirm == null || request.confirm.trim().isEmpty()) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Confirm to add this transaction...", null));
        }
        String confirmValue = request.confirm.trim().toUpperCase();
        if (!confirmValue.equals("Y") && !confirmValue.equals("N")) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Invalid value. Valid values are (Y/N)...", null));
        }
        if (confirmValue.equals("N")) {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Confirm to add this transaction...", null));
        }

        String newTranId = generateNextTranId();

        TransactionRecord newTran = new TransactionRecord();
        newTran.tranId = newTranId;
        newTran.tranTypeCd = request.typeCode.trim();
        newTran.tranCatCd = Integer.parseInt(request.categoryCode.trim());
        newTran.tranSource = request.source.trim();
        newTran.tranDesc = request.description.trim();
        newTran.tranAmt = amountValue;
        newTran.tranCardNum = cardNumber;
        newTran.tranMerchantId = Long.parseLong(request.merchantId.trim());
        newTran.tranMerchantName = request.merchantName.trim();
        newTran.tranMerchantCity = request.merchantCity.trim();
        newTran.tranMerchantZip = request.merchantZip.trim();
        newTran.tranOrigTs = request.origDate.trim();
        newTran.tranProcTs = request.procDate.trim();

        if (transactFile.containsKey(newTranId)) {
            return ResponseEntity.status(HttpStatus.CONFLICT)
                .body(new ApiResponse(false, "Tran ID already exist...", null));
        }

        transactFile.put(newTranId, newTran);

        Map<String, Object> responseData = new HashMap<>();
        responseData.put("tranId", newTranId);
        responseData.put("transaction", newTran);
        
        String message = "Transaction added successfully. Your Tran ID is " + newTranId.trim() + ".";
        
        ApiResponse response = new ApiResponse(true, message, responseData);
        response.commArea = request.commArea;
        
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @PostMapping("/copy-last")
    public ResponseEntity<ApiResponse> copyLastTransaction(@RequestBody CopyLastRequest request) {
        String accountId = request.accountId;
        String cardNumber = request.cardNumber;
        CardXrefRecord xrefRecord = null;

        if (accountId != null && !accountId.trim().isEmpty()) {
            try {
                long acctIdNum = Long.parseLong(accountId.trim());
                xrefRecord = cxacaixFile.get(acctIdNum);
                if (xrefRecord == null) {
                    return ResponseEntity.status(HttpStatus.NOT_FOUND)
                        .body(new ApiResponse(false, "Account ID NOT found...", null));
                }
                cardNumber = xrefRecord.xrefCardNum;
            } catch (NumberFormatException e) {
                return ResponseEntity.badRequest()
                    .body(new ApiResponse(false, "Account ID must be Numeric...", null));
            }
        } else if (cardNumber != null && !cardNumber.trim().isEmpty()) {
            if (!cardNumber.trim().matches("\\d+")) {
                return ResponseEntity.badRequest()
                    .body(new ApiResponse(false, "Card Number must be Numeric...", null));
            }
            xrefRecord = ccxrefFile.get(cardNumber.trim());
            if (xrefRecord == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ApiResponse(false, "Card Number NOT found...", null));
            }
            accountId = String.valueOf(xrefRecord.xrefAcctId);
        } else {
            return ResponseEntity.badRequest()
                .body(new ApiResponse(false, "Account or Card Number must be entered...", null));
        }

        TransactionRecord lastTran = getLastTransaction();
        
        Map<String, Object> responseData = new HashMap<>();
        responseData.put("accountId", accountId);
        responseData.put("cardNumber", cardNumber);
        
        if (lastTran != null) {
            responseData.put("typeCode", lastTran.tranTypeCd);
            responseData.put("categoryCode", String.valueOf(lastTran.tranCatCd));
            responseData.put("source", lastTran.tranSource);
            responseData.put("amount", lastTran.tranAmt.toString());
            responseData.put("description", lastTran.tranDesc);
            responseData.put("origDate", lastTran.tranOrigTs);
            responseData.put("procDate", lastTran.tranProcTs);
            responseData.put("merchantId", String.valueOf(lastTran.tranMerchantId));
            responseData.put("merchantName", lastTran.tranMerchantName);
            responseData.put("merchantCity", lastTran.tranMerchantCity);
            responseData.put("merchantZip", lastTran.tranMerchantZip);
        }

        ApiResponse response = new ApiResponse(true, "Last transaction data copied", responseData);
        response.commArea = request.commArea;
        
        return ResponseEntity.ok(response);
    }

    @GetMapping("/add/init")
    public ResponseEntity<ApiResponse> initAddScreen(
            @RequestParam(required = false) String cardNumber,
            @RequestParam(required = false) String accountId) {
        
        Map<String, Object> responseData = new HashMap<>();
        responseData.put("title01", "AWS CardDemo");
        responseData.put("title02", "Add Transaction");
        responseData.put("programName", "COTRN02C");
        responseData.put("tranId", "CT02");
        
        LocalDateTime now = LocalDateTime.now();
        responseData.put("currentDate", now.format(DateTimeFormatter.ofPattern("MM/dd/yy")));
        responseData.put("currentTime", now.format(DateTimeFormatter.ofPattern("HH:mm:ss")));

        if (cardNumber != null && !cardNumber.trim().isEmpty()) {
            responseData.put("cardNumber", cardNumber);
            CardXrefRecord xref = ccxrefFile.get(cardNumber.trim());
            if (xref != null) {
                responseData.put("accountId", String.valueOf(xref.xrefAcctId));
            }
        } else if (accountId != null && !accountId.trim().isEmpty()) {
            try {
                long acctIdNum = Long.parseLong(accountId.trim());
                CardXrefRecord xref = cxacaixFile.get(acctIdNum);
                if (xref != null) {
                    responseData.put("accountId", accountId);
                    responseData.put("cardNumber", xref.xrefCardNum);
                }
            } catch (NumberFormatException e) {
                // ignore
            }
        }

        return ResponseEntity.ok(new ApiResponse(true, null, responseData));
    }

    @PostMapping("/clear")
    public ResponseEntity<ApiResponse> clearScreen(@RequestBody(required = false) CardDemoCommArea commArea) {
        Map<String, Object> responseData = new HashMap<>();
        responseData.put("title01", "AWS CardDemo");
        responseData.put("title02", "Add Transaction");
        responseData.put("programName", "COTRN02C");
        responseData.put("tranId", "CT02");
        
        LocalDateTime now = LocalDateTime.now();
        responseData.put("currentDate", now.format(DateTimeFormatter.ofPattern("MM/dd/yy")));
        responseData.put("currentTime", now.format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        
        responseData.put("accountId", "");
        responseData.put("cardNumber", "");
        responseData.put("typeCode", "");
        responseData.put("categoryCode", "");
        responseData.put("source", "");
        responseData.put("amount", "");
        responseData.put("description", "");
        responseData.put("origDate", "");
        responseData.put("procDate", "");
        responseData.put("merchantId", "");
        responseData.put("merchantName", "");
        responseData.put("merchantCity", "");
        responseData.put("merchantZip", "");
        responseData.put("confirm", "");

        ApiResponse response = new ApiResponse(true, null, responseData);
        response.commArea = commArea;
        
        return ResponseEntity.ok(response);
    }

    private String generateNextTranId() {
        long maxId = 0;
        for (String key : transactFile.keySet()) {
            try {
                long id = Long.parseLong(key.trim());
                if (id > maxId) {
                    maxId = id;
                }
            } catch (NumberFormatException e) {
                // skip non-numeric keys
            }
        }
        maxId++;
        return String.format("%016d", maxId);
    }

    private TransactionRecord getLastTransaction() {
        TransactionRecord lastTran = null;
        String maxKey = null;
        for (String key : transactFile.keySet()) {
            if (maxKey == null || key.compareTo(maxKey) > 0) {
                maxKey = key;
            }
        }
        if (maxKey != null) {
            lastTran = transactFile.get(maxKey);
        }
        return lastTran;
    }

    private boolean isValidDateFormat(String date) {
        if (date == null || date.length() != 10) {
            return false;
        }
        String year = date.substring(0, 4);
        String dash1 = date.substring(4, 5);
        String month = date.substring(5, 7);
        String dash2 = date.substring(7, 8);
        String day = date.substring(8, 10);
        
        if (!dash1.equals("-") || !dash2.equals("-")) {
            return false;
        }
        if (!year.matches("\\d{4}") || !month.matches("\\d{2}") || !day.matches("\\d{2}")) {
            return false;
        }
        return true;
    }

    private boolean isValidDate(String date) {
        try {
            LocalDate.parse(date, DateTimeFormatter.ISO_LOCAL_DATE);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public static class TransactionAddRequest {
        public String accountId;
        public String cardNumber;
        public String typeCode;
        public String categoryCode;
        public String source;
        public String description;
        public String amount;
        public String origDate;
        public String procDate;
        public String merchantId;
        public String merchantName;
        public String merchantCity;
        public String merchantZip;
        public String confirm;
        public CardDemoCommArea commArea;
    }

    public static class CopyLastRequest {
        public String accountId;
        public String cardNumber;
        public CardDemoCommArea commArea;
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }
}