package com.carddemo.controllers;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;


// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:03:48
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;

@RestController
@RequestMapping("/api/transactions")
public class TransactionViewController {

    private static final String WS_PGMNAME = "COTRN01C";
    private static final String WS_TRANID = "CT01";
    private static final String WS_TRANSACT_FILE = "TRANSACT";

    private static Map<String, TransactionRecord> transactFile = new HashMap<>();

    @PostConstruct
    public void initializeData() {
        TransactionRecord tran1 = new TransactionRecord();
        tran1.tranId = "0000000000000001";
        tran1.tranTypeCd = "SA";
        tran1.tranCatCd = 5001;
        tran1.tranSource = "POS";
        tran1.tranDesc = "Purchase at Store ABC";
        tran1.tranAmt = new BigDecimal("125.50");
        tran1.tranMerchantId = 100001L;
        tran1.tranMerchantName = "Store ABC";
        tran1.tranMerchantCity = "New York";
        tran1.tranMerchantZip = "10001";
        tran1.tranCardNum = "4111111111111111";
        tran1.tranOrigTs = "2024-01-15 10:30:00";
        tran1.tranProcTs = "2024-01-15 10:30:05";
        transactFile.put(tran1.tranId, tran1);

        TransactionRecord tran2 = new TransactionRecord();
        tran2.tranId = "0000000000000002";
        tran2.tranTypeCd = "CR";
        tran2.tranCatCd = 5002;
        tran2.tranSource = "ONLINE";
        tran2.tranDesc = "Online Purchase XYZ";
        tran2.tranAmt = new BigDecimal("299.99");
        tran2.tranMerchantId = 100002L;
        tran2.tranMerchantName = "XYZ Online";
        tran2.tranMerchantCity = "Los Angeles";
        tran2.tranMerchantZip = "90001";
        tran2.tranCardNum = "4222222222222222";
        tran2.tranOrigTs = "2024-01-16 14:45:00";
        tran2.tranProcTs = "2024-01-16 14:45:10";
        transactFile.put(tran2.tranId, tran2);

        TransactionRecord tran3 = new TransactionRecord();
        tran3.tranId = "0000000000000003";
        tran3.tranTypeCd = "SA";
        tran3.tranCatCd = 5003;
        tran3.tranSource = "ATM";
        tran3.tranDesc = "ATM Withdrawal";
        tran3.tranAmt = new BigDecimal("500.00");
        tran3.tranMerchantId = 100003L;
        tran3.tranMerchantName = "Bank ATM";
        tran3.tranMerchantCity = "Chicago";
        tran3.tranMerchantZip = "60601";
        tran3.tranCardNum = "4333333333333333";
        tran3.tranOrigTs = "2024-01-17 09:00:00";
        tran3.tranProcTs = "2024-01-17 09:00:03";
        transactFile.put(tran3.tranId, tran3);
    }

    @GetMapping("/{id}")
    public ResponseEntity<ApiResponse> viewTransaction(
            @PathVariable("id") String tranId,
            @RequestHeader(value = "X-CommArea", required = false) String commAreaHeader) {

        CardDemoCommArea commArea = new CardDemoCommArea();
        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;

        if (tranId == null || tranId.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Tran ID can NOT be empty...", null, null, commArea));
        }

        String paddedTranId = padTranId(tranId);
        TransactionRecord tran = readTransactFile(paddedTranId);

        if (tran == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                new ApiResponse(false, "Transaction ID NOT found...", null, null, commArea));
        }

        TransactionViewResponse viewData = buildTransactionView(tran);
        populateHeaderInfo(viewData);

        return ResponseEntity.ok(new ApiResponse(true, null, viewData, null, commArea));
    }

    @PostMapping("/view")
    public ResponseEntity<ApiResponse> viewTransactionPost(@RequestBody TransactionViewRequest request) {

        CardDemoCommArea commArea = request.commArea != null ? request.commArea : new CardDemoCommArea();
        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;

        String action = request.action;

        if ("back".equalsIgnoreCase(action) || "pf3".equalsIgnoreCase(action)) {
            String toProgram = (commArea.cdemoFromProgram == null || commArea.cdemoFromProgram.trim().isEmpty())
                ? "COMEN01C" : commArea.cdemoFromProgram;
            return ResponseEntity.ok(new ApiResponse(true, null, null, mapProgramToRedirect(toProgram), commArea));
        }

        if ("clear".equalsIgnoreCase(action) || "pf4".equalsIgnoreCase(action)) {
            TransactionViewResponse viewData = new TransactionViewResponse();
            populateHeaderInfo(viewData);
            return ResponseEntity.ok(new ApiResponse(true, "Screen cleared", viewData, null, commArea));
        }

        if ("list".equalsIgnoreCase(action) || "pf5".equalsIgnoreCase(action)) {
            return ResponseEntity.ok(new ApiResponse(true, null, null, "/api/transactions", commArea));
        }

        String tranIdInput = request.tranIdInput;
        if (tranIdInput == null || tranIdInput.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Tran ID can NOT be empty...", null, null, commArea));
        }

        String paddedTranId = padTranId(tranIdInput);
        TransactionRecord tran = readTransactFile(paddedTranId);

        if (tran == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                new ApiResponse(false, "Transaction ID NOT found...", null, null, commArea));
        }

        TransactionViewResponse viewData = buildTransactionView(tran);
        populateHeaderInfo(viewData);

        return ResponseEntity.ok(new ApiResponse(true, null, viewData, null, commArea));
    }

    private TransactionRecord readTransactFile(String tranId) {
        return transactFile.get(tranId);
    }

    private String padTranId(String tranId) {
        if (tranId == null) return null;
        String trimmed = tranId.trim();
        if (trimmed.length() >= 16) return trimmed.substring(0, 16);
        return String.format("%16s", trimmed).replace(' ', '0');
    }

    private TransactionViewResponse buildTransactionView(TransactionRecord tran) {
        TransactionViewResponse response = new TransactionViewResponse();
        response.tranId = tran.tranId;
        response.cardNum = tran.tranCardNum;
        response.tranTypeCd = tran.tranTypeCd;
        response.tranCatCd = tran.tranCatCd;
        response.tranSource = tran.tranSource;
        response.tranAmt = formatAmount(tran.tranAmt);
        response.tranDesc = tran.tranDesc;
        response.tranOrigTs = tran.tranOrigTs;
        response.tranProcTs = tran.tranProcTs;
        response.merchantId = tran.tranMerchantId;
        response.merchantName = tran.tranMerchantName;
        response.merchantCity = tran.tranMerchantCity;
        response.merchantZip = tran.tranMerchantZip;
        return response;
    }

    private String formatAmount(BigDecimal amount) {
        if (amount == null) return "+00000000.00";
        String sign = amount.compareTo(BigDecimal.ZERO) >= 0 ? "+" : "";
        return sign + String.format("%011.2f", amount.abs());
    }

    private void populateHeaderInfo(TransactionViewResponse response) {
        LocalDateTime now = LocalDateTime.now();
        response.curDate = now.format(DateTimeFormatter.ofPattern("MM/dd/yy"));
        response.curTime = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        response.trnName = WS_TRANID;
        response.pgmName = WS_PGMNAME;
        response.title01 = "CardDemo - Transaction View";
        response.title02 = "View Transaction Details";
    }

    private String mapProgramToRedirect(String program) {
        if (program == null) return "/api/menu";
        switch (program.toUpperCase().trim()) {
            case "COSGN00C": return "/api/auth";
            case "COMEN01C": return "/api/menu";
            case "COTRN00C": return "/api/transactions";
            case "COTRN01C": return "/api/transactions/view";
            case "COTRN02C": return "/api/transactions/add";
            default: return "/api/menu";
        }
    }

    public static class TransactionViewRequest {
        public String tranIdInput;
        public String action;
        public CardDemoCommArea commArea;
    }

    public static class TransactionViewResponse {
        public String title01;
        public String title02;
        public String trnName;
        public String pgmName;
        public String curDate;
        public String curTime;
        public String tranId;
        public String cardNum;
        public String tranTypeCd;
        public int tranCatCd;
        public String tranSource;
        public String tranAmt;
        public String tranDesc;
        public String tranOrigTs;
        public String tranProcTs;
        public long merchantId;
        public String merchantName;
        public String merchantCity;
        public String merchantZip;
        public String errorMsg;
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }

        public ApiResponse(boolean success, String message, Object data, String redirect, CardDemoCommArea commArea) {
            this.success = success;
            this.message = message;
            this.data = data;
            this.redirect = redirect;
            this.commArea = commArea;
        }
    }
}