package com.carddemo.controllers;

import com.carddemo.dto.CardDemoCommArea;
import com.carddemo.dto.TransactionRecord;
import com.carddemo.dto.AccountRecord;
import com.carddemo.dto.CardXrefRecord;
import com.carddemo.dto.CustomerRecord;
import com.carddemo.dto.UserSecurityData;
import com.carddemo.dto.TitleData;
import com.carddemo.dto.DateData;
import com.carddemo.dto.MessageData;


// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:03:04
// Source: AWS CardDemo (Apache 2.0)

import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import jakarta.annotation.PostConstruct;

@RestController
@RequestMapping("/api/transactions")
public class TransactionListController {

    private static final String WS_PGMNAME = "COTRN00C";
    private static final String WS_TRANID = "CT00";
    private static final int PAGE_SIZE = 10;

    private static Map<String, TransactionRecord> transactFile = new LinkedHashMap<>();

    @PostConstruct
    public void initializeData() {
        for (int i = 1; i <= 35; i++) {
            TransactionRecord record = new TransactionRecord();
            record.tranId = String.format("%016d", i);
            record.tranTypeCd = "SA";
            record.tranCatCd = 5010;
            record.tranSource = "POS";
            record.tranDesc = "Sample Transaction " + i;
            record.tranAmt = new BigDecimal("100.00").add(new BigDecimal(i));
            record.tranMerchantId = 1000 + i;
            record.tranMerchantName = "Merchant " + i;
            record.tranMerchantCity = "City" + i;
            record.tranMerchantZip = "1234" + (i % 10);
            record.tranCardNum = "4111111111111111";
            record.tranOrigTs = "2024-01-" + String.format("%02d", (i % 28) + 1) + " 10:30:00";
            record.tranProcTs = "2024-01-" + String.format("%02d", (i % 28) + 1) + " 10:30:05";
            transactFile.put(record.tranId, record);
        }
    }

    @GetMapping
    public ResponseEntity<ApiResponse> listTransactions(
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(required = false) String startTranId) {

        List<TransactionRecord> allTransactions = new ArrayList<>(transactFile.values());
        Collections.sort(allTransactions, Comparator.comparing(t -> t.tranId));

        int startIndex = 0;
        if (startTranId != null && !startTranId.trim().isEmpty()) {
            for (int i = 0; i < allTransactions.size(); i++) {
                if (allTransactions.get(i).tranId.compareTo(startTranId) >= 0) {
                    startIndex = i;
                    break;
                }
            }
        } else {
            startIndex = (page - 1) * PAGE_SIZE;
        }

        if (startIndex >= allTransactions.size()) {
            Map<String, Object> data = new HashMap<>();
            data.put("transactions", Collections.emptyList());
            data.put("pageNum", page);
            data.put("hasNextPage", false);
            data.put("hasPrevPage", page > 1);
            data.put("firstTranId", null);
            data.put("lastTranId", null);
            addHeaderInfo(data);
            return ResponseEntity.ok(new ApiResponse(true, "No transactions found", data));
        }

        int endIndex = Math.min(startIndex + PAGE_SIZE, allTransactions.size());
        List<TransactionRecord> pageTransactions = allTransactions.subList(startIndex, endIndex);

        List<Map<String, Object>> transactionList = new ArrayList<>();
        for (TransactionRecord tran : pageTransactions) {
            Map<String, Object> tranMap = new HashMap<>();
            tranMap.put("tranId", tran.tranId);
            tranMap.put("tranDate", formatTranDate(tran.tranOrigTs));
            tranMap.put("tranDesc", tran.tranDesc);
            tranMap.put("tranAmt", tran.tranAmt);
            transactionList.add(tranMap);
        }

        String firstTranId = pageTransactions.isEmpty() ? null : pageTransactions.get(0).tranId;
        String lastTranId = pageTransactions.isEmpty() ? null : pageTransactions.get(pageTransactions.size() - 1).tranId;
        boolean hasNextPage = endIndex < allTransactions.size();
        boolean hasPrevPage = startIndex > 0;

        Map<String, Object> data = new HashMap<>();
        data.put("transactions", transactionList);
        data.put("pageNum", page);
        data.put("hasNextPage", hasNextPage);
        data.put("hasPrevPage", hasPrevPage);
        data.put("firstTranId", firstTranId);
        data.put("lastTranId", lastTranId);
        addHeaderInfo(data);

        return ResponseEntity.ok(new ApiResponse(true, null, data));
    }

    @PostMapping("/page")
    public ResponseEntity<ApiResponse> handlePaging(@RequestBody PageRequest request) {
        String action = request.action;
        CardDemoCommArea commArea = request.commArea;

        if (commArea == null) {
            commArea = new CardDemoCommArea();
        }

        if ("next".equalsIgnoreCase(action)) {
            return processPageForward(request, commArea);
        } else if ("previous".equalsIgnoreCase(action)) {
            return processPageBackward(request, commArea);
        } else if ("back".equalsIgnoreCase(action)) {
            return returnToPrevScreen(commArea);
        }

        return listTransactions(request.pageNum > 0 ? request.pageNum : 1, request.startTranId);
    }

    @PostMapping("/select")
    public ResponseEntity<ApiResponse> selectTransaction(@RequestBody SelectRequest request) {
        CardDemoCommArea commArea = request.commArea;
        if (commArea == null) {
            commArea = new CardDemoCommArea();
        }

        String selectionFlag = request.selectionFlag;
        String selectedTranId = request.selectedTranId;

        if (selectionFlag == null || selectionFlag.trim().isEmpty() ||
            selectedTranId == null || selectedTranId.trim().isEmpty()) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "No transaction selected", null));
        }

        if (!"S".equalsIgnoreCase(selectionFlag)) {
            return ResponseEntity.badRequest().body(
                new ApiResponse(false, "Invalid selection. Valid value is S", null));
        }

        TransactionRecord tran = transactFile.get(selectedTranId);
        if (tran == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                new ApiResponse(false, "Transaction not found", null));
        }

        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;
        commArea.cdemoToProgram = "COTRN01C";
        commArea.cdemoPgmContext = 0;

        ApiResponse response = new ApiResponse(true, null, null);
        response.redirect = "/api/transactions/" + selectedTranId;
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    @PostMapping("/search")
    public ResponseEntity<ApiResponse> searchTransactions(@RequestBody SearchRequest request) {
        CardDemoCommArea commArea = request.commArea;
        if (commArea == null) {
            commArea = new CardDemoCommArea();
        }

        String tranIdInput = request.tranIdInput;
        
        if (tranIdInput != null && !tranIdInput.trim().isEmpty()) {
            if (!tranIdInput.matches("\\d+")) {
                return ResponseEntity.badRequest().body(
                    new ApiResponse(false, "Tran ID must be Numeric ...", null));
            }
        }

        String startTranId = null;
        if (tranIdInput != null && !tranIdInput.trim().isEmpty()) {
            startTranId = String.format("%016d", Long.parseLong(tranIdInput));
        }

        return listTransactions(1, startTranId);
    }

    private ResponseEntity<ApiResponse> processPageForward(PageRequest request, CardDemoCommArea commArea) {
        String lastTranId = request.lastTranId;
        int currentPage = request.pageNum;

        List<TransactionRecord> allTransactions = new ArrayList<>(transactFile.values());
        Collections.sort(allTransactions, Comparator.comparing(t -> t.tranId));

        int startIndex = 0;
        if (lastTranId != null && !lastTranId.trim().isEmpty()) {
            for (int i = 0; i < allTransactions.size(); i++) {
                if (allTransactions.get(i).tranId.compareTo(lastTranId) > 0) {
                    startIndex = i;
                    break;
                }
                if (i == allTransactions.size() - 1) {
                    startIndex = allTransactions.size();
                }
            }
        }

        if (startIndex >= allTransactions.size()) {
            Map<String, Object> data = new HashMap<>();
            data.put("message", "You are already at the bottom of the page...");
            addHeaderInfo(data);
            return ResponseEntity.ok(new ApiResponse(true, "You are already at the bottom of the page...", data));
        }

        int endIndex = Math.min(startIndex + PAGE_SIZE, allTransactions.size());
        List<TransactionRecord> pageTransactions = allTransactions.subList(startIndex, endIndex);

        List<Map<String, Object>> transactionList = new ArrayList<>();
        for (TransactionRecord tran : pageTransactions) {
            Map<String, Object> tranMap = new HashMap<>();
            tranMap.put("tranId", tran.tranId);
            tranMap.put("tranDate", formatTranDate(tran.tranOrigTs));
            tranMap.put("tranDesc", tran.tranDesc);
            tranMap.put("tranAmt", tran.tranAmt);
            transactionList.add(tranMap);
        }

        String firstTranId = pageTransactions.isEmpty() ? null : pageTransactions.get(0).tranId;
        String newLastTranId = pageTransactions.isEmpty() ? null : pageTransactions.get(pageTransactions.size() - 1).tranId;
        boolean hasNextPage = endIndex < allTransactions.size();

        Map<String, Object> data = new HashMap<>();
        data.put("transactions", transactionList);
        data.put("pageNum", currentPage + 1);
        data.put("hasNextPage", hasNextPage);
        data.put("hasPrevPage", true);
        data.put("firstTranId", firstTranId);
        data.put("lastTranId", newLastTranId);
        addHeaderInfo(data);

        ApiResponse response = new ApiResponse(true, null, data);
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private ResponseEntity<ApiResponse> processPageBackward(PageRequest request, CardDemoCommArea commArea) {
        String firstTranId = request.firstTranId;
        int currentPage = request.pageNum;

        if (currentPage <= 1) {
            Map<String, Object> data = new HashMap<>();
            data.put("message", "You are already at the top of the page...");
            addHeaderInfo(data);
            return ResponseEntity.ok(new ApiResponse(true, "You are already at the top of the page...", data));
        }

        List<TransactionRecord> allTransactions = new ArrayList<>(transactFile.values());
        Collections.sort(allTransactions, Comparator.comparing(t -> t.tranId));

        int endIndex = allTransactions.size();
        if (firstTranId != null && !firstTranId.trim().isEmpty()) {
            for (int i = 0; i < allTransactions.size(); i++) {
                if (allTransactions.get(i).tranId.compareTo(firstTranId) >= 0) {
                    endIndex = i;
                    break;
                }
            }
        }

        int startIndex = Math.max(0, endIndex - PAGE_SIZE);
        List<TransactionRecord> pageTransactions = allTransactions.subList(startIndex, endIndex);

        List<Map<String, Object>> transactionList = new ArrayList<>();
        for (TransactionRecord tran : pageTransactions) {
            Map<String, Object> tranMap = new HashMap<>();
            tranMap.put("tranId", tran.tranId);
            tranMap.put("tranDate", formatTranDate(tran.tranOrigTs));
            tranMap.put("tranDesc", tran.tranDesc);
            tranMap.put("tranAmt", tran.tranAmt);
            transactionList.add(tranMap);
        }

        String newFirstTranId = pageTransactions.isEmpty() ? null : pageTransactions.get(0).tranId;
        String lastTranId = pageTransactions.isEmpty() ? null : pageTransactions.get(pageTransactions.size() - 1).tranId;
        boolean hasPrevPage = startIndex > 0;

        Map<String, Object> data = new HashMap<>();
        data.put("transactions", transactionList);
        data.put("pageNum", currentPage - 1);
        data.put("hasNextPage", true);
        data.put("hasPrevPage", hasPrevPage);
        data.put("firstTranId", newFirstTranId);
        data.put("lastTranId", lastTranId);
        addHeaderInfo(data);

        ApiResponse response = new ApiResponse(true, null, data);
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private ResponseEntity<ApiResponse> returnToPrevScreen(CardDemoCommArea commArea) {
        String toProgram = commArea.cdemoToProgram;
        if (toProgram == null || toProgram.trim().isEmpty()) {
            toProgram = "COMEN01C";
        }

        commArea.cdemoFromTranid = WS_TRANID;
        commArea.cdemoFromProgram = WS_PGMNAME;
        commArea.cdemoPgmContext = 0;

        ApiResponse response = new ApiResponse(true, null, null);
        response.redirect = "/api/menu";
        response.commArea = commArea;
        return ResponseEntity.ok(response);
    }

    private String formatTranDate(String tranOrigTs) {
        if (tranOrigTs == null || tranOrigTs.length() < 10) {
            return "00/00/00";
        }
        try {
            String datePart = tranOrigTs.substring(0, 10);
            String[] parts = datePart.split("-");
            if (parts.length >= 3) {
                String yy = parts[0].length() >= 4 ? parts[0].substring(2) : parts[0];
                String mm = parts[1];
                String dd = parts[2];
                return mm + "/" + dd + "/" + yy;
            }
        } catch (Exception e) {
            return "00/00/00";
        }
        return "00/00/00";
    }

    private void addHeaderInfo(Map<String, Object> data) {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MM/dd/yy");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");

        data.put("currentDate", now.format(dateFormatter));
        data.put("currentTime", now.format(timeFormatter));
        data.put("tranId", WS_TRANID);
        data.put("programName", WS_PGMNAME);
        data.put("title01", "AWS CardDemo Application");
        data.put("title02", "Transaction List");
    }

    public static class PageRequest {
        public String action;
        public int pageNum;
        public String firstTranId;
        public String lastTranId;
        public String startTranId;
        public CardDemoCommArea commArea;
    }

    public static class SelectRequest {
        public String selectionFlag;
        public String selectedTranId;
        public CardDemoCommArea commArea;
    }

    public static class SearchRequest {
        public String tranIdInput;
        public CardDemoCommArea commArea;
    }

    public static class ApiResponse {
        public boolean success;
        public String message;
        public Object data;
        public String redirect;
        public CardDemoCommArea commArea;

        public ApiResponse(boolean success, String message, Object data) {
            this.success = success;
            this.message = message;
            this.data = data;
        }
    }
}