// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:04:30
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.carddemo.dto.AccountRecord;
import java.math.BigDecimal;

class AccountRecordTest {

    private AccountRecord accountRecord;

    @BeforeEach
    void setUp() {
        accountRecord = new AccountRecord();
    }

    @Test
    void testDefaultConstructorInitializesAcctIdToZero() {
        assertEquals(0L, accountRecord.acctId);
    }

    @Test
    void testDefaultConstructorInitializesAcctActiveStatusToEmptyString() {
        assertEquals("", accountRecord.acctActiveStatus);
    }

    @Test
    void testDefaultConstructorInitializesAcctCurrBalToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCurrBal);
    }

    @Test
    void testDefaultConstructorInitializesAcctCreditLimitToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCreditLimit);
    }

    @Test
    void testDefaultConstructorInitializesAcctCashCreditLimitToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCashCreditLimit);
    }

    @Test
    void testDefaultConstructorInitializesAcctOpenDateToEmptyString() {
        assertEquals("", accountRecord.acctOpenDate);
    }

    @Test
    void testDefaultConstructorInitializesAcctExpiraionDateToEmptyString() {
        assertEquals("", accountRecord.acctExpiraionDate);
    }

    @Test
    void testDefaultConstructorInitializesAcctReissueDateToEmptyString() {
        assertEquals("", accountRecord.acctReissueDate);
    }

    @Test
    void testDefaultConstructorInitializesAcctCurrCycCreditToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCurrCycCredit);
    }

    @Test
    void testDefaultConstructorInitializesAcctCurrCycDebitToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCurrCycDebit);
    }

    @Test
    void testDefaultConstructorInitializesAcctAddrZipToEmptyString() {
        assertEquals("", accountRecord.acctAddrZip);
    }

    @Test
    void testDefaultConstructorInitializesAcctGroupIdToEmptyString() {
        assertEquals("", accountRecord.acctGroupId);
    }

    @Test
    void testAcctIdFieldAssignmentAndRetrieval() {
        accountRecord.acctId = 12345678901L;
        assertEquals(12345678901L, accountRecord.acctId);
    }

    @Test
    void testAcctActiveStatusFieldAssignmentAndRetrieval() {
        accountRecord.acctActiveStatus = "Y";
        assertEquals("Y", accountRecord.acctActiveStatus);
    }

    @Test
    void testAcctCurrBalFieldAssignmentAndRetrieval() {
        BigDecimal balance = new BigDecimal("1500.75");
        accountRecord.acctCurrBal = balance;
        assertEquals(balance, accountRecord.acctCurrBal);
    }

    @Test
    void testAcctCreditLimitFieldAssignmentAndRetrieval() {
        BigDecimal creditLimit = new BigDecimal("10000.00");
        accountRecord.acctCreditLimit = creditLimit;
        assertEquals(creditLimit, accountRecord.acctCreditLimit);
    }

    @Test
    void testAcctCashCreditLimitFieldAssignmentAndRetrieval() {
        BigDecimal cashCreditLimit = new BigDecimal("5000.00");
        accountRecord.acctCashCreditLimit = cashCreditLimit;
        assertEquals(cashCreditLimit, accountRecord.acctCashCreditLimit);
    }

    @Test
    void testAcctOpenDateFieldAssignmentAndRetrieval() {
        accountRecord.acctOpenDate = "2020-01-15";
        assertEquals("2020-01-15", accountRecord.acctOpenDate);
    }

    @Test
    void testAcctExpiraionDateFieldAssignmentAndRetrieval() {
        accountRecord.acctExpiraionDate = "2025-12-31";
        assertEquals("2025-12-31", accountRecord.acctExpiraionDate);
    }

    @Test
    void testAcctReissueDateFieldAssignmentAndRetrieval() {
        accountRecord.acctReissueDate = "2023-06-01";
        assertEquals("2023-06-01", accountRecord.acctReissueDate);
    }

    @Test
    void testAcctCurrCycCreditFieldAssignmentAndRetrieval() {
        BigDecimal credit = new BigDecimal("250.50");
        accountRecord.acctCurrCycCredit = credit;
        assertEquals(credit, accountRecord.acctCurrCycCredit);
    }

    @Test
    void testAcctCurrCycDebitFieldAssignmentAndRetrieval() {
        BigDecimal debit = new BigDecimal("175.25");
        accountRecord.acctCurrCycDebit = debit;
        assertEquals(debit, accountRecord.acctCurrCycDebit);
    }

    @Test
    void testAcctAddrZipFieldAssignmentAndRetrieval() {
        accountRecord.acctAddrZip = "12345-6789";
        assertEquals("12345-6789", accountRecord.acctAddrZip);
    }

    @Test
    void testAcctGroupIdFieldAssignmentAndRetrieval() {
        accountRecord.acctGroupId = "GRP001";
        assertEquals("GRP001", accountRecord.acctGroupId);
    }

    @Test
    void testToStringContainsAcctId() {
        accountRecord.acctId = 999L;
        String result = accountRecord.toString();
        assertTrue(result.contains("acctId=999"));
    }

    @Test
    void testToStringContainsAcctActiveStatus() {
        accountRecord.acctActiveStatus = "N";
        String result = accountRecord.toString();
        assertTrue(result.contains("acctActiveStatus='N'"));
    }

    @Test
    void testToStringContainsAcctCurrBal() {
        accountRecord.acctCurrBal = new BigDecimal("100.00");
        String result = accountRecord.toString();
        assertTrue(result.contains("acctCurrBal=100.00"));
    }

    @Test
    void testToStringContainsAllFields() {
        accountRecord.acctId = 123L;
        accountRecord.acctActiveStatus = "Y";
        accountRecord.acctCurrBal = new BigDecimal("500.00");
        accountRecord.acctCreditLimit = new BigDecimal("5000.00");
        accountRecord.acctCashCreditLimit = new BigDecimal("2000.00");
        accountRecord.acctOpenDate = "2021-05-10";
        accountRecord.acctExpiraionDate = "2026-05-10";
        accountRecord.acctReissueDate = "2024-05-10";
        accountRecord.acctCurrCycCredit = new BigDecimal("100.00");
        accountRecord.acctCurrCycDebit = new BigDecimal("50.00");
        accountRecord.acctAddrZip = "90210";
        accountRecord.acctGroupId = "GRPA";

        String result = accountRecord.toString();

        assertTrue(result.contains("AccountRecord{"));
        assertTrue(result.contains("acctId=123"));
        assertTrue(result.contains("acctActiveStatus='Y'"));
        assertTrue(result.contains("acctCurrBal=500.00"));
        assertTrue(result.contains("acctCreditLimit=5000.00"));
        assertTrue(result.contains("acctCashCreditLimit=2000.00"));
        assertTrue(result.contains("acctOpenDate='2021-05-10'"));
        assertTrue(result.contains("acctExpiraionDate='2026-05-10'"));
        assertTrue(result.contains("acctReissueDate='2024-05-10'"));
        assertTrue(result.contains("acctCurrCycCredit=100.00"));
        assertTrue(result.contains("acctCurrCycDebit=50.00"));
        assertTrue(result.contains("acctAddrZip='90210'"));
        assertTrue(result.contains("acctGroupId='GRPA'"));
    }

    @Test
    void testLargeAcctIdValue() {
        accountRecord.acctId = Long.MAX_VALUE;
        assertEquals(Long.MAX_VALUE, accountRecord.acctId);
    }

    @Test
    void testNegativeAcctCurrBal() {
        BigDecimal negativeBalance = new BigDecimal("-500.00");
        accountRecord.acctCurrBal = negativeBalance;
        assertEquals(negativeBalance, accountRecord.acctCurrBal);
    }

    @Test
    void testHighPrecisionBigDecimal() {
        BigDecimal highPrecision = new BigDecimal("12345.6789012345");
        accountRecord.acctCurrBal = highPrecision;
        assertEquals(highPrecision, accountRecord.acctCurrBal);
    }
}