// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:03:34
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.carddemo.dto.MessageData;

class MessageDataTest {

    private MessageData messageData;

    @BeforeEach
    void setUp() {
        messageData = new MessageData();
    }

    @Test
    void testDefaultConstructorInitializesThankYouMessage() {
        assertEquals("Thank you for using CardDemo application...      ", messageData.ccdaMsgThankYou);
    }

    @Test
    void testDefaultConstructorInitializesInvalidKeyMessage() {
        assertEquals("Invalid key pressed. Please see below...         ", messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testFieldAssignmentCcdaMsgThankYou() {
        messageData.ccdaMsgThankYou = "Custom thank you message";
        assertEquals("Custom thank you message", messageData.ccdaMsgThankYou);
    }

    @Test
    void testFieldAssignmentCcdaMsgInvalidKey() {
        messageData.ccdaMsgInvalidKey = "Custom invalid key message";
        assertEquals("Custom invalid key message", messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testFieldAssignmentToNull() {
        messageData.ccdaMsgThankYou = null;
        messageData.ccdaMsgInvalidKey = null;
        assertNull(messageData.ccdaMsgThankYou);
        assertNull(messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testFieldAssignmentToEmptyString() {
        messageData.ccdaMsgThankYou = "";
        messageData.ccdaMsgInvalidKey = "";
        assertEquals("", messageData.ccdaMsgThankYou);
        assertEquals("", messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testToStringContainsThankYouMessage() {
        String result = messageData.toString();
        assertTrue(result.contains("ccdaMsgThankYou='Thank you for using CardDemo application...      '"));
    }

    @Test
    void testToStringContainsInvalidKeyMessage() {
        String result = messageData.toString();
        assertTrue(result.contains("ccdaMsgInvalidKey='Invalid key pressed. Please see below...         '"));
    }

    @Test
    void testToStringFormat() {
        String result = messageData.toString();
        assertTrue(result.startsWith("MessageData{"));
        assertTrue(result.endsWith("}"));
    }

    @Test
    void testToStringWithCustomValues() {
        messageData.ccdaMsgThankYou = "Thanks!";
        messageData.ccdaMsgInvalidKey = "Invalid!";
        String result = messageData.toString();
        assertTrue(result.contains("ccdaMsgThankYou='Thanks!'"));
        assertTrue(result.contains("ccdaMsgInvalidKey='Invalid!'"));
    }

    @Test
    void testMultipleInstances() {
        MessageData messageData1 = new MessageData();
        MessageData messageData2 = new MessageData();
        
        messageData1.ccdaMsgThankYou = "Modified";
        
        assertNotEquals(messageData1.ccdaMsgThankYou, messageData2.ccdaMsgThankYou);
        assertEquals("Thank you for using CardDemo application...      ", messageData2.ccdaMsgThankYou);
    }
}