// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:05:54
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import com.carddemo.dto.TransactionRecord;
import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;

class TransactionRecordTest {

    private TransactionRecord transactionRecord;

    @BeforeEach
    void setUp() {
        transactionRecord = new TransactionRecord();
    }

    @Test
    void testDefaultConstructorInitializesFieldsToDefaults() {
        assertEquals("", transactionRecord.tranId);
        assertEquals("", transactionRecord.tranTypeCd);
        assertEquals(0, transactionRecord.tranCatCd);
        assertEquals("", transactionRecord.tranSource);
        assertEquals("", transactionRecord.tranDesc);
        assertEquals(BigDecimal.ZERO, transactionRecord.tranAmt);
        assertEquals(0L, transactionRecord.tranMerchantId);
        assertEquals("", transactionRecord.tranMerchantName);
        assertEquals("", transactionRecord.tranMerchantCity);
        assertEquals("", transactionRecord.tranMerchantZip);
        assertEquals("", transactionRecord.tranCardNum);
        assertEquals("", transactionRecord.tranOrigTs);
        assertEquals("", transactionRecord.tranProcTs);
    }

    @Test
    void testTranIdFieldAssignmentAndRetrieval() {
        transactionRecord.tranId = "TXN123456";
        assertEquals("TXN123456", transactionRecord.tranId);
    }

    @Test
    void testTranTypeCdFieldAssignmentAndRetrieval() {
        transactionRecord.tranTypeCd = "PUR";
        assertEquals("PUR", transactionRecord.tranTypeCd);
    }

    @Test
    void testTranCatCdFieldAssignmentAndRetrieval() {
        transactionRecord.tranCatCd = 5;
        assertEquals(5, transactionRecord.tranCatCd);
    }

    @Test
    void testTranSourceFieldAssignmentAndRetrieval() {
        transactionRecord.tranSource = "ONLINE";
        assertEquals("ONLINE", transactionRecord.tranSource);
    }

    @Test
    void testTranDescFieldAssignmentAndRetrieval() {
        transactionRecord.tranDesc = "Purchase at Store ABC";
        assertEquals("Purchase at Store ABC", transactionRecord.tranDesc);
    }

    @Test
    void testTranAmtFieldAssignmentAndRetrieval() {
        transactionRecord.tranAmt = new BigDecimal("125.99");
        assertEquals(new BigDecimal("125.99"), transactionRecord.tranAmt);
    }

    @Test
    void testTranMerchantIdFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantId = 987654321L;
        assertEquals(987654321L, transactionRecord.tranMerchantId);
    }

    @Test
    void testTranMerchantNameFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantName = "Acme Corporation";
        assertEquals("Acme Corporation", transactionRecord.tranMerchantName);
    }

    @Test
    void testTranMerchantCityFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantCity = "New York";
        assertEquals("New York", transactionRecord.tranMerchantCity);
    }

    @Test
    void testTranMerchantZipFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantZip = "10001";
        assertEquals("10001", transactionRecord.tranMerchantZip);
    }

    @Test
    void testTranCardNumFieldAssignmentAndRetrieval() {
        transactionRecord.tranCardNum = "4111111111111111";
        assertEquals("4111111111111111", transactionRecord.tranCardNum);
    }

    @Test
    void testTranOrigTsFieldAssignmentAndRetrieval() {
        transactionRecord.tranOrigTs = "2024-01-15T10:30:00";
        assertEquals("2024-01-15T10:30:00", transactionRecord.tranOrigTs);
    }

    @Test
    void testTranProcTsFieldAssignmentAndRetrieval() {
        transactionRecord.tranProcTs = "2024-01-15T10:30:05";
        assertEquals("2024-01-15T10:30:05", transactionRecord.tranProcTs);
    }

    @Test
    void testToStringContainsAllFields() {
        transactionRecord.tranId = "TXN001";
        transactionRecord.tranTypeCd = "PUR";
        transactionRecord.tranCatCd = 3;
        transactionRecord.tranSource = "POS";
        transactionRecord.tranDesc = "Coffee Shop";
        transactionRecord.tranAmt = new BigDecimal("5.50");
        transactionRecord.tranMerchantId = 12345L;
        transactionRecord.tranMerchantName = "Java Cafe";
        transactionRecord.tranMerchantCity = "Seattle";
        transactionRecord.tranMerchantZip = "98101";
        transactionRecord.tranCardNum = "4222222222222222";
        transactionRecord.tranOrigTs = "2024-01-10T08:00:00";
        transactionRecord.tranProcTs = "2024-01-10T08:00:01";

        String result = transactionRecord.toString();

        assertTrue(result.contains("tranId='TXN001'"));
        assertTrue(result.contains("tranTypeCd='PUR'"));
        assertTrue(result.contains("tranCatCd=3"));
        assertTrue(result.contains("tranSource='POS'"));
        assertTrue(result.contains("tranDesc='Coffee Shop'"));
        assertTrue(result.contains("tranAmt=5.50"));
        assertTrue(result.contains("tranMerchantId=12345"));
        assertTrue(result.contains("tranMerchantName='Java Cafe'"));
        assertTrue(result.contains("tranMerchantCity='Seattle'"));
        assertTrue(result.contains("tranMerchantZip='98101'"));
        assertTrue(result.contains("tranCardNum='4222222222222222'"));
        assertTrue(result.contains("tranOrigTs='2024-01-10T08:00:00'"));
        assertTrue(result.contains("tranProcTs='2024-01-10T08:00:01'"));
    }

    @Test
    void testToStringWithDefaultValues() {
        String result = transactionRecord.toString();

        assertTrue(result.contains("tranId=''"));
        assertTrue(result.contains("tranTypeCd=''"));
        assertTrue(result.contains("tranCatCd=0"));
        assertTrue(result.contains("tranSource=''"));
        assertTrue(result.contains("tranDesc=''"));
        assertTrue(result.contains("tranAmt=0"));
        assertTrue(result.contains("tranMerchantId=0"));
        assertTrue(result.contains("tranMerchantName=''"));
        assertTrue(result.contains("tranMerchantCity=''"));
        assertTrue(result.contains("tranMerchantZip=''"));
        assertTrue(result.contains("tranCardNum=''"));
        assertTrue(result.contains("tranOrigTs=''"));
        assertTrue(result.contains("tranProcTs=''"));
    }

    @Test
    void testTranAmtWithLargeValue() {
        transactionRecord.tranAmt = new BigDecimal("999999999.99");
        assertEquals(new BigDecimal("999999999.99"), transactionRecord.tranAmt);
    }

    @Test
    void testTranAmtWithNegativeValue() {
        transactionRecord.tranAmt = new BigDecimal("-50.00");
        assertEquals(new BigDecimal("-50.00"), transactionRecord.tranAmt);
    }

    @Test
    void testTranMerchantIdWithLargeValue() {
        transactionRecord.tranMerchantId = Long.MAX_VALUE;
        assertEquals(Long.MAX_VALUE, transactionRecord.tranMerchantId);
    }

    @Test
    void testTranCatCdWithNegativeValue() {
        transactionRecord.tranCatCd = -1;
        assertEquals(-1, transactionRecord.tranCatCd);
    }
}