// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:03:58
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.carddemo.dto.UserSecurityData;

class UserSecurityDataTest {

    private UserSecurityData userData;

    @BeforeEach
    void setUp() {
        userData = new UserSecurityData();
    }

    @Test
    void testDefaultConstructorInitializesFieldsToEmptyStrings() {
        assertEquals("", userData.secUsrId);
        assertEquals("", userData.secUsrFname);
        assertEquals("", userData.secUsrLname);
        assertEquals("", userData.secUsrPwd);
        assertEquals("", userData.secUsrType);
    }

    @Test
    void testSecUsrIdFieldAssignmentAndRetrieval() {
        userData.secUsrId = "USR001";
        assertEquals("USR001", userData.secUsrId);
    }

    @Test
    void testSecUsrFnameFieldAssignmentAndRetrieval() {
        userData.secUsrFname = "John";
        assertEquals("John", userData.secUsrFname);
    }

    @Test
    void testSecUsrLnameFieldAssignmentAndRetrieval() {
        userData.secUsrLname = "Doe";
        assertEquals("Doe", userData.secUsrLname);
    }

    @Test
    void testSecUsrPwdFieldAssignmentAndRetrieval() {
        userData.secUsrPwd = "securePassword123";
        assertEquals("securePassword123", userData.secUsrPwd);
    }

    @Test
    void testSecUsrTypeFieldAssignmentAndRetrieval() {
        userData.secUsrType = "ADMIN";
        assertEquals("ADMIN", userData.secUsrType);
    }

    @Test
    void testAllFieldsCanBeSetAndRetrieved() {
        userData.secUsrId = "USR002";
        userData.secUsrFname = "Jane";
        userData.secUsrLname = "Smith";
        userData.secUsrPwd = "password456";
        userData.secUsrType = "USER";

        assertEquals("USR002", userData.secUsrId);
        assertEquals("Jane", userData.secUsrFname);
        assertEquals("Smith", userData.secUsrLname);
        assertEquals("password456", userData.secUsrPwd);
        assertEquals("USER", userData.secUsrType);
    }

    @Test
    void testToStringContainsAllFields() {
        userData.secUsrId = "USR003";
        userData.secUsrFname = "Bob";
        userData.secUsrLname = "Wilson";
        userData.secUsrPwd = "pwd789";
        userData.secUsrType = "GUEST";

        String result = userData.toString();

        assertTrue(result.contains("secUsrId='USR003'"));
        assertTrue(result.contains("secUsrFname='Bob'"));
        assertTrue(result.contains("secUsrLname='Wilson'"));
        assertTrue(result.contains("secUsrPwd='pwd789'"));
        assertTrue(result.contains("secUsrType='GUEST'"));
        assertTrue(result.startsWith("UserSecurityData{"));
        assertTrue(result.endsWith("}"));
    }

    @Test
    void testToStringWithDefaultValues() {
        String result = userData.toString();

        assertTrue(result.contains("secUsrId=''"));
        assertTrue(result.contains("secUsrFname=''"));
        assertTrue(result.contains("secUsrLname=''"));
        assertTrue(result.contains("secUsrPwd=''"));
        assertTrue(result.contains("secUsrType=''"));
    }

    @Test
    void testFieldsCanBeSetToNull() {
        userData.secUsrId = null;
        userData.secUsrFname = null;
        userData.secUsrLname = null;
        userData.secUsrPwd = null;
        userData.secUsrType = null;

        assertNull(userData.secUsrId);
        assertNull(userData.secUsrFname);
        assertNull(userData.secUsrLname);
        assertNull(userData.secUsrPwd);
        assertNull(userData.secUsrType);
    }

    @Test
    void testFieldsCanHandleSpecialCharacters() {
        userData.secUsrId = "USR!@#$%";
        userData.secUsrFname = "José";
        userData.secUsrLname = "O'Brien";
        userData.secUsrPwd = "p@ss$w0rd!";
        userData.secUsrType = "SUPER_USER";

        assertEquals("USR!@#$%", userData.secUsrId);
        assertEquals("José", userData.secUsrFname);
        assertEquals("O'Brien", userData.secUsrLname);
        assertEquals("p@ss$w0rd!", userData.secUsrPwd);
        assertEquals("SUPER_USER", userData.secUsrType);
    }

    @Test
    void testFieldsCanHandleEmptyStrings() {
        userData.secUsrId = "";
        userData.secUsrFname = "";
        userData.secUsrLname = "";
        userData.secUsrPwd = "";
        userData.secUsrType = "";

        assertEquals("", userData.secUsrId);
        assertEquals("", userData.secUsrFname);
        assertEquals("", userData.secUsrLname);
        assertEquals("", userData.secUsrPwd);
        assertEquals("", userData.secUsrType);
    }

    @Test
    void testMultipleInstancesAreIndependent() {
        UserSecurityData userData1 = new UserSecurityData();
        UserSecurityData userData2 = new UserSecurityData();

        userData1.secUsrId = "USR001";
        userData2.secUsrId = "USR002";

        assertEquals("USR001", userData1.secUsrId);
        assertEquals("USR002", userData2.secUsrId);
        assertNotEquals(userData1.secUsrId, userData2.secUsrId);
    }
}