package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:59:35
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigDecimal;

class AccountRecordTest {

    private AccountRecord accountRecord;

    @BeforeEach
    void setUp() {
        accountRecord = new AccountRecord();
    }

    @Test
    void testDefaultConstructorInitializesAcctIdToZero() {
        assertEquals(0L, accountRecord.acctId);
    }

    @Test
    void testDefaultConstructorInitializesAcctActiveStatusToEmptyString() {
        assertEquals("", accountRecord.acctActiveStatus);
    }

    @Test
    void testDefaultConstructorInitializesAcctCurrBalToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCurrBal);
    }

    @Test
    void testDefaultConstructorInitializesAcctCreditLimitToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCreditLimit);
    }

    @Test
    void testDefaultConstructorInitializesAcctCashCreditLimitToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCashCreditLimit);
    }

    @Test
    void testDefaultConstructorInitializesAcctOpenDateToEmptyString() {
        assertEquals("", accountRecord.acctOpenDate);
    }

    @Test
    void testDefaultConstructorInitializesAcctExpiraionDateToEmptyString() {
        assertEquals("", accountRecord.acctExpiraionDate);
    }

    @Test
    void testDefaultConstructorInitializesAcctReissueDateToEmptyString() {
        assertEquals("", accountRecord.acctReissueDate);
    }

    @Test
    void testDefaultConstructorInitializesAcctCurrCycCreditToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCurrCycCredit);
    }

    @Test
    void testDefaultConstructorInitializesAcctCurrCycDebitToZero() {
        assertEquals(BigDecimal.ZERO, accountRecord.acctCurrCycDebit);
    }

    @Test
    void testDefaultConstructorInitializesAcctAddrZipToEmptyString() {
        assertEquals("", accountRecord.acctAddrZip);
    }

    @Test
    void testDefaultConstructorInitializesAcctGroupIdToEmptyString() {
        assertEquals("", accountRecord.acctGroupId);
    }

    @Test
    void testAcctIdFieldAssignmentAndRetrieval() {
        accountRecord.acctId = 12345L;
        assertEquals(12345L, accountRecord.acctId);
    }

    @Test
    void testAcctActiveStatusFieldAssignmentAndRetrieval() {
        accountRecord.acctActiveStatus = "ACTIVE";
        assertEquals("ACTIVE", accountRecord.acctActiveStatus);
    }

    @Test
    void testAcctCurrBalFieldAssignmentAndRetrieval() {
        BigDecimal balance = new BigDecimal("1500.50");
        accountRecord.acctCurrBal = balance;
        assertEquals(balance, accountRecord.acctCurrBal);
    }

    @Test
    void testAcctCreditLimitFieldAssignmentAndRetrieval() {
        BigDecimal creditLimit = new BigDecimal("5000.00");
        accountRecord.acctCreditLimit = creditLimit;
        assertEquals(creditLimit, accountRecord.acctCreditLimit);
    }

    @Test
    void testAcctCashCreditLimitFieldAssignmentAndRetrieval() {
        BigDecimal cashCreditLimit = new BigDecimal("2000.00");
        accountRecord.acctCashCreditLimit = cashCreditLimit;
        assertEquals(cashCreditLimit, accountRecord.acctCashCreditLimit);
    }

    @Test
    void testAcctOpenDateFieldAssignmentAndRetrieval() {
        accountRecord.acctOpenDate = "2023-01-15";
        assertEquals("2023-01-15", accountRecord.acctOpenDate);
    }

    @Test
    void testAcctExpiraionDateFieldAssignmentAndRetrieval() {
        accountRecord.acctExpiraionDate = "2028-01-15";
        assertEquals("2028-01-15", accountRecord.acctExpiraionDate);
    }

    @Test
    void testAcctReissueDateFieldAssignmentAndRetrieval() {
        accountRecord.acctReissueDate = "2025-01-15";
        assertEquals("2025-01-15", accountRecord.acctReissueDate);
    }

    @Test
    void testAcctCurrCycCreditFieldAssignmentAndRetrieval() {
        BigDecimal cycCredit = new BigDecimal("300.00");
        accountRecord.acctCurrCycCredit = cycCredit;
        assertEquals(cycCredit, accountRecord.acctCurrCycCredit);
    }

    @Test
    void testAcctCurrCycDebitFieldAssignmentAndRetrieval() {
        BigDecimal cycDebit = new BigDecimal("150.75");
        accountRecord.acctCurrCycDebit = cycDebit;
        assertEquals(cycDebit, accountRecord.acctCurrCycDebit);
    }

    @Test
    void testAcctAddrZipFieldAssignmentAndRetrieval() {
        accountRecord.acctAddrZip = "12345";
        assertEquals("12345", accountRecord.acctAddrZip);
    }

    @Test
    void testAcctGroupIdFieldAssignmentAndRetrieval() {
        accountRecord.acctGroupId = "GRP001";
        assertEquals("GRP001", accountRecord.acctGroupId);
    }

    @Test
    void testToStringContainsAllFields() {
        accountRecord.acctId = 99999L;
        accountRecord.acctActiveStatus = "ACTIVE";
        accountRecord.acctCurrBal = new BigDecimal("1000.00");
        accountRecord.acctCreditLimit = new BigDecimal("5000.00");
        accountRecord.acctCashCreditLimit = new BigDecimal("2000.00");
        accountRecord.acctOpenDate = "2023-01-01";
        accountRecord.acctExpiraionDate = "2028-01-01";
        accountRecord.acctReissueDate = "2025-01-01";
        accountRecord.acctCurrCycCredit = new BigDecimal("200.00");
        accountRecord.acctCurrCycDebit = new BigDecimal("100.00");
        accountRecord.acctAddrZip = "54321";
        accountRecord.acctGroupId = "GRP002";

        String result = accountRecord.toString();

        assertTrue(result.contains("acctId=99999"));
        assertTrue(result.contains("acctActiveStatus='ACTIVE'"));
        assertTrue(result.contains("acctCurrBal=1000.00"));
        assertTrue(result.contains("acctCreditLimit=5000.00"));
        assertTrue(result.contains("acctCashCreditLimit=2000.00"));
        assertTrue(result.contains("acctOpenDate='2023-01-01'"));
        assertTrue(result.contains("acctExpiraionDate='2028-01-01'"));
        assertTrue(result.contains("acctReissueDate='2025-01-01'"));
        assertTrue(result.contains("acctCurrCycCredit=200.00"));
        assertTrue(result.contains("acctCurrCycDebit=100.00"));
        assertTrue(result.contains("acctAddrZip='54321'"));
        assertTrue(result.contains("acctGroupId='GRP002'"));
    }

    @Test
    void testToStringWithDefaultValues() {
        String result = accountRecord.toString();

        assertNotNull(result);
        assertTrue(result.startsWith("AccountRecord{"));
        assertTrue(result.endsWith("}"));
        assertTrue(result.contains("acctId=0"));
        assertTrue(result.contains("acctActiveStatus=''"));
    }
}