package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:59:53
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class CardXrefRecordTest {

    private CardXrefRecord cardXrefRecord;

    @BeforeEach
    void setUp() {
        cardXrefRecord = new CardXrefRecord();
    }

    @Test
    void testDefaultConstructorInitializesXrefCardNumToEmptyString() {
        assertEquals("", cardXrefRecord.xrefCardNum);
    }

    @Test
    void testDefaultConstructorInitializesXrefCustIdToZero() {
        assertEquals(0L, cardXrefRecord.xrefCustId);
    }

    @Test
    void testDefaultConstructorInitializesXrefAcctIdToZero() {
        assertEquals(0L, cardXrefRecord.xrefAcctId);
    }

    @Test
    void testXrefCardNumFieldAssignmentAndRetrieval() {
        String expectedCardNum = "1234567890123456";
        cardXrefRecord.xrefCardNum = expectedCardNum;
        assertEquals(expectedCardNum, cardXrefRecord.xrefCardNum);
    }

    @Test
    void testXrefCustIdFieldAssignmentAndRetrieval() {
        long expectedCustId = 12345L;
        cardXrefRecord.xrefCustId = expectedCustId;
        assertEquals(expectedCustId, cardXrefRecord.xrefCustId);
    }

    @Test
    void testXrefAcctIdFieldAssignmentAndRetrieval() {
        long expectedAcctId = 67890L;
        cardXrefRecord.xrefAcctId = expectedAcctId;
        assertEquals(expectedAcctId, cardXrefRecord.xrefAcctId);
    }

    @Test
    void testToStringWithDefaultValues() {
        String result = cardXrefRecord.toString();
        assertTrue(result.contains("xrefCardNum=''"));
        assertTrue(result.contains("xrefCustId=0"));
        assertTrue(result.contains("xrefAcctId=0"));
    }

    @Test
    void testToStringWithAssignedValues() {
        cardXrefRecord.xrefCardNum = "9876543210987654";
        cardXrefRecord.xrefCustId = 111L;
        cardXrefRecord.xrefAcctId = 222L;

        String result = cardXrefRecord.toString();
        assertTrue(result.contains("xrefCardNum='9876543210987654'"));
        assertTrue(result.contains("xrefCustId=111"));
        assertTrue(result.contains("xrefAcctId=222"));
    }

    @Test
    void testMultipleFieldAssignments() {
        cardXrefRecord.xrefCardNum = "CARD001";
        cardXrefRecord.xrefCustId = 100L;
        cardXrefRecord.xrefAcctId = 200L;

        assertEquals("CARD001", cardXrefRecord.xrefCardNum);
        assertEquals(100L, cardXrefRecord.xrefCustId);
        assertEquals(200L, cardXrefRecord.xrefAcctId);

        cardXrefRecord.xrefCardNum = "CARD002";
        cardXrefRecord.xrefCustId = 300L;
        cardXrefRecord.xrefAcctId = 400L;

        assertEquals("CARD002", cardXrefRecord.xrefCardNum);
        assertEquals(300L, cardXrefRecord.xrefCustId);
        assertEquals(400L, cardXrefRecord.xrefAcctId);
    }
}