package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:57:28
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class CardDemoCommAreaTest {

    private CardDemoCommArea commArea;

    @BeforeEach
    void setUp() {
        commArea = new CardDemoCommArea();
    }

    @Test
    void testDefaultConstructorInitializesStringFieldsToEmptyString() {
        assertEquals("", commArea.cdemoFromTranid);
        assertEquals("", commArea.cdemoFromProgram);
        assertEquals("", commArea.cdemoToTranid);
        assertEquals("", commArea.cdemoToProgram);
        assertEquals("", commArea.cdemoUserId);
        assertEquals("", commArea.cdemoUserType);
        assertEquals("", commArea.cdemoCustFname);
        assertEquals("", commArea.cdemoCustMname);
        assertEquals("", commArea.cdemoCustLname);
        assertEquals("", commArea.cdemoAcctStatus);
        assertEquals("", commArea.cdemoLastMap);
        assertEquals("", commArea.cdemoLastMapset);
    }

    @Test
    void testDefaultConstructorInitializesNumericFieldsToZero() {
        assertEquals(0, commArea.cdemoPgmContext);
        assertEquals(0L, commArea.cdemoCustId);
        assertEquals(0L, commArea.cdemoAcctId);
        assertEquals(0L, commArea.cdemoCardNum);
    }

    @Test
    void testFieldAssignmentAndRetrieval() {
        commArea.cdemoFromTranid = "TRAN1";
        commArea.cdemoFromProgram = "PROG1";
        commArea.cdemoToTranid = "TRAN2";
        commArea.cdemoToProgram = "PROG2";
        commArea.cdemoUserId = "USER001";
        commArea.cdemoUserType = "A";
        commArea.cdemoPgmContext = 1;
        commArea.cdemoCustId = 12345L;
        commArea.cdemoCustFname = "John";
        commArea.cdemoCustMname = "M";
        commArea.cdemoCustLname = "Doe";
        commArea.cdemoAcctId = 67890L;
        commArea.cdemoAcctStatus = "ACTIVE";
        commArea.cdemoCardNum = 1234567890123456L;
        commArea.cdemoLastMap = "MAP1";
        commArea.cdemoLastMapset = "MAPSET1";

        assertEquals("TRAN1", commArea.cdemoFromTranid);
        assertEquals("PROG1", commArea.cdemoFromProgram);
        assertEquals("TRAN2", commArea.cdemoToTranid);
        assertEquals("PROG2", commArea.cdemoToProgram);
        assertEquals("USER001", commArea.cdemoUserId);
        assertEquals("A", commArea.cdemoUserType);
        assertEquals(1, commArea.cdemoPgmContext);
        assertEquals(12345L, commArea.cdemoCustId);
        assertEquals("John", commArea.cdemoCustFname);
        assertEquals("M", commArea.cdemoCustMname);
        assertEquals("Doe", commArea.cdemoCustLname);
        assertEquals(67890L, commArea.cdemoAcctId);
        assertEquals("ACTIVE", commArea.cdemoAcctStatus);
        assertEquals(1234567890123456L, commArea.cdemoCardNum);
        assertEquals("MAP1", commArea.cdemoLastMap);
        assertEquals("MAPSET1", commArea.cdemoLastMapset);
    }

    @Test
    void testIsAdminReturnsTrueForAdminUserType() {
        commArea.cdemoUserType = "A";
        assertTrue(commArea.isAdmin());
    }

    @Test
    void testIsAdminReturnsTrueForAdminUserTypeWithWhitespace() {
        commArea.cdemoUserType = "A ";
        assertTrue(commArea.isAdmin());
    }

    @Test
    void testIsAdminReturnsFalseForNonAdminUserType() {
        commArea.cdemoUserType = "U";
        assertFalse(commArea.isAdmin());
    }

    @Test
    void testIsAdminReturnsFalseForNullUserType() {
        commArea.cdemoUserType = null;
        assertFalse(commArea.isAdmin());
    }

    @Test
    void testIsRegularUserReturnsTrueForUserType() {
        commArea.cdemoUserType = "U";
        assertTrue(commArea.isRegularUser());
    }

    @Test
    void testIsRegularUserReturnsTrueForUserTypeWithWhitespace() {
        commArea.cdemoUserType = "U ";
        assertTrue(commArea.isRegularUser());
    }

    @Test
    void testIsRegularUserReturnsFalseForAdminUserType() {
        commArea.cdemoUserType = "A";
        assertFalse(commArea.isRegularUser());
    }

    @Test
    void testIsRegularUserReturnsFalseForNullUserType() {
        commArea.cdemoUserType = null;
        assertFalse(commArea.isRegularUser());
    }

    @Test
    void testIsPgmEnterReturnsTrueForContextZero() {
        commArea.cdemoPgmContext = 0;
        assertTrue(commArea.isPgmEnter());
    }

    @Test
    void testIsPgmEnterReturnsFalseForContextOne() {
        commArea.cdemoPgmContext = 1;
        assertFalse(commArea.isPgmEnter());
    }

    @Test
    void testIsPgmReenterReturnsTrueForContextOne() {
        commArea.cdemoPgmContext = 1;
        assertTrue(commArea.isPgmReenter());
    }

    @Test
    void testIsPgmReenterReturnsFalseForContextZero() {
        commArea.cdemoPgmContext = 0;
        assertFalse(commArea.isPgmReenter());
    }

    @Test
    void testConstantsHaveCorrectValues() {
        assertEquals("A", CardDemoCommArea.CDEMO_USRTYP_ADMIN);
        assertEquals("U", CardDemoCommArea.CDEMO_USRTYP_USER);
        assertEquals(0, CardDemoCommArea.CDEMO_PGM_ENTER);
        assertEquals(1, CardDemoCommArea.CDEMO_PGM_REENTER);
    }

    @Test
    void testToStringContainsFieldValues() {
        commArea.cdemoFromTranid = "TEST";
        commArea.cdemoFromProgram = "PROG";
        
        String result = commArea.toString();
        
        assertNotNull(result);
        assertTrue(result.contains("CardDemoCommArea"));
        assertTrue(result.contains("cdemoFromTranid='TEST'"));
        assertTrue(result.contains("cdemoFromProgram='PROG'"));
    }
}