package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:00:27
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;

class CustomerRecordTest {

    private CustomerRecord customerRecord;
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {
        customerRecord = new CustomerRecord();
        objectMapper = new ObjectMapper();
    }

    @Test
    void testDefaultConstructorInitializesCustIdToZero() {
        assertEquals(0L, customerRecord.custId);
    }

    @Test
    void testDefaultConstructorInitializesCustFirstNameToEmptyString() {
        assertEquals("", customerRecord.custFirstName);
    }

    @Test
    void testDefaultConstructorInitializesCustMiddleNameToEmptyString() {
        assertEquals("", customerRecord.custMiddleName);
    }

    @Test
    void testDefaultConstructorInitializesCustLastNameToEmptyString() {
        assertEquals("", customerRecord.custLastName);
    }

    @Test
    void testDefaultConstructorInitializesCustAddrLine1ToEmptyString() {
        assertEquals("", customerRecord.custAddrLine1);
    }

    @Test
    void testDefaultConstructorInitializesCustAddrLine2ToEmptyString() {
        assertEquals("", customerRecord.custAddrLine2);
    }

    @Test
    void testDefaultConstructorInitializesCustAddrLine3ToEmptyString() {
        assertEquals("", customerRecord.custAddrLine3);
    }

    @Test
    void testDefaultConstructorInitializesCustAddrStateCdToEmptyString() {
        assertEquals("", customerRecord.custAddrStateCd);
    }

    @Test
    void testDefaultConstructorInitializesCustAddrCountryCdToEmptyString() {
        assertEquals("", customerRecord.custAddrCountryCd);
    }

    @Test
    void testDefaultConstructorInitializesCustAddrZipToEmptyString() {
        assertEquals("", customerRecord.custAddrZip);
    }

    @Test
    void testDefaultConstructorInitializesCustPhoneNum1ToEmptyString() {
        assertEquals("", customerRecord.custPhoneNum1);
    }

    @Test
    void testDefaultConstructorInitializesCustPhoneNum2ToEmptyString() {
        assertEquals("", customerRecord.custPhoneNum2);
    }

    @Test
    void testDefaultConstructorInitializesCustSsnToZero() {
        assertEquals(0L, customerRecord.custSsn);
    }

    @Test
    void testDefaultConstructorInitializesCustGovtIssuedIdToEmptyString() {
        assertEquals("", customerRecord.custGovtIssuedId);
    }

    @Test
    void testDefaultConstructorInitializesCustDobYyyyMmDdToEmptyString() {
        assertEquals("", customerRecord.custDobYyyyMmDd);
    }

    @Test
    void testDefaultConstructorInitializesCustEftAccountIdToEmptyString() {
        assertEquals("", customerRecord.custEftAccountId);
    }

    @Test
    void testDefaultConstructorInitializesCustPriCardHolderIndToEmptyString() {
        assertEquals("", customerRecord.custPriCardHolderInd);
    }

    @Test
    void testDefaultConstructorInitializesCustFicoCreditScoreToZero() {
        assertEquals(0, customerRecord.custFicoCreditScore);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustId() {
        customerRecord.custId = 12345L;
        assertEquals(12345L, customerRecord.custId);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustFirstName() {
        customerRecord.custFirstName = "John";
        assertEquals("John", customerRecord.custFirstName);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustMiddleName() {
        customerRecord.custMiddleName = "Michael";
        assertEquals("Michael", customerRecord.custMiddleName);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustLastName() {
        customerRecord.custLastName = "Doe";
        assertEquals("Doe", customerRecord.custLastName);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustAddrLine1() {
        customerRecord.custAddrLine1 = "123 Main St";
        assertEquals("123 Main St", customerRecord.custAddrLine1);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustAddrLine2() {
        customerRecord.custAddrLine2 = "Apt 456";
        assertEquals("Apt 456", customerRecord.custAddrLine2);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustAddrLine3() {
        customerRecord.custAddrLine3 = "Building B";
        assertEquals("Building B", customerRecord.custAddrLine3);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustAddrStateCd() {
        customerRecord.custAddrStateCd = "CA";
        assertEquals("CA", customerRecord.custAddrStateCd);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustAddrCountryCd() {
        customerRecord.custAddrCountryCd = "US";
        assertEquals("US", customerRecord.custAddrCountryCd);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustAddrZip() {
        customerRecord.custAddrZip = "90210";
        assertEquals("90210", customerRecord.custAddrZip);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustPhoneNum1() {
        customerRecord.custPhoneNum1 = "555-123-4567";
        assertEquals("555-123-4567", customerRecord.custPhoneNum1);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustPhoneNum2() {
        customerRecord.custPhoneNum2 = "555-987-6543";
        assertEquals("555-987-6543", customerRecord.custPhoneNum2);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustSsn() {
        customerRecord.custSsn = 123456789L;
        assertEquals(123456789L, customerRecord.custSsn);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustGovtIssuedId() {
        customerRecord.custGovtIssuedId = "DL123456";
        assertEquals("DL123456", customerRecord.custGovtIssuedId);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustDobYyyyMmDd() {
        customerRecord.custDobYyyyMmDd = "1990-05-15";
        assertEquals("1990-05-15", customerRecord.custDobYyyyMmDd);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustEftAccountId() {
        customerRecord.custEftAccountId = "EFT98765";
        assertEquals("EFT98765", customerRecord.custEftAccountId);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustPriCardHolderInd() {
        customerRecord.custPriCardHolderInd = "Y";
        assertEquals("Y", customerRecord.custPriCardHolderInd);
    }

    @Test
    void testFieldAssignmentAndRetrievalForCustFicoCreditScore() {
        customerRecord.custFicoCreditScore = 750;
        assertEquals(750, customerRecord.custFicoCreditScore);
    }

    @Test
    void testToStringContainsAllFields() {
        customerRecord.custId = 1L;
        customerRecord.custFirstName = "John";
        customerRecord.custLastName = "Doe";
        
        String result = customerRecord.toString();
        
        assertTrue(result.contains("custId=1"));
        assertTrue(result.contains("custFirstName='John'"));
        assertTrue(result.contains("custLastName='Doe'"));
    }

    @Test
    void testJsonSerializationWithCustomPropertyNames() throws Exception {
        customerRecord.custId = 100L;
        customerRecord.custFirstName = "Jane";
        customerRecord.custLastName = "Smith";
        customerRecord.custFicoCreditScore = 800;
        
        String json = objectMapper.writeValueAsString(customerRecord);
        
        assertTrue(json.contains("\"CUST-ID\":100"));
        assertTrue(json.contains("\"CUST-FIRST-NAME\":\"Jane\""));
        assertTrue(json.contains("\"CUST-LAST-NAME\":\"Smith\""));
        assertTrue(json.contains("\"CUST-FICO-CREDIT-SCORE\":800"));
    }

    @Test
    void testJsonDeserializationWithCustomPropertyNames() throws Exception {
        String json = "{\"CUST-ID\":200,\"CUST-FIRST-NAME\":\"Bob\",\"CUST-LAST-NAME\":\"Jones\",\"CUST-FICO-CREDIT-SCORE\":650}";
        
        CustomerRecord result = objectMapper.readValue(json, CustomerRecord.class);
        
        assertEquals(200L, result.custId);
        assertEquals("Bob", result.custFirstName);
        assertEquals("Jones", result.custLastName);
        assertEquals(650, result.custFicoCreditScore);
    }
}