package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:05:24
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.carddemo.dto.CustomerRecord;

class CustomerRecordTest {

    private CustomerRecord customerRecord;
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {
        customerRecord = new CustomerRecord();
        objectMapper = new ObjectMapper();
    }

    @Test
    void testDefaultConstructorInitializesFieldsToDefaults() {
        assertEquals(0L, customerRecord.custId);
        assertEquals("", customerRecord.custFirstName);
        assertEquals("", customerRecord.custMiddleName);
        assertEquals("", customerRecord.custLastName);
        assertEquals("", customerRecord.custAddrLine1);
        assertEquals("", customerRecord.custAddrLine2);
        assertEquals("", customerRecord.custAddrLine3);
        assertEquals("", customerRecord.custAddrStateCd);
        assertEquals("", customerRecord.custAddrCountryCd);
        assertEquals("", customerRecord.custAddrZip);
        assertEquals("", customerRecord.custPhoneNum1);
        assertEquals("", customerRecord.custPhoneNum2);
        assertEquals(0L, customerRecord.custSsn);
        assertEquals("", customerRecord.custGovtIssuedId);
        assertEquals("", customerRecord.custDobYyyyMmDd);
        assertEquals("", customerRecord.custEftAccountId);
        assertEquals("", customerRecord.custPriCardHolderInd);
        assertEquals(0, customerRecord.custFicoCreditScore);
    }

    @Test
    void testFieldAssignmentAndRetrieval() {
        customerRecord.custId = 12345L;
        customerRecord.custFirstName = "John";
        customerRecord.custMiddleName = "Michael";
        customerRecord.custLastName = "Doe";
        customerRecord.custAddrLine1 = "123 Main Street";
        customerRecord.custAddrLine2 = "Apt 4B";
        customerRecord.custAddrLine3 = "Building C";
        customerRecord.custAddrStateCd = "CA";
        customerRecord.custAddrCountryCd = "US";
        customerRecord.custAddrZip = "90210";
        customerRecord.custPhoneNum1 = "555-123-4567";
        customerRecord.custPhoneNum2 = "555-987-6543";
        customerRecord.custSsn = 123456789L;
        customerRecord.custGovtIssuedId = "DL12345678";
        customerRecord.custDobYyyyMmDd = "1985-06-15";
        customerRecord.custEftAccountId = "EFT001234";
        customerRecord.custPriCardHolderInd = "Y";
        customerRecord.custFicoCreditScore = 750;

        assertEquals(12345L, customerRecord.custId);
        assertEquals("John", customerRecord.custFirstName);
        assertEquals("Michael", customerRecord.custMiddleName);
        assertEquals("Doe", customerRecord.custLastName);
        assertEquals("123 Main Street", customerRecord.custAddrLine1);
        assertEquals("Apt 4B", customerRecord.custAddrLine2);
        assertEquals("Building C", customerRecord.custAddrLine3);
        assertEquals("CA", customerRecord.custAddrStateCd);
        assertEquals("US", customerRecord.custAddrCountryCd);
        assertEquals("90210", customerRecord.custAddrZip);
        assertEquals("555-123-4567", customerRecord.custPhoneNum1);
        assertEquals("555-987-6543", customerRecord.custPhoneNum2);
        assertEquals(123456789L, customerRecord.custSsn);
        assertEquals("DL12345678", customerRecord.custGovtIssuedId);
        assertEquals("1985-06-15", customerRecord.custDobYyyyMmDd);
        assertEquals("EFT001234", customerRecord.custEftAccountId);
        assertEquals("Y", customerRecord.custPriCardHolderInd);
        assertEquals(750, customerRecord.custFicoCreditScore);
    }

    @Test
    void testToStringContainsAllFields() {
        customerRecord.custId = 99999L;
        customerRecord.custFirstName = "Jane";
        customerRecord.custLastName = "Smith";
        customerRecord.custFicoCreditScore = 800;

        String result = customerRecord.toString();

        assertTrue(result.contains("custId=99999"));
        assertTrue(result.contains("custFirstName='Jane'"));
        assertTrue(result.contains("custLastName='Smith'"));
        assertTrue(result.contains("custFicoCreditScore=800"));
        assertTrue(result.startsWith("CustomerRecord{"));
    }

    @Test
    void testJsonSerializationWithCustomPropertyNames() throws Exception {
        customerRecord.custId = 54321L;
        customerRecord.custFirstName = "Alice";
        customerRecord.custLastName = "Johnson";
        customerRecord.custAddrStateCd = "NY";
        customerRecord.custFicoCreditScore = 720;

        String json = objectMapper.writeValueAsString(customerRecord);

        assertTrue(json.contains("\"CUST-ID\":54321"));
        assertTrue(json.contains("\"CUST-FIRST-NAME\":\"Alice\""));
        assertTrue(json.contains("\"CUST-LAST-NAME\":\"Johnson\""));
        assertTrue(json.contains("\"CUST-ADDR-STATE-CD\":\"NY\""));
        assertTrue(json.contains("\"CUST-FICO-CREDIT-SCORE\":720"));
    }

    @Test
    void testJsonDeserializationWithCustomPropertyNames() throws Exception {
        String json = "{\"CUST-ID\":11111,\"CUST-FIRST-NAME\":\"Bob\",\"CUST-MIDDLE-NAME\":\"Lee\"," +
                "\"CUST-LAST-NAME\":\"Wilson\",\"CUST-ADDR-LINE-1\":\"456 Oak Ave\"," +
                "\"CUST-ADDR-LINE-2\":\"\",\"CUST-ADDR-LINE-3\":\"\"," +
                "\"CUST-ADDR-STATE-CD\":\"TX\",\"CUST-ADDR-COUNTRY-CD\":\"US\"," +
                "\"CUST-ADDR-ZIP\":\"75001\",\"CUST-PHONE-NUM-1\":\"214-555-1234\"," +
                "\"CUST-PHONE-NUM-2\":\"\",\"CUST-SSN\":987654321," +
                "\"CUST-GOVT-ISSUED-ID\":\"TX12345\",\"CUST-DOB-YYYY-MM-DD\":\"1990-01-15\"," +
                "\"CUST-EFT-ACCOUNT-ID\":\"EFT999\",\"CUST-PRI-CARD-HOLDER-IND\":\"N\"," +
                "\"CUST-FICO-CREDIT-SCORE\":680}";

        CustomerRecord deserialized = objectMapper.readValue(json, CustomerRecord.class);

        assertEquals(11111L, deserialized.custId);
        assertEquals("Bob", deserialized.custFirstName);
        assertEquals("Lee", deserialized.custMiddleName);
        assertEquals("Wilson", deserialized.custLastName);
        assertEquals("456 Oak Ave", deserialized.custAddrLine1);
        assertEquals("TX", deserialized.custAddrStateCd);
        assertEquals("US", deserialized.custAddrCountryCd);
        assertEquals("75001", deserialized.custAddrZip);
        assertEquals("214-555-1234", deserialized.custPhoneNum1);
        assertEquals(987654321L, deserialized.custSsn);
        assertEquals("TX12345", deserialized.custGovtIssuedId);
        assertEquals("1990-01-15", deserialized.custDobYyyyMmDd);
        assertEquals("EFT999", deserialized.custEftAccountId);
        assertEquals("N", deserialized.custPriCardHolderInd);
        assertEquals(680, deserialized.custFicoCreditScore);
    }

    @Test
    void testLongFieldsAcceptLargeValues() {
        customerRecord.custId = Long.MAX_VALUE;
        customerRecord.custSsn = 999999999L;

        assertEquals(Long.MAX_VALUE, customerRecord.custId);
        assertEquals(999999999L, customerRecord.custSsn);
    }

    @Test
    void testIntFieldAcceptsBoundaryValues() {
        customerRecord.custFicoCreditScore = 850;
        assertEquals(850, customerRecord.custFicoCreditScore);

        customerRecord.custFicoCreditScore = 300;
        assertEquals(300, customerRecord.custFicoCreditScore);

        customerRecord.custFicoCreditScore = 0;
        assertEquals(0, customerRecord.custFicoCreditScore);
    }

    @Test
    void testStringFieldsAcceptNullValues() {
        customerRecord.custFirstName = null;
        customerRecord.custLastName = null;

        assertNull(customerRecord.custFirstName);
        assertNull(customerRecord.custLastName);
    }

    @Test
    void testToStringWithDefaultValues() {
        String result = customerRecord.toString();

        assertTrue(result.contains("custId=0"));
        assertTrue(result.contains("custFirstName=''"));
        assertTrue(result.contains("custSsn=0"));
        assertTrue(result.contains("custFicoCreditScore=0"));
    }
}