package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:58:30
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.fasterxml.jackson.databind.ObjectMapper;

class DateDataTest {

    private DateData dateData;
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {
        dateData = new DateData();
        objectMapper = new ObjectMapper();
    }

    @Test
    void testDefaultFieldInitialization_CurdateFields() {
        assertEquals(0, dateData.wsCurdateYear);
        assertEquals(0, dateData.wsCurdateMonth);
        assertEquals(0, dateData.wsCurdateDay);
        assertEquals(0L, dateData.wsCurdateN);
    }

    @Test
    void testDefaultFieldInitialization_CurtimeFields() {
        assertEquals(0, dateData.wsCurtimeHours);
        assertEquals(0, dateData.wsCurtimeMinute);
        assertEquals(0, dateData.wsCurtimeSecond);
        assertEquals(0, dateData.wsCurtimeMilsec);
        assertEquals(0L, dateData.wsCurtimeN);
    }

    @Test
    void testDefaultFieldInitialization_CurdateMmDdYyFields() {
        assertEquals(0, dateData.wsCurdateMm);
        assertEquals(0, dateData.wsCurdateDd);
        assertEquals(0, dateData.wsCurdateYy);
    }

    @Test
    void testDefaultFieldInitialization_CurtimeHhMmSsFields() {
        assertEquals(0, dateData.wsCurtimeHh);
        assertEquals(0, dateData.wsCurtimeMm);
        assertEquals(0, dateData.wsCurtimeSs);
    }

    @Test
    void testDefaultFieldInitialization_TimestampFields() {
        assertEquals(0, dateData.wsTimestampDtYyyy);
        assertEquals(0, dateData.wsTimestampDtMm);
        assertEquals(0, dateData.wsTimestampDtDd);
        assertEquals(0, dateData.wsTimestampTmHh);
        assertEquals(0, dateData.wsTimestampTmMm);
        assertEquals(0, dateData.wsTimestampTmSs);
        assertEquals(0, dateData.wsTimestampTmMs6);
    }

    @Test
    void testFieldAssignment_CurdateFields() {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 12;
        dateData.wsCurdateDay = 25;
        dateData.wsCurdateN = 20241225L;

        assertEquals(2024, dateData.wsCurdateYear);
        assertEquals(12, dateData.wsCurdateMonth);
        assertEquals(25, dateData.wsCurdateDay);
        assertEquals(20241225L, dateData.wsCurdateN);
    }

    @Test
    void testFieldAssignment_CurtimeFields() {
        dateData.wsCurtimeHours = 14;
        dateData.wsCurtimeMinute = 30;
        dateData.wsCurtimeSecond = 45;
        dateData.wsCurtimeMilsec = 123;
        dateData.wsCurtimeN = 14304512L;

        assertEquals(14, dateData.wsCurtimeHours);
        assertEquals(30, dateData.wsCurtimeMinute);
        assertEquals(45, dateData.wsCurtimeSecond);
        assertEquals(123, dateData.wsCurtimeMilsec);
        assertEquals(14304512L, dateData.wsCurtimeN);
    }

    @Test
    void testFieldAssignment_CurdateMmDdYyFields() {
        dateData.wsCurdateMm = 12;
        dateData.wsCurdateDd = 25;
        dateData.wsCurdateYy = 24;

        assertEquals(12, dateData.wsCurdateMm);
        assertEquals(25, dateData.wsCurdateDd);
        assertEquals(24, dateData.wsCurdateYy);
    }

    @Test
    void testFieldAssignment_TimestampFields() {
        dateData.wsTimestampDtYyyy = 2024;
        dateData.wsTimestampDtMm = 12;
        dateData.wsTimestampDtDd = 25;
        dateData.wsTimestampTmHh = 14;
        dateData.wsTimestampTmMm = 30;
        dateData.wsTimestampTmSs = 45;
        dateData.wsTimestampTmMs6 = 123456;

        assertEquals(2024, dateData.wsTimestampDtYyyy);
        assertEquals(12, dateData.wsTimestampDtMm);
        assertEquals(25, dateData.wsTimestampDtDd);
        assertEquals(14, dateData.wsTimestampTmHh);
        assertEquals(30, dateData.wsTimestampTmMm);
        assertEquals(45, dateData.wsTimestampTmSs);
        assertEquals(123456, dateData.wsTimestampTmMs6);
    }

    @Test
    void testGetFormattedCurdate() {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 5;
        dateData.wsCurdateDay = 9;

        assertEquals("20240509", dateData.getFormattedCurdate());
    }

    @Test
    void testGetFormattedCurdate_WithZeroPadding() {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 1;
        dateData.wsCurdateDay = 5;

        assertEquals("20240105", dateData.getFormattedCurdate());
    }

    @Test
    void testGetFormattedCurtime() {
        dateData.wsCurtimeHours = 9;
        dateData.wsCurtimeMinute = 5;
        dateData.wsCurtimeSecond = 3;
        dateData.wsCurtimeMilsec = 7;

        assertEquals("09050307", dateData.getFormattedCurtime());
    }

    @Test
    void testGetFormattedCurdateMmDdYy() {
        dateData.wsCurdateMm = 12;
        dateData.wsCurdateDd = 25;
        dateData.wsCurdateYy = 24;

        assertEquals("12/25/24", dateData.getFormattedCurdateMmDdYy());
    }

    @Test
    void testGetFormattedCurdateMmDdYy_WithZeroPadding() {
        dateData.wsCurdateMm = 1;
        dateData.wsCurdateDd = 5;
        dateData.wsCurdateYy = 4;

        assertEquals("01/05/04", dateData.getFormattedCurdateMmDdYy());
    }

    @Test
    void testGetFormattedCurtimeHhMmSs() {
        dateData.wsCurtimeHh = 14;
        dateData.wsCurtimeMm = 30;
        dateData.wsCurtimeSs = 45;

        assertEquals("14:30:45", dateData.getFormattedCurtimeHhMmSs());
    }

    @Test
    void testGetFormattedCurtimeHhMmSs_WithZeroPadding() {
        dateData.wsCurtimeHh = 9;
        dateData.wsCurtimeMm = 5;
        dateData.wsCurtimeSs = 3;

        assertEquals("09:05:03", dateData.getFormattedCurtimeHhMmSs());
    }

    @Test
    void testGetFormattedTimestamp() {
        dateData.wsTimestampDtYyyy = 2024;
        dateData.wsTimestampDtMm = 12;
        dateData.wsTimestampDtDd = 25;
        dateData.wsTimestampTmHh = 14;
        dateData.wsTimestampTmMm = 30;
        dateData.wsTimestampTmSs = 45;
        dateData.wsTimestampTmMs6 = 123456;

        assertEquals("2024-12-25 14:30:45.123456", dateData.getFormattedTimestamp());
    }

    @Test
    void testGetFormattedTimestamp_WithZeroPadding() {
        dateData.wsTimestampDtYyyy = 2024;
        dateData.wsTimestampDtMm = 1;
        dateData.wsTimestampDtDd = 5;
        dateData.wsTimestampTmHh = 9;
        dateData.wsTimestampTmMm = 3;
        dateData.wsTimestampTmSs = 7;
        dateData.wsTimestampTmMs6 = 123;

        assertEquals("2024-01-05 09:03:07.000123", dateData.getFormattedTimestamp());
    }

    @Test
    void testToString_NotNull() {
        assertNotNull(dateData.toString());
    }

    @Test
    void testToString_ContainsFieldNames() {
        String result = dateData.toString();
        assertTrue(result.contains("DateData"));
        assertTrue(result.contains("wsCurdateYear"));
    }

    @Test
    void testJsonSerialization() throws Exception {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 12;
        dateData.wsCurdateDay = 25;

        String json = objectMapper.writeValueAsString(dateData);

        assertTrue(json.contains("WS-CURDATE-YEAR"));
        assertTrue(json.contains("WS-CURDATE-MONTH"));
        assertTrue(json.contains("WS-CURDATE-DAY"));
        assertTrue(json.contains("2024"));
    }

    @Test
    void testJsonDeserialization() throws Exception {
        String json = "{\"WS-CURDATE-YEAR\":2024,\"WS-CURDATE-MONTH\":12,\"WS-CURDATE-DAY\":25}";

        DateData result = objectMapper.readValue(json, DateData.class);

        assertEquals(2024, result.wsCurdateYear);
        assertEquals(12, result.wsCurdateMonth);
        assertEquals(25, result.wsCurdateDay);
    }

    @Test
    void testDefaultConstructor() {
        DateData newDateData = new DateData();
        assertNotNull(newDateData);
    }

    @Test
    void testGetFormattedCurdate_DefaultValues() {
        assertEquals("00000000", dateData.getFormattedCurdate());
    }

    @Test
    void testGetFormattedCurtime_DefaultValues() {
        assertEquals("00000000", dateData.getFormattedCurtime());
    }

    @Test
    void testGetFormattedCurdateMmDdYy_DefaultValues() {
        assertEquals("00/00/00", dateData.getFormattedCurdateMmDdYy());
    }

    @Test
    void testGetFormattedCurtimeHhMmSs_DefaultValues() {
        assertEquals("00:00:00", dateData.getFormattedCurtimeHhMmSs());
    }

    @Test
    void testGetFormattedTimestamp_DefaultValues() {
        assertEquals("0000-00-00 00:00:00.000000", dateData.getFormattedTimestamp());
    }
}