package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:03:16
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.carddemo.dto.DateData;

class DateDataTest {

    private DateData dateData;

    @BeforeEach
    void setUp() {
        dateData = new DateData();
    }

    @Test
    void testDefaultFieldInitialization() {
        assertEquals(0, dateData.wsCurdateYear);
        assertEquals(0, dateData.wsCurdateMonth);
        assertEquals(0, dateData.wsCurdateDay);
        assertEquals(0L, dateData.wsCurdateN);
        assertEquals(0, dateData.wsCurtimeHours);
        assertEquals(0, dateData.wsCurtimeMinute);
        assertEquals(0, dateData.wsCurtimeSecond);
        assertEquals(0, dateData.wsCurtimeMilsec);
        assertEquals(0L, dateData.wsCurtimeN);
        assertEquals(0, dateData.wsCurdateMm);
        assertEquals(0, dateData.wsCurdateDd);
        assertEquals(0, dateData.wsCurdateYy);
        assertEquals(0, dateData.wsCurtimeHh);
        assertEquals(0, dateData.wsCurtimeMm);
        assertEquals(0, dateData.wsCurtimeSs);
        assertEquals(0, dateData.wsTimestampDtYyyy);
        assertEquals(0, dateData.wsTimestampDtMm);
        assertEquals(0, dateData.wsTimestampDtDd);
        assertEquals(0, dateData.wsTimestampTmHh);
        assertEquals(0, dateData.wsTimestampTmMm);
        assertEquals(0, dateData.wsTimestampTmSs);
        assertEquals(0L, dateData.wsTimestampTmMs6);
    }

    @Test
    void testFieldAssignmentAndRetrieval() {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 12;
        dateData.wsCurdateDay = 25;
        dateData.wsCurdateN = 20241225L;
        dateData.wsCurtimeHours = 14;
        dateData.wsCurtimeMinute = 30;
        dateData.wsCurtimeSecond = 45;
        dateData.wsCurtimeMilsec = 123;
        dateData.wsCurtimeN = 143045123L;
        dateData.wsCurdateMm = 12;
        dateData.wsCurdateDd = 25;
        dateData.wsCurdateYy = 24;
        dateData.wsCurtimeHh = 14;
        dateData.wsCurtimeMm = 30;
        dateData.wsCurtimeSs = 45;
        dateData.wsTimestampDtYyyy = 2024;
        dateData.wsTimestampDtMm = 12;
        dateData.wsTimestampDtDd = 25;
        dateData.wsTimestampTmHh = 14;
        dateData.wsTimestampTmMm = 30;
        dateData.wsTimestampTmSs = 45;
        dateData.wsTimestampTmMs6 = 123456L;

        assertEquals(2024, dateData.wsCurdateYear);
        assertEquals(12, dateData.wsCurdateMonth);
        assertEquals(25, dateData.wsCurdateDay);
        assertEquals(20241225L, dateData.wsCurdateN);
        assertEquals(14, dateData.wsCurtimeHours);
        assertEquals(30, dateData.wsCurtimeMinute);
        assertEquals(45, dateData.wsCurtimeSecond);
        assertEquals(123, dateData.wsCurtimeMilsec);
        assertEquals(143045123L, dateData.wsCurtimeN);
        assertEquals(12, dateData.wsCurdateMm);
        assertEquals(25, dateData.wsCurdateDd);
        assertEquals(24, dateData.wsCurdateYy);
        assertEquals(14, dateData.wsCurtimeHh);
        assertEquals(30, dateData.wsCurtimeMm);
        assertEquals(45, dateData.wsCurtimeSs);
        assertEquals(2024, dateData.wsTimestampDtYyyy);
        assertEquals(12, dateData.wsTimestampDtMm);
        assertEquals(25, dateData.wsTimestampDtDd);
        assertEquals(14, dateData.wsTimestampTmHh);
        assertEquals(30, dateData.wsTimestampTmMm);
        assertEquals(45, dateData.wsTimestampTmSs);
        assertEquals(123456L, dateData.wsTimestampTmMs6);
    }

    @Test
    void testGetFormattedCurdateWithDefaultValues() {
        assertEquals("00000000", dateData.getFormattedCurdate());
    }

    @Test
    void testGetFormattedCurdateWithSetValues() {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 3;
        dateData.wsCurdateDay = 5;
        assertEquals("20240305", dateData.getFormattedCurdate());
    }

    @Test
    void testGetFormattedCurtimeWithDefaultValues() {
        assertEquals("00000000", dateData.getFormattedCurtime());
    }

    @Test
    void testGetFormattedCurtimeWithSetValues() {
        dateData.wsCurtimeHours = 9;
        dateData.wsCurtimeMinute = 5;
        dateData.wsCurtimeSecond = 3;
        dateData.wsCurtimeMilsec = 12;
        assertEquals("09050312", dateData.getFormattedCurtime());
    }

    @Test
    void testGetFormattedCurdateMmDdYyWithDefaultValues() {
        assertEquals("00/00/00", dateData.getFormattedCurdateMmDdYy());
    }

    @Test
    void testGetFormattedCurdateMmDdYyWithSetValues() {
        dateData.wsCurdateMm = 12;
        dateData.wsCurdateDd = 25;
        dateData.wsCurdateYy = 24;
        assertEquals("12/25/24", dateData.getFormattedCurdateMmDdYy());
    }

    @Test
    void testGetFormattedCurtimeHhMmSsWithDefaultValues() {
        assertEquals("00:00:00", dateData.getFormattedCurtimeHhMmSs());
    }

    @Test
    void testGetFormattedCurtimeHhMmSsWithSetValues() {
        dateData.wsCurtimeHh = 14;
        dateData.wsCurtimeMm = 30;
        dateData.wsCurtimeSs = 45;
        assertEquals("14:30:45", dateData.getFormattedCurtimeHhMmSs());
    }

    @Test
    void testGetFormattedTimestampWithDefaultValues() {
        assertEquals("0000-00-00 00:00:00.000000", dateData.getFormattedTimestamp());
    }

    @Test
    void testGetFormattedTimestampWithSetValues() {
        dateData.wsTimestampDtYyyy = 2024;
        dateData.wsTimestampDtMm = 12;
        dateData.wsTimestampDtDd = 25;
        dateData.wsTimestampTmHh = 14;
        dateData.wsTimestampTmMm = 30;
        dateData.wsTimestampTmSs = 45;
        dateData.wsTimestampTmMs6 = 123456L;
        assertEquals("2024-12-25 14:30:45.123456", dateData.getFormattedTimestamp());
    }

    @Test
    void testToStringContainsFieldValues() {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 12;
        dateData.wsCurdateDay = 25;
        
        String result = dateData.toString();
        
        assertTrue(result.contains("wsCurdateYear=2024"));
        assertTrue(result.contains("wsCurdateMonth=12"));
        assertTrue(result.contains("wsCurdateDay=25"));
        assertTrue(result.startsWith("DateData{"));
    }

    @Test
    void testFormattedCurdateWithSingleDigitValues() {
        dateData.wsCurdateYear = 2024;
        dateData.wsCurdateMonth = 1;
        dateData.wsCurdateDay = 5;
        assertEquals("20240105", dateData.getFormattedCurdate());
    }

    @Test
    void testFormattedCurtimeWithSingleDigitValues() {
        dateData.wsCurtimeHours = 1;
        dateData.wsCurtimeMinute = 2;
        dateData.wsCurtimeSecond = 3;
        dateData.wsCurtimeMilsec = 4;
        assertEquals("01020304", dateData.getFormattedCurtime());
    }

    @Test
    void testFormattedTimestampWithSmallMicroseconds() {
        dateData.wsTimestampDtYyyy = 2024;
        dateData.wsTimestampDtMm = 1;
        dateData.wsTimestampDtDd = 1;
        dateData.wsTimestampTmHh = 0;
        dateData.wsTimestampTmMm = 0;
        dateData.wsTimestampTmSs = 0;
        dateData.wsTimestampTmMs6 = 1L;
        assertEquals("2024-01-01 00:00:00.000001", dateData.getFormattedTimestamp());
    }
}