package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:58:45
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class MessageDataTest {

    private MessageData messageData;

    @BeforeEach
    void setUp() {
        messageData = new MessageData();
    }

    @Test
    void testDefaultConstructorInitializesCcdaMsgThankYou() {
        assertEquals("Thank you for using CardDemo application...      ", messageData.ccdaMsgThankYou);
    }

    @Test
    void testDefaultConstructorInitializesCcdaMsgInvalidKey() {
        assertEquals("Invalid key pressed. Please see below...         ", messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testFieldAssignmentCcdaMsgThankYou() {
        String newMessage = "New thank you message";
        messageData.ccdaMsgThankYou = newMessage;
        assertEquals(newMessage, messageData.ccdaMsgThankYou);
    }

    @Test
    void testFieldAssignmentCcdaMsgInvalidKey() {
        String newMessage = "New invalid key message";
        messageData.ccdaMsgInvalidKey = newMessage;
        assertEquals(newMessage, messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testFieldRetrievalCcdaMsgThankYou() {
        String retrievedValue = messageData.ccdaMsgThankYou;
        assertNotNull(retrievedValue);
        assertEquals("Thank you for using CardDemo application...      ", retrievedValue);
    }

    @Test
    void testFieldRetrievalCcdaMsgInvalidKey() {
        String retrievedValue = messageData.ccdaMsgInvalidKey;
        assertNotNull(retrievedValue);
        assertEquals("Invalid key pressed. Please see below...         ", retrievedValue);
    }

    @Test
    void testToStringContainsCcdaMsgThankYou() {
        String result = messageData.toString();
        assertTrue(result.contains("ccdaMsgThankYou="));
        assertTrue(result.contains("Thank you for using CardDemo application..."));
    }

    @Test
    void testToStringContainsCcdaMsgInvalidKey() {
        String result = messageData.toString();
        assertTrue(result.contains("ccdaMsgInvalidKey="));
        assertTrue(result.contains("Invalid key pressed. Please see below..."));
    }

    @Test
    void testToStringFormat() {
        String result = messageData.toString();
        assertTrue(result.startsWith("MessageData{"));
        assertTrue(result.endsWith("}"));
    }

    @Test
    void testFieldsAreNotNullAfterConstruction() {
        assertNotNull(messageData.ccdaMsgThankYou);
        assertNotNull(messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testFieldCanBeSetToEmptyString() {
        messageData.ccdaMsgThankYou = "";
        messageData.ccdaMsgInvalidKey = "";
        assertEquals("", messageData.ccdaMsgThankYou);
        assertEquals("", messageData.ccdaMsgInvalidKey);
    }

    @Test
    void testFieldCanBeSetToNull() {
        messageData.ccdaMsgThankYou = null;
        messageData.ccdaMsgInvalidKey = null;
        assertNull(messageData.ccdaMsgThankYou);
        assertNull(messageData.ccdaMsgInvalidKey);
    }
}