package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:02:37
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import com.carddemo.dto.TitleData;

class TitleDataTest {

    private TitleData titleData;

    @BeforeEach
    void setUp() {
        titleData = new TitleData();
    }

    @Test
    void testDefaultConstructorInitializesTitle01() {
        assertEquals("      AWS Mainframe Modernization       ", titleData.title01);
    }

    @Test
    void testDefaultConstructorInitializesTitle02() {
        assertEquals("              CardDemo                  ", titleData.title02);
    }

    @Test
    void testDefaultConstructorInitializesThankYou() {
        assertEquals("Thank you for using CCDA application... ", titleData.thankYou);
    }

    @Test
    void testTitle01FieldAssignment() {
        titleData.title01 = "Custom Title 01";
        assertEquals("Custom Title 01", titleData.title01);
    }

    @Test
    void testTitle02FieldAssignment() {
        titleData.title02 = "Custom Title 02";
        assertEquals("Custom Title 02", titleData.title02);
    }

    @Test
    void testThankYouFieldAssignment() {
        titleData.thankYou = "Custom Thank You Message";
        assertEquals("Custom Thank You Message", titleData.thankYou);
    }

    @Test
    void testToStringContainsTitle01() {
        String result = titleData.toString();
        assertTrue(result.contains("title01='      AWS Mainframe Modernization       '"));
    }

    @Test
    void testToStringContainsTitle02() {
        String result = titleData.toString();
        assertTrue(result.contains("title02='              CardDemo                  '"));
    }

    @Test
    void testToStringContainsThankYou() {
        String result = titleData.toString();
        assertTrue(result.contains("thankYou='Thank you for using CCDA application... '"));
    }

    @Test
    void testToStringFormat() {
        String result = titleData.toString();
        assertTrue(result.startsWith("TitleData{"));
        assertTrue(result.endsWith("}"));
    }

    @Test
    void testFieldsCanBeSetToNull() {
        titleData.title01 = null;
        titleData.title02 = null;
        titleData.thankYou = null;
        
        assertNull(titleData.title01);
        assertNull(titleData.title02);
        assertNull(titleData.thankYou);
    }

    @Test
    void testFieldsCanBeSetToEmptyString() {
        titleData.title01 = "";
        titleData.title02 = "";
        titleData.thankYou = "";
        
        assertEquals("", titleData.title01);
        assertEquals("", titleData.title02);
        assertEquals("", titleData.thankYou);
    }

    @Test
    void testMultipleInstancesAreIndependent() {
        TitleData anotherTitleData = new TitleData();
        
        titleData.title01 = "Modified Title";
        
        assertEquals("Modified Title", titleData.title01);
        assertEquals("      AWS Mainframe Modernization       ", anotherTitleData.title01);
    }
}