package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:57:46
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class TitleDataTest {

    private TitleData titleData;

    @BeforeEach
    void setUp() {
        titleData = new TitleData();
    }

    @Test
    void testDefaultConstructorInitializesCcdaTitle01() {
        assertEquals("      AWS Mainframe Modernization       ", titleData.ccdaTitle01);
    }

    @Test
    void testDefaultConstructorInitializesCcdaTitle02() {
        assertEquals("              CardDemo                  ", titleData.ccdaTitle02);
    }

    @Test
    void testDefaultConstructorInitializesCcdaThankYou() {
        assertEquals("Thank you for using CCDA application... ", titleData.ccdaThankYou);
    }

    @Test
    void testFieldAssignmentCcdaTitle01() {
        titleData.ccdaTitle01 = "Custom Title 01";
        assertEquals("Custom Title 01", titleData.ccdaTitle01);
    }

    @Test
    void testFieldAssignmentCcdaTitle02() {
        titleData.ccdaTitle02 = "Custom Title 02";
        assertEquals("Custom Title 02", titleData.ccdaTitle02);
    }

    @Test
    void testFieldAssignmentCcdaThankYou() {
        titleData.ccdaThankYou = "Custom Thank You Message";
        assertEquals("Custom Thank You Message", titleData.ccdaThankYou);
    }

    @Test
    void testFieldCanBeSetToNull() {
        titleData.ccdaTitle01 = null;
        assertNull(titleData.ccdaTitle01);
    }

    @Test
    void testFieldCanBeSetToEmptyString() {
        titleData.ccdaTitle02 = "";
        assertEquals("", titleData.ccdaTitle02);
    }

    @Test
    void testToStringContainsCcdaTitle01() {
        String result = titleData.toString();
        assertTrue(result.contains("ccdaTitle01='      AWS Mainframe Modernization       '"));
    }

    @Test
    void testToStringContainsCcdaTitle02() {
        String result = titleData.toString();
        assertTrue(result.contains("ccdaTitle02='              CardDemo                  '"));
    }

    @Test
    void testToStringContainsCcdaThankYou() {
        String result = titleData.toString();
        assertTrue(result.contains("ccdaThankYou='Thank you for using CCDA application... '"));
    }

    @Test
    void testToStringFormat() {
        String result = titleData.toString();
        assertTrue(result.startsWith("TitleData{"));
        assertTrue(result.endsWith("}"));
    }

    @Test
    void testMultipleFieldAssignments() {
        titleData.ccdaTitle01 = "New Title 1";
        titleData.ccdaTitle02 = "New Title 2";
        titleData.ccdaThankYou = "New Thank You";
        
        assertEquals("New Title 1", titleData.ccdaTitle01);
        assertEquals("New Title 2", titleData.ccdaTitle02);
        assertEquals("New Thank You", titleData.ccdaThankYou);
    }

    @Test
    void testToStringReflectsModifiedValues() {
        titleData.ccdaTitle01 = "Modified";
        String result = titleData.toString();
        assertTrue(result.contains("ccdaTitle01='Modified'"));
    }
}