package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:00:54
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import java.math.BigDecimal;

class TransactionRecordTest {

    private TransactionRecord transactionRecord;

    @BeforeEach
    void setUp() {
        transactionRecord = new TransactionRecord();
    }

    @Test
    void testDefaultConstructorInitializesTranIdToEmptyString() {
        assertEquals("", transactionRecord.tranId);
    }

    @Test
    void testDefaultConstructorInitializesTranTypeCdToEmptyString() {
        assertEquals("", transactionRecord.tranTypeCd);
    }

    @Test
    void testDefaultConstructorInitializesTranCatCdToZero() {
        assertEquals(0, transactionRecord.tranCatCd);
    }

    @Test
    void testDefaultConstructorInitializesTranSourceToEmptyString() {
        assertEquals("", transactionRecord.tranSource);
    }

    @Test
    void testDefaultConstructorInitializesTranDescToEmptyString() {
        assertEquals("", transactionRecord.tranDesc);
    }

    @Test
    void testDefaultConstructorInitializesTranAmtToZero() {
        assertEquals(BigDecimal.ZERO, transactionRecord.tranAmt);
    }

    @Test
    void testDefaultConstructorInitializesTranMerchantIdToZero() {
        assertEquals(0L, transactionRecord.tranMerchantId);
    }

    @Test
    void testDefaultConstructorInitializesTranMerchantNameToEmptyString() {
        assertEquals("", transactionRecord.tranMerchantName);
    }

    @Test
    void testDefaultConstructorInitializesTranMerchantCityToEmptyString() {
        assertEquals("", transactionRecord.tranMerchantCity);
    }

    @Test
    void testDefaultConstructorInitializesTranMerchantZipToEmptyString() {
        assertEquals("", transactionRecord.tranMerchantZip);
    }

    @Test
    void testDefaultConstructorInitializesTranCardNumToEmptyString() {
        assertEquals("", transactionRecord.tranCardNum);
    }

    @Test
    void testDefaultConstructorInitializesTranOrigTsToEmptyString() {
        assertEquals("", transactionRecord.tranOrigTs);
    }

    @Test
    void testDefaultConstructorInitializesTranProcTsToEmptyString() {
        assertEquals("", transactionRecord.tranProcTs);
    }

    @Test
    void testTranIdFieldAssignmentAndRetrieval() {
        transactionRecord.tranId = "TXN12345";
        assertEquals("TXN12345", transactionRecord.tranId);
    }

    @Test
    void testTranTypeCdFieldAssignmentAndRetrieval() {
        transactionRecord.tranTypeCd = "DEBIT";
        assertEquals("DEBIT", transactionRecord.tranTypeCd);
    }

    @Test
    void testTranCatCdFieldAssignmentAndRetrieval() {
        transactionRecord.tranCatCd = 5;
        assertEquals(5, transactionRecord.tranCatCd);
    }

    @Test
    void testTranSourceFieldAssignmentAndRetrieval() {
        transactionRecord.tranSource = "ONLINE";
        assertEquals("ONLINE", transactionRecord.tranSource);
    }

    @Test
    void testTranDescFieldAssignmentAndRetrieval() {
        transactionRecord.tranDesc = "Purchase at Store";
        assertEquals("Purchase at Store", transactionRecord.tranDesc);
    }

    @Test
    void testTranAmtFieldAssignmentAndRetrieval() {
        transactionRecord.tranAmt = new BigDecimal("150.75");
        assertEquals(new BigDecimal("150.75"), transactionRecord.tranAmt);
    }

    @Test
    void testTranMerchantIdFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantId = 987654321L;
        assertEquals(987654321L, transactionRecord.tranMerchantId);
    }

    @Test
    void testTranMerchantNameFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantName = "Amazon";
        assertEquals("Amazon", transactionRecord.tranMerchantName);
    }

    @Test
    void testTranMerchantCityFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantCity = "Seattle";
        assertEquals("Seattle", transactionRecord.tranMerchantCity);
    }

    @Test
    void testTranMerchantZipFieldAssignmentAndRetrieval() {
        transactionRecord.tranMerchantZip = "98101";
        assertEquals("98101", transactionRecord.tranMerchantZip);
    }

    @Test
    void testTranCardNumFieldAssignmentAndRetrieval() {
        transactionRecord.tranCardNum = "4111111111111111";
        assertEquals("4111111111111111", transactionRecord.tranCardNum);
    }

    @Test
    void testTranOrigTsFieldAssignmentAndRetrieval() {
        transactionRecord.tranOrigTs = "2024-01-15T10:30:00";
        assertEquals("2024-01-15T10:30:00", transactionRecord.tranOrigTs);
    }

    @Test
    void testTranProcTsFieldAssignmentAndRetrieval() {
        transactionRecord.tranProcTs = "2024-01-15T10:30:05";
        assertEquals("2024-01-15T10:30:05", transactionRecord.tranProcTs);
    }

    @Test
    void testToStringContainsAllFields() {
        transactionRecord.tranId = "TXN001";
        transactionRecord.tranTypeCd = "CREDIT";
        transactionRecord.tranCatCd = 3;
        transactionRecord.tranSource = "POS";
        transactionRecord.tranDesc = "Test Transaction";
        transactionRecord.tranAmt = new BigDecimal("99.99");
        transactionRecord.tranMerchantId = 12345L;
        transactionRecord.tranMerchantName = "Test Merchant";
        transactionRecord.tranMerchantCity = "New York";
        transactionRecord.tranMerchantZip = "10001";
        transactionRecord.tranCardNum = "1234567890123456";
        transactionRecord.tranOrigTs = "2024-01-01T12:00:00";
        transactionRecord.tranProcTs = "2024-01-01T12:00:01";

        String result = transactionRecord.toString();

        assertTrue(result.contains("tranId='TXN001'"));
        assertTrue(result.contains("tranTypeCd='CREDIT'"));
        assertTrue(result.contains("tranCatCd=3"));
        assertTrue(result.contains("tranSource='POS'"));
        assertTrue(result.contains("tranDesc='Test Transaction'"));
        assertTrue(result.contains("tranAmt=99.99"));
        assertTrue(result.contains("tranMerchantId=12345"));
        assertTrue(result.contains("tranMerchantName='Test Merchant'"));
        assertTrue(result.contains("tranMerchantCity='New York'"));
        assertTrue(result.contains("tranMerchantZip='10001'"));
        assertTrue(result.contains("tranCardNum='1234567890123456'"));
        assertTrue(result.contains("tranOrigTs='2024-01-01T12:00:00'"));
        assertTrue(result.contains("tranProcTs='2024-01-01T12:00:01'"));
    }

    @Test
    void testToStringStartsWithClassName() {
        String result = transactionRecord.toString();
        assertTrue(result.startsWith("TransactionRecord{"));
    }

    @Test
    void testToStringEndsWithClosingBrace() {
        String result = transactionRecord.toString();
        assertTrue(result.endsWith("}"));
    }
}