package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:59:05
// Source: AWS CardDemo (Apache 2.0)

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class UserSecurityDataTest {

    private UserSecurityData userSecurityData;

    @BeforeEach
    void setUp() {
        userSecurityData = new UserSecurityData();
    }

    @Test
    void testDefaultConstructorInitializesSecUsrIdToEmptyString() {
        assertEquals("", userSecurityData.secUsrId);
    }

    @Test
    void testDefaultConstructorInitializesSecUsrFnameToEmptyString() {
        assertEquals("", userSecurityData.secUsrFname);
    }

    @Test
    void testDefaultConstructorInitializesSecUsrLnameToEmptyString() {
        assertEquals("", userSecurityData.secUsrLname);
    }

    @Test
    void testDefaultConstructorInitializesSecUsrPwdToEmptyString() {
        assertEquals("", userSecurityData.secUsrPwd);
    }

    @Test
    void testDefaultConstructorInitializesSecUsrTypeToEmptyString() {
        assertEquals("", userSecurityData.secUsrType);
    }

    @Test
    void testSecUsrIdFieldAssignmentAndRetrieval() {
        userSecurityData.secUsrId = "USR001";
        assertEquals("USR001", userSecurityData.secUsrId);
    }

    @Test
    void testSecUsrFnameFieldAssignmentAndRetrieval() {
        userSecurityData.secUsrFname = "John";
        assertEquals("John", userSecurityData.secUsrFname);
    }

    @Test
    void testSecUsrLnameFieldAssignmentAndRetrieval() {
        userSecurityData.secUsrLname = "Doe";
        assertEquals("Doe", userSecurityData.secUsrLname);
    }

    @Test
    void testSecUsrPwdFieldAssignmentAndRetrieval() {
        userSecurityData.secUsrPwd = "password123";
        assertEquals("password123", userSecurityData.secUsrPwd);
    }

    @Test
    void testSecUsrTypeFieldAssignmentAndRetrieval() {
        userSecurityData.secUsrType = "ADMIN";
        assertEquals("ADMIN", userSecurityData.secUsrType);
    }

    @Test
    void testToStringWithDefaultValues() {
        String expected = "UserSecurityData{secUsrId='', secUsrFname='', secUsrLname='', secUsrPwd='', secUsrType=''}";
        assertEquals(expected, userSecurityData.toString());
    }

    @Test
    void testToStringWithAssignedValues() {
        userSecurityData.secUsrId = "USR001";
        userSecurityData.secUsrFname = "John";
        userSecurityData.secUsrLname = "Doe";
        userSecurityData.secUsrPwd = "secret";
        userSecurityData.secUsrType = "USER";

        String expected = "UserSecurityData{secUsrId='USR001', secUsrFname='John', secUsrLname='Doe', secUsrPwd='secret', secUsrType='USER'}";
        assertEquals(expected, userSecurityData.toString());
    }

    @Test
    void testAllFieldsCanBeSetAndRetrieved() {
        userSecurityData.secUsrId = "USR123";
        userSecurityData.secUsrFname = "Jane";
        userSecurityData.secUsrLname = "Smith";
        userSecurityData.secUsrPwd = "myPassword";
        userSecurityData.secUsrType = "MANAGER";

        assertAll(
            () -> assertEquals("USR123", userSecurityData.secUsrId),
            () -> assertEquals("Jane", userSecurityData.secUsrFname),
            () -> assertEquals("Smith", userSecurityData.secUsrLname),
            () -> assertEquals("myPassword", userSecurityData.secUsrPwd),
            () -> assertEquals("MANAGER", userSecurityData.secUsrType)
        );
    }

    @Test
    void testFieldsCanBeSetToNull() {
        userSecurityData.secUsrId = null;
        userSecurityData.secUsrFname = null;
        userSecurityData.secUsrLname = null;
        userSecurityData.secUsrPwd = null;
        userSecurityData.secUsrType = null;

        assertAll(
            () -> assertNull(userSecurityData.secUsrId),
            () -> assertNull(userSecurityData.secUsrFname),
            () -> assertNull(userSecurityData.secUsrLname),
            () -> assertNull(userSecurityData.secUsrPwd),
            () -> assertNull(userSecurityData.secUsrType)
        );
    }
}