"""
file_writer.py (ONLINE VERSION)
--------------------------------
Writes converted files to the output directory structure:

converted-usingAgent/
  java/
    dto/            <- copybook Java DTO classes
    controllers/    <- CICS COBOL REST controllers
  tests/
    java/
      dto/          <- JUnit tests for DTOs
      controllers/  <- JUnit tests for controllers
  docs/
"""

import logging
import shutil
from pathlib import Path
from datetime import datetime

logger = logging.getLogger("FileWriter")


class FileWriter:

    def __init__(self, out_dir: str, clean: bool = False):
        self.out = Path(out_dir)
        if clean and self.out.exists():
            shutil.rmtree(self.out)
            logger.info(f"Cleaned output directory: {self.out}")
        self._create_structure()
        self.written = []

    def _create_structure(self):
        dirs = [
            self.out / "java" / "dto",
            self.out / "java" / "controllers",
            self.out / "tests" / "java" / "dto",
            self.out / "tests" / "java" / "controllers",
            self.out / "docs",
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)
        logger.info(f"Output structure created at: {self.out.resolve()}")

    # Package mappings for each output directory
    PACKAGE_MAP = {
        "dto":         "com.carddemo.dto",
        "controllers": "com.carddemo.controllers",
    }

    def write_java_record(self, class_name: str, content: str):
        """Writes a Java DTO class (from copybook) to java/dto/"""
        path = self.out / "java" / "dto" / f"{class_name}.java"
        self._write(path, content, "com.carddemo.dto")

    def write_java_service(self, class_name: str, content: str):
        """Writes a Spring Boot controller (from COBOL) to java/controllers/"""
        path = self.out / "java" / "controllers" / f"{class_name}.java"
        self._write(path, content, "com.carddemo.controllers")

    def write_java_test_record(self, class_name: str, content: str):
        """Writes a JUnit test for a DTO class to tests/java/dto/"""
        path = self.out / "tests" / "java" / "dto" / f"{class_name}.java"
        self._write(path, content, "com.carddemo.dto")

    def write_java_test_service(self, class_name: str, content: str):
        """Writes a JUnit test for a controller to tests/java/controllers/"""
        path = self.out / "tests" / "java" / "controllers" / f"{class_name}.java"
        self._write(path, content, "com.carddemo.controllers")

    def _write(self, path: Path, content: str, package: str = None):
        header = self._build_header(path)
        # Add package declaration automatically if not already present
        if package and not content.lstrip().startswith("package "):
            content = "package " + package + ";\n\n" + content
            logger.info("  Added package " + package + " to " + path.name)
        full_content = header + "\n" + content
        path.write_text(full_content, encoding="utf-8")
        file_str = str(path)
        if file_str not in self.written:
            self.written.append(file_str)
        logger.info(f"  Written: {path}")

    def _build_header(self, path: Path) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return f"// Generated by CardDemo Online Agentic Converter on {ts}\n// Source: AWS CardDemo (Apache 2.0)\n"

    def print_summary(self):
        logger.info("=" * 60)
        logger.info(f"FILES WRITTEN: {len(self.written)}")
        logger.info("=" * 60)
        for f in self.written:
            logger.info(f"  {f}")
