package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:59:17
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;

public class AccountRecord {

    @JsonProperty("ACCT-ID")
    public long acctId;

    @JsonProperty("ACCT-ACTIVE-STATUS")
    public String acctActiveStatus;

    @JsonProperty("ACCT-CURR-BAL")
    public BigDecimal acctCurrBal;

    @JsonProperty("ACCT-CREDIT-LIMIT")
    public BigDecimal acctCreditLimit;

    @JsonProperty("ACCT-CASH-CREDIT-LIMIT")
    public BigDecimal acctCashCreditLimit;

    @JsonProperty("ACCT-OPEN-DATE")
    public String acctOpenDate;

    @JsonProperty("ACCT-EXPIRAION-DATE")
    public String acctExpiraionDate;

    @JsonProperty("ACCT-REISSUE-DATE")
    public String acctReissueDate;

    @JsonProperty("ACCT-CURR-CYC-CREDIT")
    public BigDecimal acctCurrCycCredit;

    @JsonProperty("ACCT-CURR-CYC-DEBIT")
    public BigDecimal acctCurrCycDebit;

    @JsonProperty("ACCT-ADDR-ZIP")
    public String acctAddrZip;

    @JsonProperty("ACCT-GROUP-ID")
    public String acctGroupId;

    public AccountRecord() {
        this.acctId = 0L;
        this.acctActiveStatus = "";
        this.acctCurrBal = BigDecimal.ZERO;
        this.acctCreditLimit = BigDecimal.ZERO;
        this.acctCashCreditLimit = BigDecimal.ZERO;
        this.acctOpenDate = "";
        this.acctExpiraionDate = "";
        this.acctReissueDate = "";
        this.acctCurrCycCredit = BigDecimal.ZERO;
        this.acctCurrCycDebit = BigDecimal.ZERO;
        this.acctAddrZip = "";
        this.acctGroupId = "";
    }

    @Override
    public String toString() {
        return "AccountRecord{" +
                "acctId=" + acctId +
                ", acctActiveStatus='" + acctActiveStatus + '\'' +
                ", acctCurrBal=" + acctCurrBal +
                ", acctCreditLimit=" + acctCreditLimit +
                ", acctCashCreditLimit=" + acctCashCreditLimit +
                ", acctOpenDate='" + acctOpenDate + '\'' +
                ", acctExpiraionDate='" + acctExpiraionDate + '\'' +
                ", acctReissueDate='" + acctReissueDate + '\'' +
                ", acctCurrCycCredit=" + acctCurrCycCredit +
                ", acctCurrCycDebit=" + acctCurrCycDebit +
                ", acctAddrZip='" + acctAddrZip + '\'' +
                ", acctGroupId='" + acctGroupId + '\'' +
                '}';
    }
}