package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:02:04
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;

public class CardDemoCommArea {

    // 88 level constants for CDEMO-USER-TYPE
    public static final String CDEMO_USRTYP_ADMIN = "A";
    public static final String CDEMO_USRTYP_USER = "U";

    // 88 level constants for CDEMO-PGM-CONTEXT
    public static final int CDEMO_PGM_ENTER = 0;
    public static final int CDEMO_PGM_REENTER = 1;

    // CDEMO-GENERAL-INFO fields
    @JsonProperty("cdemoFromTranid")
    public String cdemoFromTranid;

    @JsonProperty("cdemoFromProgram")
    public String cdemoFromProgram;

    @JsonProperty("cdemoToTranid")
    public String cdemoToTranid;

    @JsonProperty("cdemoToProgram")
    public String cdemoToProgram;

    @JsonProperty("cdemoUserId")
    public String cdemoUserId;

    @JsonProperty("cdemoUserType")
    public String cdemoUserType;

    @JsonProperty("cdemoPgmContext")
    public int cdemoPgmContext;

    // CDEMO-CUSTOMER-INFO fields
    @JsonProperty("cdemoCustId")
    public long cdemoCustId;

    @JsonProperty("cdemoCustFname")
    public String cdemoCustFname;

    @JsonProperty("cdemoCustMname")
    public String cdemoCustMname;

    @JsonProperty("cdemoCustLname")
    public String cdemoCustLname;

    // CDEMO-ACCOUNT-INFO fields
    @JsonProperty("cdemoAcctId")
    public long cdemoAcctId;

    @JsonProperty("cdemoAcctStatus")
    public String cdemoAcctStatus;

    // CDEMO-CARD-INFO fields
    @JsonProperty("cdemoCardNum")
    public long cdemoCardNum;

    // CDEMO-MORE-INFO fields
    @JsonProperty("cdemoLastMap")
    public String cdemoLastMap;

    @JsonProperty("cdemoLastMapset")
    public String cdemoLastMapset;

    public CardDemoCommArea() {
        this.cdemoFromTranid = "";
        this.cdemoFromProgram = "";
        this.cdemoToTranid = "";
        this.cdemoToProgram = "";
        this.cdemoUserId = "";
        this.cdemoUserType = "";
        this.cdemoPgmContext = 0;
        this.cdemoCustId = 0L;
        this.cdemoCustFname = "";
        this.cdemoCustMname = "";
        this.cdemoCustLname = "";
        this.cdemoAcctId = 0L;
        this.cdemoAcctStatus = "";
        this.cdemoCardNum = 0L;
        this.cdemoLastMap = "";
        this.cdemoLastMapset = "";
    }

    public boolean isAdmin() {
        return "A".equals(cdemoUserType != null ? cdemoUserType.trim() : "");
    }

    public boolean isRegularUser() {
        return "U".equals(cdemoUserType != null ? cdemoUserType.trim() : "");
    }

    public boolean isPgmEnter() {
        return cdemoPgmContext == CDEMO_PGM_ENTER;
    }

    public boolean isPgmReenter() {
        return cdemoPgmContext == CDEMO_PGM_REENTER;
    }

    @Override
    public String toString() {
        return "CardDemoCommArea{" +
                "cdemoFromTranid='" + cdemoFromTranid + '\'' +
                ", cdemoFromProgram='" + cdemoFromProgram + '\'' +
                ", cdemoToTranid='" + cdemoToTranid + '\'' +
                ", cdemoToProgram='" + cdemoToProgram + '\'' +
                ", cdemoUserId='" + cdemoUserId + '\'' +
                ", cdemoUserType='" + cdemoUserType + '\'' +
                ", cdemoPgmContext=" + cdemoPgmContext +
                ", cdemoCustId=" + cdemoCustId +
                ", cdemoCustFname='" + cdemoCustFname + '\'' +
                ", cdemoCustMname='" + cdemoCustMname + '\'' +
                ", cdemoCustLname='" + cdemoCustLname + '\'' +
                ", cdemoAcctId=" + cdemoAcctId +
                ", cdemoAcctStatus='" + cdemoAcctStatus + '\'' +
                ", cdemoCardNum=" + cdemoCardNum +
                ", cdemoLastMap='" + cdemoLastMap + '\'' +
                ", cdemoLastMapset='" + cdemoLastMapset + '\'' +
                '}';
    }
}