package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:59:44
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class CardXrefRecord {

    @JsonProperty("xref-card-num")
    public String xrefCardNum;

    @JsonProperty("xref-cust-id")
    public long xrefCustId;

    @JsonProperty("xref-acct-id")
    public long xrefAcctId;

    public CardXrefRecord() {
        this.xrefCardNum = "";
        this.xrefCustId = 0L;
        this.xrefAcctId = 0L;
    }

    @Override
    public String toString() {
        return "CardXrefRecord{" +
                "xrefCardNum='" + xrefCardNum + '\'' +
                ", xrefCustId=" + xrefCustId +
                ", xrefAcctId=" + xrefAcctId +
                '}';
    }
}