package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:00:07
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class CustomerRecord {

    @JsonProperty("CUST-ID")
    public long custId;

    @JsonProperty("CUST-FIRST-NAME")
    public String custFirstName;

    @JsonProperty("CUST-MIDDLE-NAME")
    public String custMiddleName;

    @JsonProperty("CUST-LAST-NAME")
    public String custLastName;

    @JsonProperty("CUST-ADDR-LINE-1")
    public String custAddrLine1;

    @JsonProperty("CUST-ADDR-LINE-2")
    public String custAddrLine2;

    @JsonProperty("CUST-ADDR-LINE-3")
    public String custAddrLine3;

    @JsonProperty("CUST-ADDR-STATE-CD")
    public String custAddrStateCd;

    @JsonProperty("CUST-ADDR-COUNTRY-CD")
    public String custAddrCountryCd;

    @JsonProperty("CUST-ADDR-ZIP")
    public String custAddrZip;

    @JsonProperty("CUST-PHONE-NUM-1")
    public String custPhoneNum1;

    @JsonProperty("CUST-PHONE-NUM-2")
    public String custPhoneNum2;

    @JsonProperty("CUST-SSN")
    public long custSsn;

    @JsonProperty("CUST-GOVT-ISSUED-ID")
    public String custGovtIssuedId;

    @JsonProperty("CUST-DOB-YYYY-MM-DD")
    public String custDobYyyyMmDd;

    @JsonProperty("CUST-EFT-ACCOUNT-ID")
    public String custEftAccountId;

    @JsonProperty("CUST-PRI-CARD-HOLDER-IND")
    public String custPriCardHolderInd;

    @JsonProperty("CUST-FICO-CREDIT-SCORE")
    public int custFicoCreditScore;

    public CustomerRecord() {
        this.custId = 0L;
        this.custFirstName = "";
        this.custMiddleName = "";
        this.custLastName = "";
        this.custAddrLine1 = "";
        this.custAddrLine2 = "";
        this.custAddrLine3 = "";
        this.custAddrStateCd = "";
        this.custAddrCountryCd = "";
        this.custAddrZip = "";
        this.custPhoneNum1 = "";
        this.custPhoneNum2 = "";
        this.custSsn = 0L;
        this.custGovtIssuedId = "";
        this.custDobYyyyMmDd = "";
        this.custEftAccountId = "";
        this.custPriCardHolderInd = "";
        this.custFicoCreditScore = 0;
    }

    @Override
    public String toString() {
        return "CustomerRecord{" +
                "custId=" + custId +
                ", custFirstName='" + custFirstName + '\'' +
                ", custMiddleName='" + custMiddleName + '\'' +
                ", custLastName='" + custLastName + '\'' +
                ", custAddrLine1='" + custAddrLine1 + '\'' +
                ", custAddrLine2='" + custAddrLine2 + '\'' +
                ", custAddrLine3='" + custAddrLine3 + '\'' +
                ", custAddrStateCd='" + custAddrStateCd + '\'' +
                ", custAddrCountryCd='" + custAddrCountryCd + '\'' +
                ", custAddrZip='" + custAddrZip + '\'' +
                ", custPhoneNum1='" + custPhoneNum1 + '\'' +
                ", custPhoneNum2='" + custPhoneNum2 + '\'' +
                ", custSsn=" + custSsn +
                ", custGovtIssuedId='" + custGovtIssuedId + '\'' +
                ", custDobYyyyMmDd='" + custDobYyyyMmDd + '\'' +
                ", custEftAccountId='" + custEftAccountId + '\'' +
                ", custPriCardHolderInd='" + custPriCardHolderInd + '\'' +
                ", custFicoCreditScore=" + custFicoCreditScore +
                '}';
    }
}