package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:58:05
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class DateData {
    
    // WS-CURDATE-DATA group
    // WS-CURDATE group
    @JsonProperty("WS-CURDATE-YEAR")
    public int wsCurdateYear = 0;
    
    @JsonProperty("WS-CURDATE-MONTH")
    public int wsCurdateMonth = 0;
    
    @JsonProperty("WS-CURDATE-DAY")
    public int wsCurdateDay = 0;
    
    @JsonProperty("WS-CURDATE-N")
    public long wsCurdateN = 0L;
    
    // WS-CURTIME group
    @JsonProperty("WS-CURTIME-HOURS")
    public int wsCurtimeHours = 0;
    
    @JsonProperty("WS-CURTIME-MINUTE")
    public int wsCurtimeMinute = 0;
    
    @JsonProperty("WS-CURTIME-SECOND")
    public int wsCurtimeSecond = 0;
    
    @JsonProperty("WS-CURTIME-MILSEC")
    public int wsCurtimeMilsec = 0;
    
    @JsonProperty("WS-CURTIME-N")
    public long wsCurtimeN = 0L;
    
    // WS-CURDATE-MM-DD-YY group
    @JsonProperty("WS-CURDATE-MM")
    public int wsCurdateMm = 0;
    
    @JsonProperty("WS-CURDATE-DD")
    public int wsCurdateDd = 0;
    
    @JsonProperty("WS-CURDATE-YY")
    public int wsCurdateYy = 0;
    
    // WS-CURTIME-HH-MM-SS group
    @JsonProperty("WS-CURTIME-HH")
    public int wsCurtimeHh = 0;
    
    @JsonProperty("WS-CURTIME-MM")
    public int wsCurtimeMm = 0;
    
    @JsonProperty("WS-CURTIME-SS")
    public int wsCurtimeSs = 0;
    
    // WS-TIMESTAMP group
    @JsonProperty("WS-TIMESTAMP-DT-YYYY")
    public int wsTimestampDtYyyy = 0;
    
    @JsonProperty("WS-TIMESTAMP-DT-MM")
    public int wsTimestampDtMm = 0;
    
    @JsonProperty("WS-TIMESTAMP-DT-DD")
    public int wsTimestampDtDd = 0;
    
    @JsonProperty("WS-TIMESTAMP-TM-HH")
    public int wsTimestampTmHh = 0;
    
    @JsonProperty("WS-TIMESTAMP-TM-MM")
    public int wsTimestampTmMm = 0;
    
    @JsonProperty("WS-TIMESTAMP-TM-SS")
    public int wsTimestampTmSs = 0;
    
    @JsonProperty("WS-TIMESTAMP-TM-MS6")
    public int wsTimestampTmMs6 = 0;
    
    public DateData() {
    }
    
    public String getFormattedCurdate() {
        return String.format("%04d%02d%02d", wsCurdateYear, wsCurdateMonth, wsCurdateDay);
    }
    
    public String getFormattedCurtime() {
        return String.format("%02d%02d%02d%02d", wsCurtimeHours, wsCurtimeMinute, wsCurtimeSecond, wsCurtimeMilsec);
    }
    
    public String getFormattedCurdateMmDdYy() {
        return String.format("%02d/%02d/%02d", wsCurdateMm, wsCurdateDd, wsCurdateYy);
    }
    
    public String getFormattedCurtimeHhMmSs() {
        return String.format("%02d:%02d:%02d", wsCurtimeHh, wsCurtimeMm, wsCurtimeSs);
    }
    
    public String getFormattedTimestamp() {
        return String.format("%04d-%02d-%02d %02d:%02d:%02d.%06d",
            wsTimestampDtYyyy, wsTimestampDtMm, wsTimestampDtDd,
            wsTimestampTmHh, wsTimestampTmMm, wsTimestampTmSs, wsTimestampTmMs6);
    }
    
    @Override
    public String toString() {
        return "DateData{" +
            "wsCurdateYear=" + wsCurdateYear +
            ", wsCurdateMonth=" + wsCurdateMonth +
            ", wsCurdateDay=" + wsCurdateDay +
            ", wsCurdateN=" + wsCurdateN +
            ", wsCurtimeHours=" + wsCurtimeHours +
            ", wsCurtimeMinute=" + wsCurtimeMinute +
            ", wsCurtimeSecond=" + wsCurtimeSecond +
            ", wsCurtimeMilsec=" + wsCurtimeMilsec +
            ", wsCurtimeN=" + wsCurtimeN +
            ", wsCurdateMm=" + wsCurdateMm +
            ", wsCurdateDd=" + wsCurdateDd +
            ", wsCurdateYy=" + wsCurdateYy +
            ", wsCurtimeHh=" + wsCurtimeHh +
            ", wsCurtimeMm=" + wsCurtimeMm +
            ", wsCurtimeSs=" + wsCurtimeSs +
            ", wsTimestampDtYyyy=" + wsTimestampDtYyyy +
            ", wsTimestampDtMm=" + wsTimestampDtMm +
            ", wsTimestampDtDd=" + wsTimestampDtDd +
            ", wsTimestampTmHh=" + wsTimestampTmHh +
            ", wsTimestampTmMm=" + wsTimestampTmMm +
            ", wsTimestampTmSs=" + wsTimestampTmSs +
            ", wsTimestampTmMs6=" + wsTimestampTmMs6 +
            '}';
    }
}