package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:02:55
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class DateData {

    @JsonProperty("ws-curdate-year")
    public int wsCurdateYear = 0;

    @JsonProperty("ws-curdate-month")
    public int wsCurdateMonth = 0;

    @JsonProperty("ws-curdate-day")
    public int wsCurdateDay = 0;

    @JsonProperty("ws-curdate-n")
    public long wsCurdateN = 0L;

    @JsonProperty("ws-curtime-hours")
    public int wsCurtimeHours = 0;

    @JsonProperty("ws-curtime-minute")
    public int wsCurtimeMinute = 0;

    @JsonProperty("ws-curtime-second")
    public int wsCurtimeSecond = 0;

    @JsonProperty("ws-curtime-milsec")
    public int wsCurtimeMilsec = 0;

    @JsonProperty("ws-curtime-n")
    public long wsCurtimeN = 0L;

    @JsonProperty("ws-curdate-mm")
    public int wsCurdateMm = 0;

    @JsonProperty("ws-curdate-dd")
    public int wsCurdateDd = 0;

    @JsonProperty("ws-curdate-yy")
    public int wsCurdateYy = 0;

    @JsonProperty("ws-curtime-hh")
    public int wsCurtimeHh = 0;

    @JsonProperty("ws-curtime-mm")
    public int wsCurtimeMm = 0;

    @JsonProperty("ws-curtime-ss")
    public int wsCurtimeSs = 0;

    @JsonProperty("ws-timestamp-dt-yyyy")
    public int wsTimestampDtYyyy = 0;

    @JsonProperty("ws-timestamp-dt-mm")
    public int wsTimestampDtMm = 0;

    @JsonProperty("ws-timestamp-dt-dd")
    public int wsTimestampDtDd = 0;

    @JsonProperty("ws-timestamp-tm-hh")
    public int wsTimestampTmHh = 0;

    @JsonProperty("ws-timestamp-tm-mm")
    public int wsTimestampTmMm = 0;

    @JsonProperty("ws-timestamp-tm-ss")
    public int wsTimestampTmSs = 0;

    @JsonProperty("ws-timestamp-tm-ms6")
    public long wsTimestampTmMs6 = 0L;

    public DateData() {
    }

    public String getFormattedCurdate() {
        return String.format("%04d%02d%02d", wsCurdateYear, wsCurdateMonth, wsCurdateDay);
    }

    public String getFormattedCurtime() {
        return String.format("%02d%02d%02d%02d", wsCurtimeHours, wsCurtimeMinute, wsCurtimeSecond, wsCurtimeMilsec);
    }

    public String getFormattedCurdateMmDdYy() {
        return String.format("%02d/%02d/%02d", wsCurdateMm, wsCurdateDd, wsCurdateYy);
    }

    public String getFormattedCurtimeHhMmSs() {
        return String.format("%02d:%02d:%02d", wsCurtimeHh, wsCurtimeMm, wsCurtimeSs);
    }

    public String getFormattedTimestamp() {
        return String.format("%04d-%02d-%02d %02d:%02d:%02d.%06d",
                wsTimestampDtYyyy, wsTimestampDtMm, wsTimestampDtDd,
                wsTimestampTmHh, wsTimestampTmMm, wsTimestampTmSs, wsTimestampTmMs6);
    }

    @Override
    public String toString() {
        return "DateData{" +
                "wsCurdateYear=" + wsCurdateYear +
                ", wsCurdateMonth=" + wsCurdateMonth +
                ", wsCurdateDay=" + wsCurdateDay +
                ", wsCurdateN=" + wsCurdateN +
                ", wsCurtimeHours=" + wsCurtimeHours +
                ", wsCurtimeMinute=" + wsCurtimeMinute +
                ", wsCurtimeSecond=" + wsCurtimeSecond +
                ", wsCurtimeMilsec=" + wsCurtimeMilsec +
                ", wsCurtimeN=" + wsCurtimeN +
                ", wsCurdateMm=" + wsCurdateMm +
                ", wsCurdateDd=" + wsCurdateDd +
                ", wsCurdateYy=" + wsCurdateYy +
                ", wsCurtimeHh=" + wsCurtimeHh +
                ", wsCurtimeMm=" + wsCurtimeMm +
                ", wsCurtimeSs=" + wsCurtimeSs +
                ", wsTimestampDtYyyy=" + wsTimestampDtYyyy +
                ", wsTimestampDtMm=" + wsTimestampDtMm +
                ", wsTimestampDtDd=" + wsTimestampDtDd +
                ", wsTimestampTmHh=" + wsTimestampTmHh +
                ", wsTimestampTmMm=" + wsTimestampTmMm +
                ", wsTimestampTmSs=" + wsTimestampTmSs +
                ", wsTimestampTmMs6=" + wsTimestampTmMs6 +
                '}';
    }
}