package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:58:37
// Source: AWS CardDemo (Apache 2.0)

public class MessageData {
    
    public String ccdaMsgThankYou;
    public String ccdaMsgInvalidKey;
    
    public MessageData() {
        this.ccdaMsgThankYou = "Thank you for using CardDemo application...      ";
        this.ccdaMsgInvalidKey = "Invalid key pressed. Please see below...         ";
    }
    
    @Override
    public String toString() {
        return "MessageData{" +
                "ccdaMsgThankYou='" + ccdaMsgThankYou + '\'' +
                ", ccdaMsgInvalidKey='" + ccdaMsgInvalidKey + '\'' +
                '}';
    }
}