package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:02:29
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class TitleData {

    @JsonProperty("title01")
    public String title01;

    @JsonProperty("title02")
    public String title02;

    @JsonProperty("thankYou")
    public String thankYou;

    public TitleData() {
        this.title01 = "      AWS Mainframe Modernization       ";
        this.title02 = "              CardDemo                  ";
        this.thankYou = "Thank you for using CCDA application... ";
    }

    @Override
    public String toString() {
        return "TitleData{" +
                "title01='" + title01 + '\'' +
                ", title02='" + title02 + '\'' +
                ", thankYou='" + thankYou + '\'' +
                '}';
    }
}