package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-21 23:57:37
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class TitleData {

    @JsonProperty("CCDA-TITLE01")
    public String ccdaTitle01;

    @JsonProperty("CCDA-TITLE02")
    public String ccdaTitle02;

    @JsonProperty("CCDA-THANK-YOU")
    public String ccdaThankYou;

    public TitleData() {
        this.ccdaTitle01 = "      AWS Mainframe Modernization       ";
        this.ccdaTitle02 = "              CardDemo                  ";
        this.ccdaThankYou = "Thank you for using CCDA application... ";
    }

    @Override
    public String toString() {
        return "TitleData{" +
                "ccdaTitle01='" + ccdaTitle01 + '\'' +
                ", ccdaTitle02='" + ccdaTitle02 + '\'' +
                ", ccdaThankYou='" + ccdaThankYou + '\'' +
                '}';
    }
}