package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 00:00:38
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;

public class TransactionRecord {

    @JsonProperty("TRAN-ID")
    public String tranId;

    @JsonProperty("TRAN-TYPE-CD")
    public String tranTypeCd;

    @JsonProperty("TRAN-CAT-CD")
    public int tranCatCd;

    @JsonProperty("TRAN-SOURCE")
    public String tranSource;

    @JsonProperty("TRAN-DESC")
    public String tranDesc;

    @JsonProperty("TRAN-AMT")
    public BigDecimal tranAmt;

    @JsonProperty("TRAN-MERCHANT-ID")
    public long tranMerchantId;

    @JsonProperty("TRAN-MERCHANT-NAME")
    public String tranMerchantName;

    @JsonProperty("TRAN-MERCHANT-CITY")
    public String tranMerchantCity;

    @JsonProperty("TRAN-MERCHANT-ZIP")
    public String tranMerchantZip;

    @JsonProperty("TRAN-CARD-NUM")
    public String tranCardNum;

    @JsonProperty("TRAN-ORIG-TS")
    public String tranOrigTs;

    @JsonProperty("TRAN-PROC-TS")
    public String tranProcTs;

    public TransactionRecord() {
        this.tranId = "";
        this.tranTypeCd = "";
        this.tranCatCd = 0;
        this.tranSource = "";
        this.tranDesc = "";
        this.tranAmt = BigDecimal.ZERO;
        this.tranMerchantId = 0L;
        this.tranMerchantName = "";
        this.tranMerchantCity = "";
        this.tranMerchantZip = "";
        this.tranCardNum = "";
        this.tranOrigTs = "";
        this.tranProcTs = "";
    }

    @Override
    public String toString() {
        return "TransactionRecord{" +
                "tranId='" + tranId + '\'' +
                ", tranTypeCd='" + tranTypeCd + '\'' +
                ", tranCatCd=" + tranCatCd +
                ", tranSource='" + tranSource + '\'' +
                ", tranDesc='" + tranDesc + '\'' +
                ", tranAmt=" + tranAmt +
                ", tranMerchantId=" + tranMerchantId +
                ", tranMerchantName='" + tranMerchantName + '\'' +
                ", tranMerchantCity='" + tranMerchantCity + '\'' +
                ", tranMerchantZip='" + tranMerchantZip + '\'' +
                ", tranCardNum='" + tranCardNum + '\'' +
                ", tranOrigTs='" + tranOrigTs + '\'' +
                ", tranProcTs='" + tranProcTs + '\'' +
                '}';
    }
}