package com.carddemo.dto;

// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:03:44
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class UserSecurityData {
    
    @JsonProperty("secUsrId")
    public String secUsrId;
    
    @JsonProperty("secUsrFname")
    public String secUsrFname;
    
    @JsonProperty("secUsrLname")
    public String secUsrLname;
    
    @JsonProperty("secUsrPwd")
    public String secUsrPwd;
    
    @JsonProperty("secUsrType")
    public String secUsrType;
    
    public UserSecurityData() {
        this.secUsrId = "";
        this.secUsrFname = "";
        this.secUsrLname = "";
        this.secUsrPwd = "";
        this.secUsrType = "";
    }
    
    @Override
    public String toString() {
        return "UserSecurityData{" +
                "secUsrId='" + secUsrId + '\'' +
                ", secUsrFname='" + secUsrFname + '\'' +
                ", secUsrLname='" + secUsrLname + '\'' +
                ", secUsrPwd='" + secUsrPwd + '\'' +
                ", secUsrType='" + secUsrType + '\'' +
                '}';
    }
}