// Generated by CardDemo Online Agentic Converter on 2026-03-22 01:03:24
// Source: AWS CardDemo (Apache 2.0)

import com.fasterxml.jackson.annotation.JsonProperty;

public class MessageData {
    
    @JsonProperty("ccdaMsgThankYou")
    public String ccdaMsgThankYou;
    
    @JsonProperty("ccdaMsgInvalidKey")
    public String ccdaMsgInvalidKey;
    
    public MessageData() {
        this.ccdaMsgThankYou = "Thank you for using CardDemo application...      ";
        this.ccdaMsgInvalidKey = "Invalid key pressed. Please see below...         ";
    }
    
    @Override
    public String toString() {
        return "MessageData{" +
                "ccdaMsgThankYou='" + ccdaMsgThankYou + '\'' +
                ", ccdaMsgInvalidKey='" + ccdaMsgInvalidKey + '\'' +
                '}';
    }
}